"""The already-public-passwords check.

BACKEND-PLAN.md Phase 5: "Check against a local list of the top 100,000 breached
passwords. Local, not an external API — no third party learns anything about our users'
passwords, and there is no network dependency in the signup path."

The local part is the security property. Every hosted alternative — including the k-anonymity
range API, which is genuinely well designed — puts a prefix of the hash of a password
somebody is about to use onto somebody else's server, and puts a network call in the middle
of signup where a timeout becomes an outage.

**The list currently shipped is not the real one.** It is generated by
tools/build_password_list.py from the shapes that dominate breach corpora: the common
passwords themselves, plus the mechanical variations people apply to them — a year, a digit
run, a trailing punctuation mark, a capitalised first letter. That catches the large
majority of what people actually pick, and it is not a substitute for the real corpus.
`stats()` reports the entry count and `deployment_warnings()` says so out loud in
production, because a check that quietly covers less than it claims is the failure mode
this project keeps running into.

Matching is done on the case-folded form. Real corpora are case-sensitive, so folding makes
the check strictly broader than the list it was built from — "Password1" is refused because
"password1" is on it. That is the right direction to be wrong in.
"""

from __future__ import annotations

import unicodedata
from pathlib import Path

# The bundled list. A path rather than a constant so a deployment can point at the real
# corpus without a code change (PG_PASSWORD_LIST).
DEFAULT_PATH = Path(__file__).resolve().parent / "data" / "common_passwords.txt"

# A file that exists but holds almost nothing is the dangerous case: the check runs, passes
# everything, and looks healthy. Refuse to start instead. The number is low enough that a
# deliberately minimal list is still usable in a test and high enough that a truncated
# download is caught.
MIN_ENTRIES = 500

_entries: frozenset[str] | None = None
_source: str = "not loaded"


class BreachListError(RuntimeError):
    """The list is missing or too small to be a control. Raised at boot, never caught."""


def _fold(value: str) -> str:
    return unicodedata.normalize("NFKC", value).casefold()


def load(path: Path | None = None) -> int:
    """Read the list into memory and return the entry count.

    Called from the app factory so a broken list stops the boot rather than surfacing as
    "signup accepts hunter2" months later.
    """
    global _entries, _source

    target = path or DEFAULT_PATH
    if not target.is_file():
        raise BreachListError(
            f"The common-password list is missing at {target}. Signup would then accept "
            "passwords that are already public, and nothing would report a problem. "
            "Regenerate it with: python tools/build_password_list.py"
        )

    text = target.read_text(encoding="utf-8", errors="replace")
    entries = {
        _fold(stripped)
        for line in text.splitlines()
        if (stripped := line.strip()) and not stripped.startswith("#")
    }

    if len(entries) < MIN_ENTRIES:
        raise BreachListError(
            f"The common-password list at {target} holds {len(entries)} entries, below the "
            f"{MIN_ENTRIES} minimum. A list this small does not refuse anything anyone "
            "actually picks, so the check would pass while protecting nobody."
        )

    _entries = frozenset(entries)
    _source = str(target)
    return len(_entries)


def _loaded() -> frozenset[str]:
    if _entries is None:
        load()
    assert _entries is not None  # noqa: S101 - load() raises rather than returning None
    return _entries


def is_breached(password: str) -> bool:
    return _fold(password) in _loaded()


def stats() -> dict[str, object]:
    """For the boot log. Makes the size of the list a visible fact rather than a claim."""
    return {"entries": len(_loaded()), "source": _source}


def reset_for_tests() -> None:
    global _entries, _source
    _entries = None
    _source = "not loaded"
