"""Cross-site request forgery defence, applied to every state-changing request.

BACKEND-PLAN.md Phase 5 asks for three layers, and this module is two of them — the third,
`SameSite=Lax`, is a property of the cookie itself and lives in `sessions.cookie_kwargs`.

  2. **Origin must match.** Every browser sends `Origin` on a cross-site POST, and every
     current browser sends it on same-site POSTs too. A *missing* `Origin` on a
     state-changing request is a rejection, not a pass — treating absence as permission is
     how this control is usually defeated, because the attacker chooses whether to send it.
  3. **A per-session token in a custom header.** A custom header cannot be set by a plain
     HTML form or an `img` tag, so requiring one already forecloses the classic attacks; and
     because the value is derived from *this* session (see `sessions.csrf_for`), an attacker
     who can plant a cookie on the domain still cannot produce a matching value.

**Middleware, not a dependency.** Authorization belongs on the route, where it is visible in
review — but CSRF is a property of the transport, and the failure mode is a route that
forgets it. A middleware fails closed for routes nobody has written yet, which is exactly
the shape of mistake worth designing against. The cost is an exemption list, so the
exemptions are named here, in one place, and a test asserts the list is precisely this and
nothing more.
"""

from __future__ import annotations

import json
from http.cookies import SimpleCookie

from starlette.types import ASGIApp, Receive, Scope, Send

from app.config import Settings
from app.logging import logger
from app.security import sessions

log = logger("postgame.csrf")

UNSAFE_METHODS = frozenset({"POST", "PUT", "PATCH", "DELETE"})

# The only paths a browser may reach with a state-changing method and no Origin.
#
# `/api/csp-report`: the reports are generated by the browser's own CSP machinery, which
# sends them with `Origin: null` or with none at all depending on the browser and on
# whether the violating document was sandboxed. The endpoint takes no action on behalf of
# anyone, holds no session, writes nothing, and is separately rate limited — there is
# nothing here to forge.
EXEMPT_PATHS = frozenset({"/api/csp-report"})

# Paths where the Origin check applies in full but the session-bound token does not.
#
# Requiring a token derived from the current session in order to *create* a session is
# circular, and the failure is worse than circular: a browser holding a stale cookie — one
# whose session was revoked, or expired, or belonged to a database that has since been reset
# — would be refused at the login form with a 403 it has no way to resolve, because the
# token it would need is derived from a cookie it cannot read. Clearing the cookie is not a
# fix either; the client cannot clear an HttpOnly cookie, and the server only gets to clear
# it on a request that succeeded.
#
# Nothing is given up. Layer 2 applies unchanged, and layer 3 has nothing to protect here:
# login CSRF — forcing a victim's browser to sign in as the attacker so their activity lands
# in the attacker's account — is a cross-site POST, which the Origin check refuses.
TOKEN_OPTIONAL_PATHS = frozenset({"/api/auth/login", "/api/auth/signup"})

FORBIDDEN = 403
ORIGIN_MESSAGE = "This request did not come from Postgame."
TOKEN_MESSAGE = (
    # noqa below: user-facing copy, not a credential.
    "This request is missing its security token. Please reload the page."  # noqa: S105
)


def _cookie_value(headers: list[tuple[bytes, bytes]], name: str) -> str | None:
    for key, value in headers:
        if key.lower() != b"cookie":
            continue
        jar = SimpleCookie()
        try:
            jar.load(value.decode("latin-1"))
        except Exception:  # noqa: BLE001, S112 - a malformed jar is simply no cookie
            continue
        if name in jar:
            return jar[name].value
    return None


def _header(headers: list[tuple[bytes, bytes]], name: str) -> str | None:
    wanted = name.lower().encode("latin-1")
    for key, value in headers:
        if key.lower() == wanted:
            return value.decode("latin-1")
    return None


class CsrfMiddleware:
    def __init__(self, app: ASGIApp, *, settings: Settings) -> None:
        self.app = app
        self.settings = settings
        self.cookie = sessions.cookie_name(settings)
        # One entry today. A list because staging sometimes fronts the same app from a
        # platform-generated hostname as well as the real one, and discovering that at
        # deploy time is better than discovering it as "login silently fails".
        self.allowed_origins = frozenset({settings.app_origin})

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http" or scope.get("method", "") not in UNSAFE_METHODS:
            await self.app(scope, receive, send)
            return

        path = scope.get("path", "")
        if path in EXEMPT_PATHS:
            await self.app(scope, receive, send)
            return

        headers: list[tuple[bytes, bytes]] = scope.get("headers", [])

        origin = _header(headers, "origin")
        if origin is None or origin not in self.allowed_origins:
            log.warning("csrf_origin_rejected", path=path, present=origin is not None)
            await self._deny(send, ORIGIN_MESSAGE)
            return

        token = _cookie_value(headers, self.cookie)
        if token is not None and path not in TOKEN_OPTIONAL_PATHS:
            presented = _header(headers, sessions.CSRF_HEADER)
            if not presented or not sessions.csrf_matches(self.settings, token, presented):
                # No session lookup here — the token is derived from the cookie by HMAC, so
                # this is decidable without touching the database. That matters: it means an
                # unauthenticated flood of forged writes costs no queries.
                log.warning("csrf_token_rejected", path=path, present=bool(presented))
                await self._deny(send, TOKEN_MESSAGE)
                return

        await self.app(scope, receive, send)

    async def _deny(self, send: Send, message: str) -> None:
        # Built by hand rather than through the exception handlers, because a middleware
        # rejection happens before the app is entered. The shape matches `errors._response`
        # so a client sees one error format everywhere.
        from app.logging import request_id

        body = json.dumps({"error": message, "request_id": request_id.get()}).encode("utf-8")
        await send(
            {
                "type": "http.response.start",
                "status": FORBIDDEN,
                "headers": [
                    (b"content-type", b"application/json"),
                    (b"content-length", str(len(body)).encode("latin-1")),
                ],
            }
        )
        await send({"type": "http.response.body", "body": body})
