/* Postgame — game catalogue, part 21
   Hand-written, because none of these are on Steam: the classic Lego games,
   plus console, handheld and mobile exclusives. These rows carry no Steam app
   id, so their covers come from the Wikipedia pipeline. */
window.GAME_ROWS = (window.GAME_ROWS || []).concat([
"Lego Island|1997|Mindscape|Adventure,Sandbox|PC|77|Build, drive, and let the Brickster escape. Formative for a generation.",
"Lego Island 2: The Brickster's Revenge|2001|Silicon Dreams|Adventure,Platformer|PC,PS1,GBA|65|The Brickster is out again, across a set of minigames.",
"Lego Racers|1999|High Voltage Software|Racing|PC,PS1,N64|76|Build your own kart, then win power-up bricks with it.",
"Lego Racers 2|2001|Attention to Detail|Racing|PC,PS2,GBA|70|An open hub between races, and Mars.",
"Lego Rock Raiders|1999|Data Design Interactive|Strategy,Simulation|PC,PS1|64|Mine a hostile planet with a very small crew.",
"Lego Creator|1998|Superscape|Sandbox,Simulation|PC|70|A digital brick box with no objective at all.",
"Lego Chess|1998|Krisalis Software|Strategy,Board Game|PC|72|Chess, but the pieces are pirates who act out every capture.",
"Lego Stunt Rally|2000|Intelligent Games|Racing|PC,GBC|68|Build the track, then race it.",
"Lego Soccer Mania|2002|Silicon Dreams|Sports|PC,PS2,GBA|64|Arcade football with power-ups and no offside rule.",
"Lego Drome Racers|2002|Attention to Detail|Racing|PC,PS2,GameCube|62|Futuristic circuit racing with upgradeable cars.",
"Lego Star Wars: The Video Game|2005|Traveller's Tales|Action Adventure|PS2,Xbox,GameCube,PC|80|The prequels retold in silent slapstick. It invented a genre.",
"Lego Star Wars II: The Original Trilogy|2006|Traveller's Tales|Action Adventure|PS2,Xbox 360,GameCube,PC|85|The good trilogy, and character building.",
"Bionicle Heroes|2006|Traveller's Tales|Action,Shooter|PS2,Xbox 360,GameCube,PC|68|Lego's own mythology as a third-person shooter.",
"Lego Battles|2009|Hellbent Games|RTS,Strategy|DS|73|A real-time strategy game on two screens, with wizards and pirates.",
"Lego Rock Band|2009|Harmonix|Rhythm|Wii,PS3,Xbox 360,DS|70|Harmonix's engine, family-friendly setlist, brick avatars.",
"Lego Universe|2010|NetDevil|MMO,Adventure|PC,Mac|74|A Lego MMO that shut down after two years and is still mourned.",
"Lego Legends of Chima: Laval's Journey|2013|Hellbent Games|Action Adventure|3DS,Vita,DS|55|A handheld outing for the tribal animal theme.",
"Lego Dimensions|2015|Traveller's Tales|Action Adventure,Party|PS4,Xbox One,Wii U,PS3|80|Toys-to-life crossover with Doctor Who, Gremlins and Portal in one game.",
"Lego Star Wars: Castaways|2021|Gameloft|Action Adventure|Mobile|68|A social Lego island exclusive to Apple Arcade.",
"Lego Alpha Team|2000|Digital Domain|Strategy,Puzzle|PC,GBC|66|Direct a squad of specialists past Ogel's traps.",
"Lego 2K Drive|2023|Visual Concepts|Racing,Open World|PC,PS5,Switch,Xbox Series|77|An open-world kart racer where your car rebuilds itself for terrain.",
"Mario Kart 7|2011|Nintendo EAD|Racing|3DS|85|Gliders, underwater karts, and the best handheld Mario Kart.",
"Kid Icarus: Uprising|2012|Project Sora|Action,Rail Shooter|3DS|83|Sharp writing and controls nobody agreed on.",
"Fire Emblem: The Blazing Blade|2003|Intelligent Systems|Tactics,JRPG|GBA|88|The one that introduced the west to Fire Emblem.",
"The Legend of Zelda: Phantom Hourglass|2007|Nintendo EAD|Action Adventure|DS|90|Stylus-drawn maps and a dungeon you revisit constantly.",
"The Legend of Zelda: Spirit Tracks|2009|Nintendo EAD|Action Adventure|DS|87|Link drives a train, and Zelda comes along as a ghost.",
"Metroid: Zero Mission|2004|Nintendo R&D1|Metroidvania|GBA|89|The first Metroid rebuilt with modern movement.",
"Metroid: Samus Returns|2017|MercurySteam|Metroidvania|3DS|85|The melee counter arrives and changes the series.",
"Wario Land 4|2001|Nintendo R&D1|Platformer|GBA|86|Grotesque, inventive, and built around escaping each level.",
"WarioWare: Smooth Moves|2006|Nintendo SPD|Party,Puzzle|Wii|83|Hold the remote in nineteen daft ways.",
"Rhythm Heaven Fever|2011|Nintendo SPD|Rhythm|Wii|84|Two buttons, immaculate timing, badminton with monkeys.",
"Donkey Kong Jungle Beat|2004|Nintendo EAD|Platformer|GameCube|80|Played entirely with bongo drums, and genuinely brilliant.",
"Mario Power Tennis|2004|Camelot Software Planning|Sports|GameCube|81|Power shots, and the best of the Mario sports games.",
"Super Mario Land|1989|Nintendo R&D1|Platformer|GB|79|Tiny, strange, and the Game Boy's launch showpiece.",
"Super Mario Land 2: 6 Golden Coins|1992|Nintendo R&D1|Platformer|GB|85|Wario's debut, and a proper world map.",
"Kirby's Epic Yarn|2010|Good-Feel|Platformer|Wii|86|Everything made of fabric, and you cannot die.",
"Kirby: Nightmare in Dream Land|2002|HAL Laboratory|Platformer|GBA|81|Kirby's Adventure remade, with four-player minigames.",
"Eternal Darkness: Sanity's Requiem|2002|Silicon Knights|Horror,Action Adventure|GameCube|92|A sanity meter that pretends to delete your save.",
"Wave Race 64|1996|Nintendo EAD|Racing|N64|86|Jet ski racing with water physics nobody matched for years.",
"1080 Snowboarding|1998|Nintendo EAD|Sports|N64|88|Weighty, tricky, and beautiful for an N64 game.",
"Pilotwings 64|1996|Paradigm Entertainment|Simulation|N64|86|Hang gliding and a rocket belt over a tiny America.",
"Mother 3|2006|Brownie Brown|JRPG,Turn-Based|GBA|89|Never officially translated, and quietly devastating.",
"Advance Wars: Dual Strike|2005|Intelligent Systems|Tactics,Strategy|DS|89|Two screens, two armies, tag-team commanding officers.",
"Chibi-Robo!|2005|Skip Ltd|Adventure,Platformer|GameCube|76|A tiny robot tidying a family's house, on a battery timer.",
"Mario Golf: Toadstool Tour|2003|Camelot Software Planning|Sports|GameCube|81|The best golf swing meter Nintendo has shipped.",
"Pokemon Trading Card Game|1998|Hudson Soft|Card Game|GBC|80|The card game as an RPG, and better than it sounds.",
"Gran Turismo 5|2010|Polyphony Digital|Racing,Simulation|PS3|84|A thousand cars, five years late, still magnificent.",
"Ratchet & Clank: A Crack in Time|2009|Insomniac Games|Action Platformer|PS3|87|Time puzzles and the series' warmest story.",
"Resistance 3|2011|Insomniac Games|FPS|PS3|83|A bleak road trip across an occupied America.",
"Killzone 3|2011|Guerrilla Games|FPS|PS3|81|Jetpacks and the prettiest shooter on the PS3.",
"MotorStorm|2006|Evolution Studios|Racing|PS3|82|Off-road chaos where every vehicle class takes a different line.",
"Heavenly Sword|2007|Ninja Theory|Action|PS3|79|Six hours long, and Andy Serkis chewing every scene.",
"LittleBigPlanet 3|2014|Sumo Digital|Platformer,Sandbox|PS4,PS3|79|Three new characters and a decade of user levels behind it.",
"Tearaway|2013|Media Molecule|Platformer,Adventure|Vita|87|A papercraft world that reaches out through the Vita's touchpad.",
"Patapon 2|2008|Japan Studio|Rhythm,Strategy|PSP|84|Command an army by drumming. Pata pata pata pon.",
"LocoRoco|2006|Japan Studio|Platformer,Puzzle|PSP|83|Tilt the world and let the blobs roll. Impossibly cheerful.",
"Jeanne d'Arc|2006|Level-5|Tactics,JRPG|PSP|84|Joan of Arc with demons, and superb tactical design.",
"Persona 3 Portable|2009|Atlus|JRPG,Turn-Based|PSP|89|Direct party control and a female protagonist route.",
"God of War: Chains of Olympus|2008|Ready at Dawn|Action,Hack and Slash|PSP|91|Console-grade spectacle squeezed onto a handheld.",
"Gravity Rush 2|2017|Japan Studio|Action Adventure|PS4|80|Falling in every direction, with more of everything.",
"Astro Bot Rescue Mission|2018|Japan Studio|Platformer,VR|PS4|90|The best argument anyone made for VR platforming.",
"Uncharted: Golden Abyss|2011|Bend Studio|Action Adventure|Vita|80|A full Uncharted on a handheld, at launch.",
"Sly 3: Honor Among Thieves|2005|Sucker Punch Productions|Platformer,Stealth|PS2|83|The heist crew assembles for one last job.",
"Project Gotham Racing 2|2003|Bizarre Creations|Racing|Xbox|91|Kudos points for driving with style, and a killer soundtrack.",
"Ninja Gaiden Black|2005|Team Ninja|Action,Hack and Slash|Xbox|94|Punishing, precise, and still the benchmark for hard action games.",
"Panzer Dragoon Orta|2002|Smilebit|Rail Shooter|Xbox|88|A dragon, a rail, and art direction from another planet.",
"Forza Motorsport|2005|Turn 10 Studios|Racing,Simulation|Xbox|91|Microsoft's answer to Gran Turismo, and a good one.",
"Kameo: Elements of Power|2005|Rare|Action Adventure|Xbox 360|79|Shape-shift into elemental warriors across huge battles.",
"Alto's Odyssey|2018|Snowman|Endless Runner,Mobile|Mobile|85|Sandboarding as something close to meditation.",
"Threes!|2014|Sirvo|Puzzle,Mobile|Mobile|92|The elegant original that 2048 ripped off.",
"Device 6|2013|Simogo|Puzzle,Adventure|Mobile|91|A puzzle told as typography you rotate the phone to read.",
"Florence|2018|Mountains|Adventure,Mobile|Mobile,Switch|85|A relationship told in thirty minutes of small interactions.",
"Fruit Ninja|2010|Halfbrick Studios|Arcade,Mobile|Mobile|75|Slice fruit. One of the first great touchscreen ideas.",
"Temple Run|2011|Imangi Studios|Endless Runner,Mobile|Mobile|82|The endless runner that defined the form.",
"Cut the Rope|2010|ZeptoLab|Puzzle,Mobile|Mobile|85|Physics puzzles and a small green monster to feed.",
"Flappy Bird|2013|dotGears|Arcade,Mobile|Mobile|60|Pulled from sale at the height of its fame. Still infuriating.",
"Bad Piggies|2012|Rovio Entertainment|Puzzle,Mobile|Mobile|85|Build a contraption instead of firing a bird. Better than Angry Birds.",
"Real Racing 3|2013|Firemonkeys Studios|Racing,Mobile|Mobile|84|Console-quality racing on a phone, with a timer economy.",
"Pokemon Masters EX|2019|DeNA|JRPG,Mobile|Mobile|65|Three-on-three battles with pairs from every generation."
]);
