/* Postgame — game catalogue, part 10 of 10 */
window.GAME_ROWS = (window.GAME_ROWS || []).concat([
"Rayman 2: The Great Escape|1999|Ubisoft Montpellier|Platformer|PS1,N64,PC|92|The 3D leap done with real imagination.",
"Crash Bandicoot|1996|Naughty Dog|Platformer|PS1,PS4,Switch|80|Corridors, crates, and a very stubborn bandicoot.",
"Crash Bandicoot 3: Warped|1998|Naughty Dog|Platformer|PS1,PS4,Switch|91|Time travel levels and the series at its most varied.",
"Crash Team Racing|1999|Naughty Dog|Racing|PS1,PS4,Switch|88|The kart racer that genuinely rivalled Mario's.",
"Spyro the Dragon|1998|Insomniac Games|Platformer|PS1,PS4,Switch|85|Gliding, gems, and a purple dragon with attitude.",
"A Hat in Time|2017|Gears for Breakfast|Platformer|PC,PS4,Switch,Xbox One|79|The collect-a-thon revival nobody else managed.",
"Pizza Tower|2023|Tour De Pizza|Platformer|PC,Switch,PS5|86|Wario Land at a hundred miles an hour, hand-drawn.",
"Guacamelee!|2013|DrinkBox Studios|Metroidvania,Beat 'em up|PC,PS4,Switch,Xbox One|84|Luchador wrestling in a Metroidvania. Perfect fit.",
"Bloodstained: Ritual of the Night|2019|ArtPlay|Metroidvania|PC,PS4,Switch,Xbox One|83|Igarashi rebuilding Symphony of the Night from scratch.",
"Axiom Verge|2015|Thomas Happ|Metroidvania|PC,PS4,Switch,Xbox One|82|One developer, and glitches as a mechanic.",
"Prince of Persia: The Lost Crown|2024|Ubisoft Montpellier|Metroidvania,Platformer|PC,PS5,Switch|86|The best 2D action platformer Ubisoft has ever shipped.",
"Animal Well|2024|Billy Basso|Metroidvania,Puzzle|PC,PS5,Switch|89|One person, five years, secrets inside secrets.",
"The Messenger|2018|Sabotage Studio|Platformer,Metroidvania|PC,PS4,Switch|84|Starts as an 8-bit ninja game, then changes shape.",
"Rogue Legacy 2|2022|Cellar Door Games|Roguelike,Platformer|PC,Switch,Xbox Series|85|Each heir inherits the castle and a genetic quirk.",
"Noita|2020|Nolla Games|Roguelike,Action|PC|85|Every pixel simulated. You will kill yourself with your own spell.",
"Loop Hero|2021|Four Quarters|Roguelike,Card Game|PC,Switch,Mobile|82|Place the tiles, then watch your hero walk into them.",
"Inscryption|2021|Daniel Mullins Games|Card Game,Horror|PC,PS5,Switch|85|A deckbuilder that keeps escaping its own genre.",
"Fez|2012|Polytron|Puzzle,Platformer|PC,PS4,Switch,Xbox 360|91|Rotate a 2D world through a third dimension.",
"Gris|2018|Nomada Studio|Platformer,Adventure|PC,PS4,Switch|82|Watercolour grief, wordless and beautiful.",
"Abzu|2016|Giant Squid|Adventure|PC,PS4,Switch,Xbox One|79|Journey underwater, with an extraordinary score.",
"Kentucky Route Zero|2013|Cardboard Computer|Adventure|PC,PS4,Switch,Xbox One|86|Magical-realist debt and a highway that is not on maps.",
"Night in the Woods|2017|Infinite Fall|Adventure|PC,PS4,Switch,Xbox One|87|A cat comes home to a dying mining town.",
"Oxenfree|2016|Night School Studio|Adventure|PC,PS4,Switch,Xbox One|80|Teenagers, a radio, and a very bad island.",
"Her Story|2015|Sam Barlow|Mystery,Puzzle|PC,Mobile|91|Search a police database and assemble the truth yourself.",
"Immortality|2022|Sam Barlow|Mystery,Adventure|PC,Xbox Series,Mobile|85|Three unreleased films and something hiding between frames.",
"Norco|2022|Geography of Robots|Adventure,Point and Click|PC,PS5,Switch|85|Southern Louisiana refineries as southern gothic sci-fi.",
"Slay the Princess|2023|Black Tabby Games|Visual Novel,Horror|PC,PS5,Switch|85|A voice tells you to kill her. It gets complicated.",
"AI: The Somnium Files|2019|Spike Chunsoft|Visual Novel,Mystery|PC,PS4,Switch|82|Dream detective work, and one very rude AI eyeball.",
"Nine Hours, Nine Persons, Nine Doors|2009|Spike Chunsoft|Visual Novel,Puzzle|DS,PC,Switch|85|Escape rooms and a twist that needs two screens.",
"Danganronpa 2: Goodbye Despair|2012|Spike Chunsoft|Visual Novel,Adventure|PSP,Vita,PC,Switch|84|A tropical island, and the strongest cast of the trilogy.",
"The Longest Journey|1999|Funcom|Point and Click,Adventure|PC|91|April Ryan, two worlds, and enormous amounts of dialogue.",
"Broken Sword: Shadow of the Templars|1996|Revolution Software|Point and Click,Adventure|PC,PS1,Switch|89|Templars, Paris, and a goat that ruined childhoods.",
"Blue Prince|2025|Dogubomb|Puzzle,Roguelike|PC,PS5,Xbox Series|91|Draft rooms into a mansion that never repeats.",
"Lorelei and the Laser Eyes|2024|Simogo|Puzzle,Mystery|PC,Switch,PS5|87|A monochrome hotel of interlocking puzzles.",
"The Case of the Golden Idol|2022|Color Gray Games|Puzzle,Mystery|PC,PS5,Switch|84|Deduce eighteen deaths from grotesque little scenes.",
"World of Goo|2008|2D Boy|Puzzle|PC,Wii,Switch,Mobile|94|Build bridges out of living blobs.",
"Antichamber|2013|Alexander Bruce|Puzzle|PC|82|Non-Euclidean spaces that rewrite themselves behind you.",
"Viewfinder|2023|Sad Owl Studios|Puzzle|PC,PS5|82|Place a photograph into the world and walk into it.",
"Maniac Mansion|1987|Lucasfilm Games|Point and Click,Adventure|PC,NES|87|The first SCUMM game, and you can microwave a hamster.",
"Sam & Max Hit the Road|1993|LucasArts|Point and Click,Adventure|PC,Mac|90|A dog and a rabbit on the worst road trip.",
"Indiana Jones and the Fate of Atlantis|1992|LucasArts|Point and Click,Adventure|PC,Mac|91|Three routes through the same story. Better than most of the films.",
"The 7th Guest|1993|Trilobyte|Puzzle,Horror|PC,Mac,Switch|82|Full motion video in a haunted house, and it sold CD drives.",
"Command & Conquer|1995|Westwood Studios|RTS|PC,PS1|94|The RTS that took the genre mainstream.",
"Command & Conquer: Generals|2003|EA Pacific|RTS|PC,Mac|84|Three very asymmetric armies and endless mods.",
"Dune II|1992|Westwood Studios|RTS|PC,Genesis|87|Base, harvest, attack. Every RTS descends from this.",
"Warcraft II: Tides of Darkness|1995|Blizzard Entertainment|RTS|PC,Mac|92|Naval units, fog of war, and the world that became WoW.",
"Age of Empires|1997|Ensemble Studios|RTS|PC|83|Stone Age to Iron Age, with priests converting everything.",
"Age of Empires III|2005|Ensemble Studios|RTS|PC|81|Home cities and the prettiest cannons of the era.",
"Company of Heroes|2006|Relic Entertainment|RTS|PC|93|Cover, suppression, and the best RTS destruction ever made.",
"Warhammer 40,000: Dawn of War|2004|Relic Entertainment|RTS|PC|86|Squad-based, brutal, and completely on-brand.",
"Homeworld|1999|Relic Entertainment|RTS|PC,Mac|93|Full 3D fleet command and a genuinely moving story.",
"Supreme Commander|2007|Gas Powered Games|RTS|PC,Xbox 360|86|Zoom out until your armies are icons on a map.",
"Total Annihilation|1997|Cavedog Entertainment|RTS|PC|86|Physical projectiles and infinite build queues in 1997.",
"Northgard|2018|Shiro Games|RTS,Strategy|PC,PS4,Switch,Xbox One|79|Viking settlement building with harsh winters.",
"Europa Universalis IV|2013|Paradox Development Studio|Strategy,Simulation|PC,Mac|87|Four hundred years of history, and a thousand hours to learn it.",
"Hearts of Iron IV|2016|Paradox Development Studio|Strategy,Simulation|PC,Mac|83|The Second World War as a production spreadsheet.",
"Victoria 3|2022|Paradox Development Studio|Strategy,Simulation|PC,Mac|78|Nineteenth century economics as the whole game.",
"Crusader Kings II|2012|Paradox Development Studio|Strategy,Simulation|PC,Mac|82|Where the murderous family soap opera began.",
"Civilization IV|2005|Firaxis Games|Strategy,Turn-Based|PC,Mac|94|Religion, great people, and Baba Yetu.",
"Civilization VII|2025|Firaxis Games|Strategy,Turn-Based|PC,PS5,Switch,Xbox Series|80|Three ages, swapped civs, and a lot of arguing.",
"Sid Meier's Alpha Centauri|1999|Firaxis Games|Strategy,Turn-Based|PC,Mac|92|Civilization in space, with the best writing Meier ever shipped.",
"Sid Meier's Pirates!|1987|MicroProse|Action,Simulation|PC,Xbox,Mobile|88|Sail, trade, duel, dance with the governor's daughter.",
"Frostpunk|2018|11 bit studios|City Builder,Survival|PC,PS4,Switch,Xbox One|84|Keep the generator burning. Decide who freezes.",
"Frostpunk 2|2024|11 bit studios|City Builder,Survival|PC,PS5,Xbox Series|81|Bigger, colder, and now the politics fight back.",
"Anno 1800|2019|Ubisoft Mainz|City Builder,Simulation|PC,Xbox Series,PS5|81|Industrial revolution supply chains, beautifully drawn.",
"SimCity 4|2003|Maxis|City Builder,Simulation|PC,Mac|84|The regional simulation people still mod today.",
"Cities: Skylines II|2023|Colossal Order|City Builder,Simulation|PC,PS5,Xbox Series|73|More simulation than the first, and it ran like treacle.",
"OpenTTD|2004|OpenTTD Team|Simulation,Management|PC,Mac|85|Transport Tycoon, rebuilt and improved forever by volunteers.",
"Planet Coaster|2016|Frontier Developments|Management,Simulation|PC,PS5,Xbox Series|84|The spiritual successor RollerCoaster Tycoon fans wanted.",
"Planet Zoo|2019|Frontier Developments|Management,Simulation|PC|81|Animal welfare as a genuinely hard puzzle.",
"Jurassic World Evolution|2018|Frontier Developments|Management,Simulation|PC,PS4,Switch,Xbox One|71|Build the park. The fences will fail. Obviously.",
"Against the Storm|2023|Eremite Games|City Builder,Roguelike|PC,Xbox Series|86|A roguelite city builder, and it should not work this well.",
"Manor Lords|2024|Slavic Magic|City Builder,Strategy|PC,Xbox Series|83|One developer building a medieval village simulation.",
"Darkest Dungeon|2016|Red Hook Studios|Roguelike,Tactics|PC,PS4,Switch,Xbox One|84|Stress, madness, and a narrator who enjoys your failures.",
"Darkest Dungeon II|2023|Red Hook Studios|Roguelike,Tactics|PC,PS5,Switch|81|A road trip instead of a dungeon, and relationships to manage.",
"Battle Brothers|2017|Overhype Studios|Tactics,Strategy|PC,PS4,Switch,Xbox One|80|A mercenary company with no plot armour whatsoever.",
"Invisible, Inc.|2015|Klei Entertainment|Tactics,Stealth|PC,PS4,Switch|82|Turn-based corporate espionage with perfect information.",
"Desperados III|2020|Mimimi Games|Tactics,Stealth|PC,PS4,Xbox One|85|Real-time tactics in a western, with showdown mode.",
"Commandos 2: Men of Courage|2001|Pyro Studios|Tactics,Stealth|PC|86|Six specialists, one bunker, no room for error.",
"Mario + Rabbids Kingdom Battle|2017|Ubisoft Milan|Tactics,Strategy|Switch|85|XCOM with Mario. It should be terrible and it is superb.",
"Tactical Breach Wizards|2024|Suspicious Developments|Tactics|PC|86|Throw a policeman out of a window with magic. Undo freely.",
"Mount & Blade: Warband|2010|TaleWorlds Entertainment|Action RPG,Strategy|PC,PS4,Switch,Xbox One|78|Raise an army from nothing and take a castle.",
"Mount & Blade II: Bannerlord|2020|TaleWorlds Entertainment|Action RPG,Strategy|PC,PS5,Xbox Series|80|Bigger sieges, deeper economy, same glorious jank.",
"Plants vs. Zombies|2009|PopCap Games|Tower Defence,Strategy|PC,Mobile,PS3,Switch|88|Sunflowers, peashooters, and a song about brains.",
"Bloons TD 6|2018|Ninja Kiwi|Tower Defence,Strategy|PC,Mobile,Switch|82|Monkeys popping balloons, tuned to an absurd depth.",
"Kingdom Rush|2011|Ironhide Game Studio|Tower Defence,Strategy|Mobile,PC,Switch|86|The mobile tower defence everything else copied.",
"Brawl Stars|2018|Supercell|Shooter,Mobile|Mobile|81|Three-minute top-down brawls, endlessly tuned.",
"Coin Master|2015|Moon Active|Mobile,Simulation|Mobile|60|A slot machine wearing a village builder.",
"Galaga|1981|Namco|Arcade,Shoot 'em up|Arcade,NES,Switch|87|Formation attacks, and getting your fighter back doubled.",
"Asteroids|1979|Atari|Arcade,Shoot 'em up|Arcade,Atari 2600|88|Vector rocks, thrust, and hyperspace.",
"Ms. Pac-Man|1982|General Computer Corporation|Arcade,Maze|Arcade,Multi|88|Four mazes and smarter ghosts. Better than the original.",
"Pong|1972|Atari|Arcade,Sports|Arcade,Multi|80|Two paddles and the start of the entire industry.",
"R-Type|1987|Irem|Shoot 'em up|Arcade,PC Engine,Switch|85|The Force pod, and bosses the size of the screen.",
"SOMA|2015|Frictional Games|Horror,Adventure|PC,PS4,Switch,Xbox One|84|An underwater facility, and questions about what you are.",
"Signalis|2022|rose-engine|Horror,Puzzle|PC,PS5,Switch,Xbox Series|82|Survival horror as cold, beautiful science fiction.",
"Castle Crashers|2008|The Behemoth|Beat 'em up,Co-op|Xbox 360,PC,PS4,Switch|82|Four-player hack and slash with a deer that helps.",
"Tekken 7|2015|Bandai Namco Studios|Fighting|Arcade,PC,PS4,Xbox One|82|Rage arts, and a decade of tournament play.",
"Soulcalibur VI|2018|Bandai Namco Studios|Fighting|PC,PS4,Xbox One|84|Weapon-based fighting with a superb create-a-character.",
"Guitar Hero|2005|Harmonix|Rhythm|PS2|91|Five buttons and the illusion of being a rock star.",
"Need for Speed: Underground 2|2004|EA Black Box|Racing,Open World|PS2,Xbox,GameCube,PC|82|Neon, body kits, and the peak of car culture racing."
]);
