/* Postgame - game catalogue, part 13
   Harvested from Steam. Rows carry two extra fields: the Steam app id
   (for the 600x900 capsule) and the percentage of Steam reviews that
   are positive. */
window.GAME_ROWS = (window.GAME_ROWS || []).concat([
"Getting Over It with Bennett Foddy|2017|Bennett Foddy|Horror,Platformer,Adventure|PC,Mac,Linux||A game I made for a certain kind of person. To hurt them.|240720|82",
"Layers of Fear (2016)|2016|Bloober Team SA|Horror,Adventure,Puzzle|PC,Mac,Linux|73|A first-person psychological horror with a strong emphasis on atmosphere and storytelling..|391720|89",
"The Scroll of Taiwu : Beyond The Dome|2026|ConchShip Games|RPG,Sandbox,Open World|PC||The Scroll of Taiwu is an indie game themed around Chinese mythology and wuxia. Players assume.|838350|70",
"This War of Mine|2014|11 bit studios|Survival,Strategy,Simulation|PC,Linux|83|In This War Of Mine you do not play as an elite soldier, rather a group of civilians trying to.|282070|93",
"Chained Together|2024|Anegar Games|Co-op,Adventure,Platformer|PC||Climb up from the depths of Hell. Scale various worlds solo or chained together with your.|2567870|91",
"Goat Simulator|2014|Coffee Stain Studios|Simulation,Open World,Sandbox|PC,Mac,Linux|62|Goat Simulator is the latest in high-tech Goat Simulation technology.|265930|91",
"Black Mesa|2020|Crowbar Collective|FPS,Action,Shooter|PC,Linux|84|Relive Half-Life.|362890|95",
"Friday the 13th: The Game|2017|IllFonic|Horror,Survival,Co-op|PC|61|Jason is back! Jason Voorhees is unleashed and stalking the grounds of Camp Crystal Lake! Take.|438740|80",
"Remnant: From the Ashes|2019|Gunfire Games|Souls-like,Action,Co-op|PC|78|The world has been thrown into chaos by an ancient evil from another dimension. As one of the.|617290|85",
"Fallout Shelter|2017|Bethesda Game Studios|Survival,Management,Simulation|PC|63|Fallout Shelter puts you in control of a state-of-the-art underground Vault from Vault-Tec..|588430|88",
"Escape the Backrooms|2025|Fancy Games|Horror,Co-op,Exploration|PC||Escape the Backrooms is a 1-4 player co-op horror exploration game. Traverse 30+ eerie.|1943950|91",
"Hitman: Absolution|2012|Io-Interactive A/S|Stealth,Action,TPS|PC|79|The original assassin is back! Betrayed by the Agency and hunted by the police, Agent 47 finds.|203140|93",
"Conqueror's Blade|2019|Booming Tech|Tactical,Strategy,Action|PC||Master the art of siege tactics in Conqueror's Blade, a tactical action MMO brought to you by.|905370|75",
"Phantasy Star Online 2 New Genesis|2020|SEGA|MMO,RPG,Action|PC||Phantasy Star Online 2 New Genesis is a free-to-play action MMO. Join players around the world.|1056640|70",
"Brotato|2023|Blobfish|Roguelike,Shoot 'em up,Survival|PC,Mac,Linux||Brotato is a top-down arena shooter roguelite where you play a potato wielding up to 6 weapons.|1942280|97",
"BattleBlock Theater|2014|The Behemoth|Co-op,Platformer,Action|PC,Mac|85|Welcome to BattleBlock Theater! You've got no where to go but up...on stage. Play single player.|238460|97",
"Fallout: A Post Nuclear Role Playing Game|2015|Interplay Inc.|RPG,Open World,Turn-Based|PC|89|You've just unearthed the classic post-apocalyptic role-playing game that revitalized the.|38400|94",
"Dungeon Defenders|2011|Chromatic Games|Co-op,Tower Defence,Strategy|PC|81|Create a hero from one of four classes to save Etheria in this 4-player coop Tower Defense.|65800|93",
"Sins of a Solar Empire: Rebellion|2012|Ironclad Games Corporation|Management,Co-op,Simulation|PC|82|Command a space-faring empire in Sins of a Solar Empire: Rebellion, the new stand-alone.|204880|93",
"Tree of Savior (English Ver.)|2016|IMCGAMES Co.,Ltd.|MMO,RPG,Adventure|PC||Tree of Savior(abbreviated as TOS thereafter) is an MMORPG in which you embark on a journey to.|372000|64",
"MORDHAU|2019|Triternion|Co-op,Action,Fighting|PC|81|MORDHAU is a multiplayer medieval slasher. Create your mercenary and fight in brutal battles.|629760|80",
"The Crew 2|2018|Ivory Tower|Racing,Open World,MMO|PC||Take on the American motorsports scene as you explore and dominate the land, air, and sea.|646910|77",
"Pacify|2019|Shawn Hitchcock|Horror,Co-op,Exploration|PC,Mac||An online co-op horror game where you pacify, weaken and capture supernatural creatures for PAH.|967050|87",
"ARK: Survival Ascended|2023|Studio Wildcard|Survival,Open World,Adventure|PC||ARK is reimagined from the ground-up into the next-generation of video game technology with.|2399830|59",
"Rec Room|2021|Rec Room|VR,Co-op,MMO|PC||Rec Room is the best place to build and play games together. Party up with friends from all.|471710|90",
"The Day Before|2023|FNTASTIC|TPS,Survival,Shooter|PC||The Day Before offers players a uniquely reimagined journey into post-apocalyptic open-world.|1372880|16",
"The Long Dark|2017|Hinterland Studio Inc.|Survival,Open World,Exploration|PC,Mac,Linux||THE LONG DARK is a thoughtful, exploration-survival experience that challenges solo players to.|305620|90",
"Titan Quest Anniversary Edition|2016|Iron Lore Entertainment|RPG,Hack and Slash,Action RPG|PC||For its 10 year anniversary, Titan Quest will shine in new splendour. This Anniversary Edition.|475150|91",
"Need For Speed: Hot Pursuit|2010|Criterion Games|Racing,Sports,Open World|PC|85|Need for Speed Hot Pursuit launches you into a new open-world landscape behind the wheel of the.|47870|83",
"Soundpad|2017|Leppsoft|Rhythm|PC||Play sounds in voice chats in high digital quality. Add sounds or music to your microphone.|629520|96",
"Quake Live|2014|id Software|FPS,Action,Shooter|PC||Experience the most exciting and fast-paced FPS gameplay while competing with players from.|282440|87",
"The Outlast Trials|2024|Red Barrels|Horror,Co-op,Stealth|PC||Red Barrels invites you to experience mind-numbing terror, this time with friends. Whether you.|1304930|93",
"Metin2|2017|WEBZEN Inc.|MMO,Action RPG,Hack and Slash|PC||Become a part of the legendary oriental action MMO - now also on Steam! Put your skill to the.|550900|70",
"Assassin's Creed 2|2010|Ubisoft Montreal|Action,Open World,Stealth|PC|86|An epic story of family, vengeance and conspiracy set in the pristine, yet brutal, backdrop of.|33230|89",
"Who's Your Daddy?!|2016|Evil Tortilla Games|Simulation,Co-op,Strategy|PC,Mac||Who's Your Daddy is a casual multiplayer game featuring a clueless father attempting to prevent.|427730|80",
"DEVOUR|2021|Straight Back Games|Horror,Co-op,Survival|PC,Mac||DEVOUR is a co-op horror survival game for 1-4 players. Stop possessed cultists before they.|1274570|91",
"Tale of Immortal|2023|鬼谷工作室|Management,Simulation,Sandbox|PC||Tale of Immortal is an open-world sandbox based on Chinese mythology and cultivation. You will.|1468810|53",
"PAYDAY 3|2023|Starbreeze Studios|Co-op,Action,FPS|PC|66|PAYDAY 3 is the ultimate co-op FPS crime fantasy. Choose between stealth or loud playstyles.|1272080|43",
"Magic Duels|2015|Stainless Games Ltd.|Card Game,Strategy,Co-op|PC||MORE CARDS. MORE STRATEGY. BIGGER STORY. Collect 1,300+ earnable cards, battle in 60+.|316010|71",
"Teardown|2022|Tuxedo Labs|Sandbox,Open World,Simulation|PC|80|Prepare the perfect heist in a fully destructible, simulated voxel world. Tear down walls with.|1167630|96",
"TrackMania Nations Forever|2008|Nadeo|Racing,Arcade,Simulation|PC||A free game in the truest sense of the word, TrackMania Nations Forever lets you drive at.|11020|90",
"Bully: Scholarship Edition|2008|Rockstar New England|Open World,Action,Adventure|PC|72|Bully tells the story of mischievous 15-year-old Jimmy Hopkins as he goes through the hilarity.|12200|85",
"Sniper Elite 3|2014|Rebellion|Action,Stealth,Co-op|PC||Sniper Elite 3 is a tactical third-person shooter that combines stealth, gameplay choice and.|238090|82",
"GunZ 2: The Second Duel|2014|Masangsoft|Action,TPS,Hack and Slash|PC||GunZ 2: the Second Duel is a free-to-play 3D TPS and is the most fast-paced tough action.||66",
"Microsoft Flight Simulator (2020) 40th Anniversary Edition|2020|Asobo Studio|Simulation,Open World,VR|PC|91|From gliders and helicopters to wide-body jets, fly highly detailed and accurate aircraft in.|1250410|79",
"They Are Billions|2019|Numantian Games|Colony Sim,Strategy,Survival|PC|77|They Are Billions is a Steampunk strategy game set on a post-apocalyptic planet. Build and.|644930|85",
"The Escapists 2|2017|Team17|Strategy,Co-op,Simulation|PC,Mac,Linux|75|Craft, Steal, Brawl and Escape! It's time to bust out of the toughest prisons in the world as.|641990|91",
"Bless Unleashed|2021|VALOFE|RPG,MMO,Open World|PC||Bless Unleashed is an open-world online game that can be enjoyed with your friends and.|1254120|53",
"Insurgency|2014|New World Interactive|FPS,Tactical,Shooter|PC,Mac,Linux|74|Take to the streets for intense close quarters combat, where a team's survival depends upon.|222880|92",
"Orcs Must Die! 2|2012|Robot Entertainment|Tower Defence,Co-op,Action|PC|83|You've tossed, burned and sliced them by the thousands - now orcs must die more than ever.|201790|93",
"Football Manager 2022|2021|Sports Interactive|Sports,Management,Simulation|PC,Mac|85|The closest thing to real football management. FM22 brings new, progressive ways to find your.|1569040|93",
"America's Army: Proving Grounds|2013|U.S. Army|FPS,Action,Shooter|PC||America's Army: Proving Grounds is the official game of the U.S. Army and part of the highly.||79",
"Supermarket Simulator|2025|Nokta Games|Simulation,Management,Immersive Sim|PC,Mac||Run your own supermarket! Stock shelves, set your prices, take payments, hire staff, expand.|2670630|94",
"F1 2015|2015|Codemasters|Racing,Sports,Simulation|PC,Linux|61|Race like a champion in F1 2015 A stunning new game engine and all-new 'broadcast.|286570|60",
"Farming Simulator 19|2018|Giants Software|Simulation,Farming,Racing|PC,Mac|73|The best-selling franchise takes a giant leap forward with a complete overhaul of the graphics.|787860|94",
"SpeedRunners|2016|DoubleDutch Games|Racing,Platformer,Action|PC,Mac,Linux|84|Cut-throat multiplayer running game that pits 4 players against each other, locally and/or.|207140|94",
"Golf With Your Friends|2020|Blacklight Interactive|Sports,Co-op,Simulation|PC,Mac,Linux||Why have friends if not to play Golf... With Your Friends! Nothing is out of bounds as you take.|431240|88",
"Toribash|2014|Nabi Studios|Fighting,Action,Strategy|PC,Mac,Linux||Toribash is an innovative free-to-play online turn-based fighting game where you're able to.|248570|88",
"Batman: Arkham Origins|2013|WB Games Montreal|Action,Open World,Adventure|PC|74|As of December 4, 2016, the online services portion of Batman: Arkham Origins has been retired..|209000|89",
"Subnautica: Below Zero|2021|Unknown Worlds Entertainment|Survival,Open World,Horror|PC,Mac||Dive into a freezing underwater adventure on an alien planet. Below Zero is set two years after.|848450|91",
"S.K.I.L.L. - Special Force 2 (Shooter)|2015|Dragonfly GF Co., LTD|Shooter,Action,FPS|PC||S.K.I.L.L. - Special Force 2 is a fast-paced, action-packed FPS shooter based on the Unreal.||71",
"SPORE|2008|Maxis|Open World,Sandbox,Colony Sim|PC|84|Be the architect of your own universe with Spore, an exciting single-player adventure. From.|17390|92",
"Argo|2017|Bohemia Interactive|Shooter,FPS,Action|PC||Jump straight into combat in this official standalone FREE total conversion of Arma 3. Argo is.|530700|51",
"Gunfire Reborn|2021|Gunfire Reborn Studio|Roguelike,FPS,Co-op|PC||Gunfire Reborn is a level-based adventure game featuring FPS, Roguelite and RPG. Players can.|1217060|93",
"Farming Simulator 22|2021|Giants Software|Simulation,Farming,Co-op|PC,Mac||Create your farm and let the good times grow! Harvest crops, tend to animals, manage.|1248130|92",
"Party Jousting|2016|vikingfabian|Sports|PC||A one-button party game for 2-16 players, sharing a keyboard or controller.|437900|92",
"CarX Drift Racing Online|2017|CarX Technologies, LLC|Racing,Simulation,MMO|PC||CarX Drift Racing Online is your chance to immerse yourself in the real world of drifting. Get.|635260|95",
"Just Cause 2: Multiplayer Mod|2013|Avalanche Studios|Open World,Action,TPS|PC||JC2-MP is a project to bring multiplayer to Just Cause 2 in all of its magnificent glory..|259080|92",
"Homefront|2011|Kaos Studios|Action,FPS,Shooter|PC|70|The Rock Map Pack is Now Available! Join the Resistance, stand united and fight for freedom.|55100|61",
"Soul Dossier|2021|GKD GAME|Horror,Action,Survival|PC||Soul Dossier is a multiplayer game based on Oriental culture (5vS1). The game is based on a.|1520470|82",
"Mirror|2018|KAGAMI WORKS|Visual Novel,RPG,Adventure|PC,Mac||This is a game that combines match-3, GALGAME elements and beauties. If you want to learn more.|644560|97",
"Football Manager 2021|2020|Sports Interactive|Sports,Simulation,Management|PC,Mac||New additions and game upgrades deliver added levels of depth, drama and football authenticity..|1263850|93",
"ARK: The Survival Of The Fittest|2017|Studio Wildcard|Survival,Open World,Action|PC||ARK: The Survival of the Fittest is a prototype spin-off of ARK: Survival Evolved, pitting up.||66",
"Muse Dash|2019|peropero|Rhythm,Action,Arcade|PC,Mac||Paradise of parkour & rhythm game ★★★ - Muse Dash!!|774171|90",
"The I of the Dragon|2015|Primal|RPG,Open World,Simulation|PC,Mac,Linux||The world of Nimoa is as beautiful as the morning dew, but only at first glance. Under the.|279720|68",
"World War 3|2022|New Generation Games|FPS,Co-op,Tactical|PC||World War 3 is a free-to-play tactical online multiplayer FPS where the world is your.|674020|54",
"Resident Evil 3|2020|CAPCOM Co., Ltd.|Action,Horror,Co-op|PC|77|Jill Valentine is one of the last remaining people in Raccoon City to witness the atrocities.|952060|82",
"Football Manager 2023|2022|Sports Interactive|Simulation,Sports,Management|PC,Mac||Build your dream squad, outsmart your rivals and experience the thrill of big European nights.|1904540|90",
"Darksiders II Deathinitive Edition|2015|Gunfire Games|Action,Hack and Slash,Adventure|PC||The ultimate DARKSIDERS II experience! 1080p native resolution. Reworked and tuned game.|388410|79",
"KARDS - The WW2 Card Game|2020|1939 Games|Card Game,Strategy,Turn-Based|PC|80|KARDS, The World War II Card Game, combines traditional CCG gameplay with innovative mechanics.|544810|74",
"Quake Champions|2022|id Software|Hero Shooter,FPS,Shooter|PC||Step into the Arena. Compete against players from around the world in this fast-paced shooter.|611500|74",
"Half-Life: Opposing Force|1999|Gearbox Software|FPS,Action,Shooter|PC,Mac,Linux||Return to the Black Mesa Research Facility as one of the military specialists assigned to.|50|95",
"Krunker|2021|FRVR|Shooter,FPS,Action|PC,Mac||An easy to get into fully moddable First Person Shooter with advanced movement mechanics. Fully.|1408720|79",
"DiRT Rally|2015|Codemasters|Racing,Simulation,VR|PC,Mac,Linux|86|DiRT Rally is the most authentic and thrilling rally game ever made, road-tested over 80.|310560|88",
"Sniper Elite 5|2022|Rebellion|Stealth,Action,Co-op|PC|79|The award-winning series returns as Karl Fairburne fights to uncover Project Kraken in 1944.|1029690|83",
"Grand Theft Auto: Episodes from Liberty City|2010|Rockstar North / Toronto|Open World,Action,Adventure|PC||Grand Theft Auto: Episodes from Liberty City includes both The Lost and Damned and The Ballad.|12220|74",
"Back to Bed|2014|Bedtime Digital Games|Puzzle,Action,Adventure|PC,Mac,Linux||A surreal 3D puzzle game where you guide Bob the sleepwalker safely back to bed. Move objects.|308040|81",
"UNO|2017|Ubisoft Entertainment|Card Game,Strategy,Co-op|PC||UNO is the iconic card game reimagined with a large variety of gameplay and customization.|470220|72",
"BLOCKADE 3D|2014|Novalink|Shooter,FPS,Action|PC||BLOCKADE 3D! First Person Shooter in an editable procedural cubic world. A large arsenal of.|302830|59",
"Banished|2014|Shining Rock Software LLC|City Builder,Colony Sim,Strategy|PC|73|In this city-building strategy game, you control a group of exiled travelers who decide to.|242920|90",
"Dungeon Defenders II|2017|Chromatic Games|Co-op,Tower Defence,Survival|PC||Dungeon Defenders II is a cooperative Action Tower Defense game packed with roleplaying.|236110|77",
"Spellbreak|2020|Proletariat, Inc.|Battle Royale,Action,RPG|PC||Spellbreak is a multiplayer action-spellcasting game where you unleash your inner battlemage..|1399780|87",
"Sniper Elite 4|2017|Rebellion|Action,Shooter,Stealth|PC|78|Discover unrivalled sniping freedom in the largest and most advanced World War 2 shooter ever.|312660|91",
"Ace Combat 7: Skies Unknown|2019|Bandai Namco Studios Inc.|Shooter,Arcade,Action|PC|78|Become an ace pilot and soar through photorealistic skies with full 360 degree movement; down.|502500|88",
"Dead Bits|2014|Microblast Games|Action,FPS,Shooter|PC,Mac||Quilly was abducted by aliens, now, he has to fight for his freedom! Destroy cube aliens with.||60",
"Half-Life: Source|2004|Valve|FPS,Action,Shooter|PC,Mac,Linux||Winner of over 50 Game of the Year awards, Half-Life set new standards for action games when it.|280|69",
"Ironsight|2019|WipleGames Inc.,|Action,FPS,Shooter|PC||Online FPS game, near future background, Resource Warfare between Military Forces and PMC. More.|783770|72",
"Star Conflict|2013|Star Gem Inc.|Co-op,Open World,MMO|PC,Mac,Linux|75|Star Conflict is an action-packed, massively multiplayer space simulation game that puts.|212070|73",
"Serious Sam 3: BFE|2011|Croteam|FPS,Action,Co-op|PC,Mac,Linux|72|Serious Sam 3: BFE is a prequel to the original indie fast action FPS and Game of the Year.|41070|88",
"Spec Ops: The Line|2012|YAGER|Adventure,TPS,Action|PC,Mac,Linux|76|A Third-Person modern military Shooter designed to challenge players' morality by putting them.|50300|93"
]);
