/* Postgame - game catalogue, part 11
   Harvested from Steam. Rows carry two extra fields: the Steam app id
   (for the 600x900 capsule) and the percentage of Steam reviews that
   are positive. */
window.GAME_ROWS = (window.GAME_ROWS || []).concat([
"Lego Star Wars - The Complete Saga|2009|Traveller's Tales|Co-op,Adventure,Action|PC|77|Kick Some Brick in I through VI! Play through all six Star Wars movies in one videogame! Adding.|32440|",
"Lego Star Wars: The Force Awakens|2016|Traveller's Tales|Adventure,Action,Co-op|PC||The No. 1 LEGO videogame franchise triumphantly returns with a fun-filled, humorous journey.|438640|",
"Lego Star Wars III - The Clone Wars|2011|Traveller's Tales|Action,Adventure,Co-op|PC|76|LEGO Star Wars III: The Clone Wars will allow fans to explore endlessly and laugh their way.|32510|",
"Lego Batman 3: Beyond Gotham|2014|TT Games Ltd|Adventure,Open World,Action|PC||The Caped Crusader joins forces with the super heroes of the DC Comics universe and blasts off.|313690|",
"Lego Batman: The Videogame|2008|Traveller's Tales|Action,Adventure,Co-op|PC|80|When all the villains in Arkham Asylum team up and break loose, only the dynamic duo is bold.|21000|",
"Lego Batman 2: DC Super Heroes|2012|TT Games|Action,Adventure,Open World|PC|81|Legends Unite! The Dynamic Duo of Batman and Robin join other famous super heroes from the DC.|213330|",
"Lego Harry Potter Collection|2024|TT Games|Action,Adventure,Platformer|PC||The LEGO Harry Potter: Collection brings LEGO Harry Potter: Years 1-4 and LEGO Harry.|2950340|",
"Lego Harry Potter: Years 1-4|2010|TT Games|Adventure,Co-op,Action|PC|79|Build the adventure from Privet Drive to the Triwizard Tournament and experience the magic of.|21130|",
"Lego Harry Potter: Years 5-7|2012|Traveller's Tales|Adventure,Co-op,Action|PC|80|LEGO Harry Potter: Years 5-7 takes players through Harry Potter's heroic adventures in the.|204120|",
"Lego Marvel Super Heroes|2013|Traveller's Tales|Open World,Co-op,Adventure|PC|78|LEGO Marvel Super Heroes features an original story crossing the entire Marvel Universe..|249130|",
"Lego Marvel Super Heroes 2|2017|TT Games|Open World,Co-op,Action|PC||It's about TIME! Join your favorite Super Heroes and Super Villains from different eras and.|647830|",
"Lego Marvel's Avengers|2016|Traveller's Tales|Open World,Adventure,Action|PC||Avengers Assemble! The best-selling LEGO MARVEL videogame franchise returns with a new.|405310|",
"Lego Indiana Jones 2: The Adventure Continues|2010|Traveller's Tales|Adventure,Co-op,Action|PC|66|LEGO Indy is back in his biggest adventure yet. Battle through all four movies, including.|32450|",
"Lego Indiana Jones: The Original Adventures|2009|Traveller's Tales|Adventure,Action,Co-op|PC|78|Build, Battle and Brawl your way out of trouble! Play through all three classic Indiana Jones.|32330|",
"Lego City Undercover|2017|Traveller's Tales|Open World,Action,Co-op|PC|80|Join the Chase! In LEGO CITY Undercover, play as Chase McCain, a police officer who's been.|578330|",
"Lego Jurassic World|2015|TT Games Ltd|Adventure,Open World,Action|PC|72|Following the epic storylines of Jurassic Park, The Lost World: Jurassic Park and Jurassic Park.|352400|",
"The Lego Movie - Videogame|2014|TT Fusion|Adventure,Action,Co-op|PC||Join Emmet and an unlikely group of resistance fighters in their heroic quest to thwart Lord.|267530|",
"The Lego Movie 2 Videogame|2019|TT Games|Adventure,Sandbox,Open World|PC||Bricksburg is in ruins and Emmet's friends have been taken! Team up with Emmet and a host of.|881320|",
"The Lego Ninjago Movie Video Game|2017|Traveller's Tales|Action,Co-op,Open World|PC||Find your inner ninja with the all-new LEGO NINJAGO Movie Video Game! Play as your favorite.|640590|",
"Lego Worlds|2017|TT Games|Open World,Sandbox,Adventure|PC||Experience a galaxy of Worlds made entirely from LEGO bricks. EXPLORE gigantic landscapes.|332310|",
"Lego Bricktales|2022|ClockStone|Puzzle,Adventure,Sandbox|PC,Mac,Linux|75|In this puzzle-adventure, use an intuitive brick-by-brick building mechanic to solve puzzles.|1898290|",
"Lego Builder's Journey|2021|Light Brick Studio|Puzzle,Adventure,Point and Click|PC|79|LEGO Builder's Journey is an atmospheric, geometric puzzle game that asks us to sometimes.|1544360|",
"Lego Brawls|2022|Red Games Co.|Action,Platformer,Fighting|PC||Dream up the ultimate Minifigure brawlers and bash your way through all of your favorite LEGO.|1731460|",
"Lego Horizon Adventures|2024|Guerrilla Games|Action,Adventure,Co-op|PC||Join machine hunter Aloy as she leads a colourful crew of heroes on a quest to save the world.|2428810|",
"Lego The Incredibles|2018|TT Games|Action,Adventure,Open World|PC||Experience the thrilling adventures of the Parr family as they conquer crime and family life.|818320|",
"Lego DC Super-Villains|2018|TT Games|Action,Adventure,Open World|PC,Mac|76|It's good to be bad... Embark on an all-new DC/LEGO adventure by becoming the best villain the.|829110|",
"Lego The Hobbit|2014|Traveller's Tales|Adventure,Action,Co-op|PC||Reclaim the Lost Kingdom brick by brick! Join Bilbo Baggins, Gandalf, Thorin and his company of.|285160|",
"Lego The Lord of the Rings|2012|Traveller's Tales|Adventure,Co-op,Action|PC|80|Based on The Lord of the Rings motion picture trilogy, LEGO The Lord of the Rings follows the.|214510|",
"Lego Pirates of the Caribbean: The Video Game|2014|Traveller's Tales|Adventure,Action,Co-op|PC||LEGO Pirates of the Caribbean: The Video Game is an action adventure game that brings the.|311770|",
"Lego Voyagers|2025|Light Brick Studio|Adventure|PC||From the makers of LEGO Builder's Journey comes a new 2-player co-op adventure about.||",
"Lego Party!|2025|SMG Studio|Action|PC||LEGO Party! is a 4-player party game that's built different! Compete against your friends in.||",
"New World: Aeternum|2021|Amazon Game Studios|Open World,MMO,RPG|PC||Experience a thrilling action RPG set on the supernatural island of Aeternum. Forge your.|1063730|69",
"Grand Theft Auto V Legacy|2015|Rockstar North|Open World,Action,Shooter|PC|96|Grand Theft Auto V for PC offers players the option to explore the award-winning world of Los.|271590|87",
"Unturned|2017|Smartly Dressed Games|Survival,Open World,Co-op|PC,Mac,Linux||Unturned is an open-world zombie survival sandbox game. As one of the few not yet turned, you.|304930|91",
"War Thunder|2013|Gaijin Entertainment|Simulation,VR,MMO|PC,Mac,Linux|81|War Thunder is the most comprehensive free-to-play, cross-platform, MMO military game dedicated.|236390|64",
"Brawlhalla|2017|Blue Mammoth Games|Fighting,Platformer,Co-op|PC,Mac||An epic platform fighter for up to 8 players online or local. Try casual free-for-alls, ranked.|291550|81",
"Garry's Mod|2006|Facepunch Studios|Sandbox,FPS,Simulation|PC,Mac,Linux||Garry's Mod is a physics sandbox. There aren't any predefined aims or goals. We give you the.|4000|97",
"World of Warships|2017|Wargaming Group Limited|Action,Co-op,Tactical|PC|81|Immerse yourself in thrilling naval battles and assemble an armada of over 800 ships from the.|552990|77",
"War Robots: Frontiers|2025|MY.GAMES|TPS,Action,Shooter|PC||Gear up for tactical mech action in War Robots: Frontiers, a free-to-play multiplayer mech.|1491000|64",
"Warface: Clutch|2014|MY.GAMES|FPS,Shooter,Action|PC||𝗪𝗮𝗿𝗳𝗮𝗰𝗲: 𝗖𝗹𝘂𝘁𝗰𝗵 𝗶𝘀 𝗮 𝗰𝗼𝗻𝘁𝗲𝗺𝗽𝗼𝗿𝗮𝗿𝘆 𝗠𝗠𝗢 𝗳𝗶𝗿𝘀𝘁 𝗽𝗲𝗿𝘀𝗼𝗻 𝘀𝗵𝗼𝗼𝘁𝗲𝗿 𝘄𝗶𝘁𝗵 𝗺𝗶𝗹𝗹𝗶𝗼𝗻𝘀 𝗼𝗳 𝗳𝗮𝗻𝘀 𝗮𝗿𝗼𝘂𝗻𝗱 𝘁𝗵𝗲.|291480|66",
"Half-Life 2: Lost Coast|2005|Valve|FPS,Action,Shooter|PC,Linux||Originally planned as a section of the Highway 17 chapter of Half-Life 2, Lost Coast is a.|340|89",
"Hogwarts Legacy|2023|Avalanche Software|Open World,Adventure,RPG|PC|83|Hogwarts Legacy is an immersive, open-world action RPG. Now you can take control of the action.|990080|90",
"VRChat|2017|VRChat Inc.|VR,MMO,Open World|PC||Join our growing community as you explore, play, and help craft the future of social VR. Create.|438100|76",
"Paladins|2018|Evil Mojo Games|Hero Shooter,FPS,Shooter|PC|83|Paladins is the ultimate fantasy team-based shooter experience, with over 50 customizable.|444090|85",
"NARAKA: BLADEPOINT|2021|24 Entertainment|Battle Royale,Action,MMO|PC||Dive into the legends of the Far East in NARAKA: BLADEPOINT; team up with friends in fast-paced.|1203220|70",
"Half-Life 2: Deathmatch|2004|Valve|Action,FPS,Shooter|PC,Linux||Fast multiplayer action set in the Half-Life 2 universe! HL2's physics adds a new dimension to.|320|91",
"Heroes & Generals|2016|TLM Partners|FPS,Shooter,Action|PC||Shoot, blow sh!t up, fly or bark orders in the ultimate Free-to-Play, large scale, multiplayer.|227940|68",
"Battlefield 2042|2021|DICE|FPS,Shooter,Action|PC||Battlefield 2042 is a first-person shooter that marks the return to the iconic all-out warfare.|1517290|47",
"Raft|2022|Redbeet Interactive|Survival,Co-op,Open World|PC||Raft throws you and your friends into an epic oceanic adventure! Alone or together, players.|648800|93",
"SMITE|2015|Titan Forge Games|MOBA,Action,Strategy|PC|83|Join 40+ million players in SMITE, the Battleground of the Gods! Wield Thor's hammer, turn your.|386360|79",
"World of Tanks Blitz|2016|Wargaming Group Limited|Shooter,Action,FPS|PC,Mac||Blow off steam and tank turrets in a free-to-play online 7v7 tank shooter! Drive hundreds of.|444200|79",
"Counter-Strike|2000|Valve|Action,FPS,Shooter|PC,Mac,Linux|88|Play the world's number 1 online action game. Engage in an incredibly realistic brand of.|10|97",
"Counter-Strike: Source|2004|Valve|Shooter,FPS,Action|PC,Linux|88|Counter-Strike: Source blends Counter-Strike's award-winning teamplay action with the advanced.|240|96",
"Schedule I|2025|TVGS|Simulation,Co-op,Open World|PC||From small-time dope pusher to kingpin - manufacture and distribute a range of drugs throughout.|3164500|98",
"Ring of Elysium|2019|Aurora Studio|Battle Royale,Shooter,Survival|PC||Escape an astonishing disaster in Ring of Elysium, a battle royale shooter developed by Aurora.|755790|74",
"Black Squad|2019|VALOFE|FPS,Shooter,Action|PC||Black Squad is a free-to-play military first-person-shooter. Players can master their skills.|550650|76",
"Don't Starve Together|2016|Klei Entertainment|Survival,Co-op,Open World|PC,Mac,Linux|83|Fight, Farm, Build and Explore Together in the standalone multiplayer expansion to the.|322330|95",
"Dying Light|2015|Techland|Horror,Co-op,Open World|PC,Mac,Linux|87|First-person action survival game set in a post-apocalyptic open world overrun by flesh-hungry.|239140|95",
"Counter-Strike: Condition Zero|2004|Valve|Action,FPS,Shooter|PC,Mac,Linux|65|With its extensive Tour of Duty campaign, a near-limitless number of skirmish modes, updates.|100|90",
"eFootball|2021|KONAMI|Sports,Simulation,Co-op|PC||Step up and experience the exhilarating soccer game that has now surpassed 1 billion downloads!.|1665460|48",
"Street Warriors Online|2016|Crazy Rocks Studios|Fighting,Action,Sports|PC||First, realistic PvP brawling game for up to 8 vs 8 players with original, dynamic combat.||58",
"Z1 Battle Royale|2018|Daybreak Game Company|Survival,MMO,Open World|PC|70|Z1 Battle Royale is a Free to Play, fast-paced, action arcade, competitive Battle Royale..|433850|56",
"Hunt: Showdown 1896|2019|Crytek|Open World,Tactical,FPS|PC|81|Hunt: Showdown 1896 is the brutally rewarding extraction shooter. Track twisted monsters and.|594650|73",
"CyberCorp|2025|Megame LLC|Shooter,Tactical,Co-op|PC||Brutal fast-paced isometric Co-op Loot Shooter in Cyberpunk world. Equipment-based combos..|1116170|83",
"Trove|2015|gamigo US Inc.|Open World,Sandbox,MMO|PC||Grab your friends, hone your blades, and set off for an epic procedurally generated adventure.|304050|80",
"Life is Strange 2|2018|DONTNOD Entertainment|Adventure,Point and Click,Mystery|PC,Mac,Linux||After a tragic incident, brothers Sean and Daniel Diaz run away from home. Fearing the police.|532210|86",
"R.E.P.O.|2025|semiwork|Horror,Co-op,Stealth|PC||An online co-op horror game with up to 6 players. Locate valuable, fully physics-based objects.|3241660|97",
"NBA 2K20|2019|Visual Concepts|Sports,Simulation,MMO|PC|74|NOTE: All multiplayer servers for NBA 2K20 will be shutdown as of 12/31/2021. After that time.|1089350|50",
"EA Sports FIFA 23|2022|EA Canada|Sports,Management,Simulation|PC||FIFA 23 brings The World's Game to the pitch, with HyperMotion2 Technology, men's and women's.|1811260|57",
"PlanetSide 2|2012|Rogue Planet Games|FPS,MMO,Shooter|PC|84|PlanetSide 2 is an all-out planetary war, where thousands of players battle as one across.|218230|81",
"No More Room in Hell|2013|No More Room in Hell Team|Survival,Horror,Co-op|PC,Linux||The chances of you surviving this all out war of society and the undead are slim to none..|224260|90",
"Robocraft|2017|Freejam|Action,Shooter,MMO|PC,Mac,Linux||Build insane, fully customisable robot battle vehicles that drive, hover, walk and fly in the.|301520|73",
"War Robots|2018|MY.GAMES|Shooter,TPS,Action|PC||War Robots is an online third-person 6v6 PvP shooter-we're talking dozens of combat robots.|767560|60",
"Deceit|2017|World Makers|Horror,Social Deduction,Shooter|PC||Test your instincts at trust and deception in an action-filled, multiplayer first-person.|466240|79",
"BeamNG.drive|2015|BeamNG|Simulation,Racing,Sandbox|PC||A dynamic soft-body physics vehicle simulator capable of doing just about anything.|284160|97",
"A Story About My Uncle|2014|Gone North Games|Adventure,Platformer,Puzzle|PC,Mac,Linux|73|A Story About My Uncle is a first person platforming adventure game about a boy who searches.|278360|92",
"Kathy Rain|2016|Clifftop Games|Point and Click,Adventure,Mystery|PC,Mac|77|Set in the '90s, Kathy Rain tells the story of a strong-willed journalism major who has to come.|370910|92",
"Deathmatch Classic|2001|Valve|Action,FPS,Shooter|PC,Mac,Linux||Enjoy fast-paced multiplayer gaming with Deathmatch Classic (a.k.a. DMC). Valve's tribute to.|40|83",
"Guacamelee! Super Turbo Championship Edition|2014|Drinkbox Studios|Platformer,Metroidvania,Beat 'em up|PC||The definitive version of the smash-hit Metroidvania-style action-platformer, Guacamelee! STCE.|275390|93",
"Content Warning|2024|Zorro|Co-op,Horror,Exploration|PC||Film your friends doing scary things to become SpöökTube famous! (strongly advised to not go.|2881650|95",
"Dirty Bomb|2015|Splash Damage|Hero Shooter,FPS,Shooter|PC|63|Work together or die alone! Fight to restore peace to London or tear it down for profit in the.|333930|81",
"Sea of Thieves: 2026 Edition|2020|Rare Ltd|Open World,Adventure,Co-op|PC||Sea of Thieves is a smash-hit pirate adventure game, offering the quintessential pirate.|1172620|89",
"SCP: Secret Laboratory|2017|Northwood Studios|Horror,Co-op,Shooter|PC||Deep within a secure underground facility, a sudden containment breach allows many of the.|700330|91",
"Dota Underlords|2019|Valve|Strategy,Auto Battler,Tactical|PC,Mac,Linux||Hire a crew and destroy your rivals in this new strategy battler set in the world of Dota..|1046930|82",
"EA Sports FC 24|2023|EA Canada|Sports,Simulation,Co-op|PC||EA SPORTS FC 24 welcomes you to The World's Game: the most true-to-football experience ever.|2195250|58",
"Chivalry: Medieval Warfare|2012|Torn Banner Studios|Action,Hack and Slash,Co-op|PC,Mac,Linux|79|Besiege castles and raid villages in Chivalry: Medieval Warfare, a fast-paced medieval first.|219640|83",
"Assetto Corsa|2014|Kunos Simulazioni|Racing,Simulation,VR|PC|85|Assetto Corsa v1.16 introduces the new Laguna Seca laser-scanned track, 7 new cars among which.|244210|93",
"MultiVersus|2022|Player First Games|Fighting,Co-op,Action|PC|75|MultiVersus is a free-to-play platform fighter that brings the depth of iconic WB stars to life.|1818750|76",
"Day of Defeat|2003|Valve|FPS,Shooter,Action|PC,Mac,Linux|79|Enlist in an intense brand of Axis vs. Allied teamplay set in the WWII European Theatre of.|30|90",
"Clicker Heroes|2015|Playsaurus|Simulation,Management,Strategy|PC,Mac||Click your way through hordes of monsters, earn gold, and recruit quirky heroes with powerful.|363970|90",
"theHunter Classic|2014|Expansive Worlds|Open World,Simulation,Shooter|PC||The most realistic hunting experience awaits. Explore 12 reserves and hunt 45 unique species.|253710|58",
"Evolve Stage 2|2015|Turtle Rock Studios|Action,Co-op,FPS|PC|77|Play Evolve for free with Evolve Stage 2! Evolve Stage 2 is a next-generation free multiplayer.|273350|70",
"Crab Game|2021|Dani|Horror,Battle Royale,Action|PC,Mac,Linux||Crab Game is a First-Person Multiplayer game where you play through several different minigames.|1782210|92",
"KurtzPel|2019|KOG|Action,Fighting,MMO|PC||KurtzPel is an anime-styled, action battle game from a third-person perspective. Players can.|844870|61",
"Blender|2015|Blender Foundation|Sandbox,Horror,Adventure|PC,Mac,Linux||Blender is the free and open source 3D creation suite. Free to use for everyone, for any.|365670|96",
"Life is Strange - Episode 1|2015|DONTNOD Entertainment|Adventure,Mystery,Point and Click|PC,Mac,Linux||Episode 1 now FREE! Life is Strange is an award-winning and critically acclaimed episodic.|319630|96",
"BattleBit Remastered|2023|SgtOkiDoki|FPS,Shooter,MMO|PC||BattleBit Remastered is a low-poly, massive multiplayer FPS, supporting 254 players per server..|671860|84",
"Company of Heroes 2|2013|Relic Entertainment|Strategy,RTS,Tactical|PC,Mac,Linux|80|Experience the ultimate WWII RTS platform with COH2 and its standalone expansions. This package.|231430|79",
"Realm Royale Reforged|2018|Heroic Leap Games|Battle Royale,Shooter,Survival|PC||Join 20+ million players and experience a new kind of battle royale in Realm Royale Reforged!.|813820|76",
"Total War: Warhammer II|2017|CREATIVE ASSEMBLY|Strategy,RTS,Action|PC,Mac,Linux|87|The forces of Lustria await your command. Choose your Legendary Lord, expand your armies, forge.|594570|92"
]);
