/* Postgame — game catalogue, part 8 of 10 */
window.GAME_ROWS = (window.GAME_ROWS || []).concat([
"Final Fantasy|1987|Square|JRPG,Turn-Based|NES,PS1,Mobile|80|The one that saved the company, and named itself for it.",
"Final Fantasy IV|1991|Square|JRPG,Turn-Based|SNES,DS,Mobile|88|The Active Time Battle system and a real cast.",
"Final Fantasy V|1992|Square|JRPG,Turn-Based|SNES,PS1,Mobile|85|The job system at its most flexible.",
"Final Fantasy VIII|1999|Square|JRPG,Turn-Based|PS1,PC,Switch|90|Junctioning, card games, and a very odd love story.",
"Final Fantasy XII|2006|Square Enix|JRPG,Action RPG|PS2,PS4,Switch,PC|92|Gambits let you program your party. Ivalice is superb.",
"Final Fantasy XIII|2009|Square Enix|JRPG,Turn-Based|PS3,Xbox 360,PC|83|Corridors, but a combat system worth the argument.",
"Final Fantasy XV|2016|Square Enix|Action RPG,Open World|PS4,PC,Xbox One|81|A road trip with four friends and a lot of camping.",
"Final Fantasy Tactics|1997|Square|Tactics,JRPG|PS1,PSP,Mobile|94|Political tragedy on an isometric grid.",
"Crisis Core: Final Fantasy VII|2007|Square Enix|Action RPG|PSP,PS5,Switch|83|Zack's story, and it lands harder than it should.",
"Kingdom Hearts|2002|Square Enix|Action RPG|PS2,PS4,PC|85|Disney and Final Fantasy, and somehow it worked.",
"Chrono Cross|1999|Square|JRPG,Turn-Based|PS1,PC,Switch|94|Forty playable characters and the best soundtrack Square made.",
"Xenogears|1998|Square|JRPG,Turn-Based|PS1|84|Mechs, philosophy, and a famously unfinished second disc.",
"Vagrant Story|2000|Square|Action RPG,Dungeon Crawler|PS1|92|Dense, difficult, and written like a stage play.",
"Parasite Eve|1998|Square|Action RPG,Horror|PS1|82|Cinematic horror RPG set in a very cold New York.",
"The World Ends with You|2007|Square Enix|Action RPG|DS,Switch,Mobile|88|Shibuya, two screens at once, and unbeatable style.",
"Octopath Traveler II|2023|Square Enix|JRPG,Turn-Based|PC,PS5,Switch|87|Everything the first did, sharpened.",
"Triangle Strategy|2022|Square Enix|Tactics,JRPG|Switch,PC|80|Salt, iron and trade routes decided by committee vote.",
"Live A Live|1994|Square|JRPG,Turn-Based|SNES,Switch,PC|81|Seven eras, seven genres, one very good twist.",
"Dragon Quest|1986|Chunsoft|JRPG,Turn-Based|NES,Switch,Mobile|78|The template every JRPG copied for a decade.",
"Dragon Quest III|1988|Chunsoft|JRPG,Turn-Based|NES,SNES,Switch|89|Build your own party, and that ending.",
"Dragon Quest V|1992|Chunsoft|JRPG,Turn-Based|SNES,DS,Mobile|90|A life story across three generations. Monster recruiting too.",
"Dragon Quest IX|2009|Level-5|JRPG,Turn-Based|DS|87|Built for local multiplayer, and Japan went feral for it.",
"Star Ocean: The Second Story|1998|tri-Ace|Action RPG|PS1,PSP,Switch|85|Real-time battles and dozens of endings.",
"Valkyrie Profile|1999|tri-Ace|Action RPG,Turn-Based|PS1,PSP|86|Norse myth, side-on dungeons, button-per-character combat.",
"Secret of Mana|1993|Square|Action RPG|SNES,Switch|89|Three-player action RPG with the ring menu.",
"Visions of Mana|2024|Ouka Studios|Action RPG|PC,PS5,Xbox Series|76|A bright, generous return for the series.",
"Tomb Raider|1996|Core Design|Action Adventure,Platformer|PS1,PC,Switch|91|Vast empty tombs and genuine loneliness.",
"Tomb Raider (2013)|2013|Crystal Dynamics|Action Adventure,TPS|PC,PS3,Xbox 360|86|A grittier Lara, and superb traversal.",
"Rise of the Tomb Raider|2015|Crystal Dynamics|Action Adventure,TPS|PC,PS4,Xbox One|86|Siberia, and the best tombs of the reboot trilogy.",
"Shadow of the Tomb Raider|2018|Eidos Montreal|Action Adventure,TPS|PC,PS4,Xbox One|75|The prettiest, and the most underwater.",
"Deus Ex: Mankind Divided|2016|Eidos Montreal|Immersive Sim,FPS|PC,PS4,Xbox One|84|Prague as a dense, layered playground.",
"Just Cause 2|2010|Avalanche Studios|Action,Open World|PC,PS3,Xbox 360|84|Grappling hook plus parachute equals physics comedy.",
"Just Cause 3|2015|Avalanche Studios|Action,Open World|PC,PS4,Xbox One|78|A wingsuit and an island of things to detonate.",
"Hitman (2016)|2016|IO Interactive|Stealth,Action|PC,PS4,Xbox One|84|Episodic sandboxes and the reinvention that stuck.",
"Hitman 2|2018|IO Interactive|Stealth,Action|PC,PS4,Xbox One|82|Miami and Mumbai, and the crowds got smarter.",
"Persona 3|2006|Atlus|JRPG,Turn-Based|PS2,PSP|86|School by day, the Dark Hour by night, death throughout.",
"Shin Megami Tensei III: Nocturne|2003|Atlus|JRPG,Turn-Based|PS2,PC,Switch|82|Tokyo ends, demons negotiate, the press turn punishes.",
"Shin Megami Tensei IV|2013|Atlus|JRPG,Turn-Based|3DS|85|Samurai in a buried Tokyo, and it is merciless early.",
"Odin Sphere Leifthrasir|2016|Vanillaware|Action RPG|PS4,PS3,Vita|85|Hand-painted 2D combat and five interlocking tales.",
"Dragon's Crown|2013|Vanillaware|Beat 'em up,Action RPG|PS3,Vita,PS4|82|The most beautiful side-scrolling brawler made.",
"13 Sentinels: Aegis Rim|2019|Vanillaware|Visual Novel,Tactics|PS4,Switch,PC|88|Thirteen timelines that fit together perfectly.",
"Unicorn Overlord|2024|Vanillaware|Tactics,RPG|PS5,Switch,Xbox Series|86|Squad tactics on a continent worth liberating.",
"Tales of Symphonia|2003|Namco Tales Studio|JRPG,Action RPG|GameCube,PS2,PC|86|The series' most-loved cast and world.",
"Tales of Vesperia|2008|Namco Tales Studio|JRPG,Action RPG|Xbox 360,PS4,Switch|82|Yuri Lowell, the rare JRPG lead who acts like an adult.",
"Tales of Berseria|2016|Bandai Namco Studios|JRPG,Action RPG|PS4,PC|78|Led by a woman driven entirely by revenge.",
"Ys VIII: Lacrimosa of Dana|2016|Nihon Falcom|Action RPG|PS4,PC,Switch|85|Shipwrecked on an island, with the fastest combat around.",
"The Legend of Heroes: Trails in the Sky|2004|Nihon Falcom|JRPG,Turn-Based|PC,PSP,Switch|85|Slow, patient world building that pays off enormously.",
"The Legend of Heroes: Trails of Cold Steel|2013|Nihon Falcom|JRPG,Turn-Based|PC,PS4,Switch|82|A military academy, and politics with real consequences.",
"Atelier Ryza|2019|Gust|JRPG,Simulation|PS4,Switch,PC|79|The gentlest alchemy crafting sim in the genre.",
"Disgaea|2003|Nippon Ichi Software|Tactics,JRPG|PS2,PSP,Switch|85|Damage numbers in the millions and 9999 levels.",
"Granblue Fantasy: Relink|2024|Cygames|Action RPG|PC,PS5|81|Slick party action combat with enormous production values.",
"Sea of Stars|2023|Sabotage Studio|JRPG,Turn-Based|PC,PS5,Switch,Xbox Series|83|A love letter to Chrono Trigger that stands on its own.",
"Chained Echoes|2022|Matthias Linda|JRPG,Turn-Based|PC,PS4,Switch|82|One developer, sixteen-bit ambition, no random encounters.",
"Digimon Story: Cyber Sleuth|2015|Media.Vision|JRPG,Turn-Based|Vita,PS4,PC|75|A genuinely good monster-collecting RPG.",
"Lost Odyssey|2008|Mistwalker|JRPG,Turn-Based|Xbox 360|78|A thousand years of grief in optional short stories.",
"The Last Story|2011|Mistwalker|JRPG,Action RPG|Wii|80|Sakaguchi and Uematsu, one last time on the Wii.",
"Honkai Impact 3rd|2016|miHoYo|Action RPG,Gacha|PC,Mobile|80|The studio's action template before Genshin.",
"Arknights|2019|Hypergryph|Tower Defence,Gacha|Mobile,PC|80|Tower defence with real difficulty and enormous style.",
"Blue Archive|2021|Nexon Games|JRPG,Gacha|Mobile,PC|78|Schoolgirls with assault rifles and a shocking amount of heart.",
"Azur Lane|2017|Manjuu|Shoot 'em up,Gacha|Mobile,PC|75|Warships as characters, in a side-scrolling bullet hell.",
"Umamusume: Pretty Derby|2021|Cygames|Simulation,Gacha|Mobile,PC|80|Horse girl racing management, and a genuine phenomenon.",
"Goddess of Victory: Nikke|2022|Shift Up|Shooter,Gacha|Mobile,PC|76|A cover shooter that plays far better than expected.",
"Infinity Nikki|2024|Papergames|Adventure,Open World|PC,PS5,Mobile|78|Dress-up as an open-world traversal system.",
"Monster Strike|2013|Mixi|Puzzle,Mobile|Mobile|76|Flick your monsters like marbles. Japan's biggest earner for years.",
"Dragon Ball Z: Dokkan Battle|2015|Akatsuki|Puzzle,Gacha|Mobile|74|Orb-linking battles and a decade of anniversaries.",
"Diablo|1996|Blizzard North|Action RPG|PC,PS1|94|A dark cathedral, sixteen levels down.",
"Diablo Immortal|2022|Blizzard Entertainment|Action RPG,Mobile|Mobile,PC|58|Plays wonderfully. The store is the problem.",
"Baldur's Gate|1998|BioWare|RPG|PC,Mac|91|The Infinity Engine arrives and PC RPGs change.",
"Icewind Dale|2000|Black Isle Studios|RPG|PC,Mac|87|Less talking, more dungeon, gorgeous backdrops.",
"Neverwinter Nights|2002|BioWare|RPG|PC,Mac|91|Shipped with the toolset that built a modding scene.",
"Ultima VII: The Black Gate|1992|Origin Systems|RPG|PC|93|A simulated world you could bake bread in.",
"The Elder Scrolls II: Daggerfall|1996|Bethesda Game Studios|Action RPG,Open World|PC|89|A procedurally generated province the size of England.",
"Vampire: The Masquerade - Bloodlines|2004|Troika Games|Action RPG,Immersive Sim|PC|80|Buggy, unfinished, and one of the best-written RPGs ever.",
"Fallout|1997|Interplay|RPG,Turn-Based|PC,Mac|89|Retro-future wasteland, and dialogue with real teeth.",
"Fallout 76|2018|Bethesda Game Studios|Action RPG,MMO|PC,PS4,Xbox One|52|A disastrous launch that quietly became decent.",
"Wasteland 2|2014|inXile Entertainment|RPG,Turn-Based|PC,PS4,Switch|81|The original post-apocalypse RPG lineage, revived.",
"Wasteland 3|2020|inXile Entertainment|RPG,Turn-Based|PC,PS4,Xbox One|85|Frozen Colorado, co-op campaign, excellent writing.",
"Pillars of Eternity II: Deadfire|2018|Obsidian Entertainment|RPG|PC,PS4,Switch|88|An archipelago, a ship to sail, and superb factions.",
"Tyranny|2016|Obsidian Entertainment|RPG|PC,Mac|80|You work for the evil empire, and it already won.",
"Torment: Tides of Numenera|2017|inXile Entertainment|RPG|PC,PS4,Xbox One|81|A billion years in the future, told in enormous prose.",
"Divinity: Original Sin|2014|Larian Studios|RPG,Turn-Based|PC,PS4,Xbox One|87|Where Larian's elemental chaos started.",
"Dragon Age II|2011|BioWare|RPG|PC,PS3,Xbox 360|82|One city over ten years. Divisive, and braver than remembered.",
"Dragon Age: The Veilguard|2024|BioWare|Action RPG|PC,PS5,Xbox Series|82|Gorgeous combat, and a very long wait to get here.",
"Mass Effect: Andromeda|2017|BioWare|Action RPG,Open World|PC,PS4,Xbox One|71|Best combat in the series, worst everything else.",
"The Witcher|2007|CD Projekt Red|Action RPG|PC,Mac|81|Rough, adult, and clearly the work of people with something to prove.",
"Gothic|2001|Piranha Bytes|Action RPG,Open World|PC|81|A prison colony where everything wants you dead.",
"Gothic II|2002|Piranha Bytes|Action RPG,Open World|PC|82|Harsher, larger, and beloved for it.",
"GreedFall|2019|Spiders|Action RPG|PC,PS4,Xbox One|72|Colonial fantasy with genuinely tangled politics.",
"Pathfinder: Wrath of the Righteous|2021|Owlcat Games|RPG,Turn-Based|PC,PS4,Xbox One|84|An enormous crusade with mythic paths.",
"Warhammer 40,000: Rogue Trader|2023|Owlcat Games|RPG,Turn-Based|PC,PS5,Xbox Series|81|Grimdark space nobility with a huge rules engine.",
"Stellar Blade|2024|Shift Up|Action RPG|PS5,PC|81|Sharp parry-driven combat and a striking art direction.",
"Rise of the Ronin|2024|Team Ninja|Action RPG,Open World|PS5,PC|76|Bakumatsu Japan, and Team Ninja combat opened up.",
"Nioh|2017|Team Ninja|Souls-like,Action RPG|PS4,PC|88|Stances, ki pulses, and loot by the sackful.",
"Wo Long: Fallen Dynasty|2023|Team Ninja|Souls-like,Action RPG|PC,PS5,Xbox Series|80|Deflection-first combat in Three Kingdoms China.",
"Another Crab's Treasure|2024|Aggro Crab|Souls-like,Action|PC,PS5,Switch|80|A hermit crab wearing rubbish, and a real Souls game underneath.",
"Remnant II|2023|Gunfire Games|Souls-like,TPS|PC,PS5,Xbox Series|82|Souls with guns and procedurally rearranged worlds.",
"Code Vein|2019|Bandai Namco Studios|Souls-like,Action RPG|PC,PS4,Xbox One|70|Anime vampires, and a partner system that softens the edges.",
"The First Berserker: Khazan|2025|Neople|Souls-like,Action RPG|PC,PS5,Xbox Series|82|Cel-shaded and unusually generous with its combat.",
"Eiyuden Chronicle: Hundred Heroes|2024|Rabbit and Bear Studios|JRPG,Turn-Based|PC,PS5,Switch|76|Suikoden's creators building a castle again.",
"Bravely Default II|2021|Claytechworks|JRPG,Turn-Based|Switch,PC|75|The brave and default economy, in HD."
]);
