/* Postgame - game catalogue, part 17
   Harvested from Steam. Rows carry two extra fields: the Steam app id
   (for the 600x900 capsule) and the percentage of Steam reviews that
   are positive. */
window.GAME_ROWS = (window.GAME_ROWS || []).concat([
"DYNASTY WARRIORS 8: Xtreme Legends Complete Edition|2014|KOEI TECMO GAMES CO., LTD.|Hack and Slash,Action,Co-op|PC|71|Dynasty Warriors 8: Xtreme Legends introduces entirely new levels of fun to the refreshing.|278080|84",
"Ragnarok Online 2|2013|Gravity, Inc.|RPG,MMO,JRPG|PC||Return to the beautiful and dangerous world of Midgard! Inspired by Norse mythology, the.|231060|58",
"Crysis 2 - Maximum Edition|2011|Crytek Studios|Action,FPS,Shooter|PC||Aliens are decimating New York City, only you have the technology to survive. Be The Weapon.|108800|85",
"Farm Together|2018|Milkstone Studios|Simulation,Co-op,Farming|PC,Mac,Linux||Grow your own farm all by yourself, or cooperate with your friends in this unique, relaxing.|673950|94",
"Sands of Salzaar|2021|汉家松鼠Han-Squirrel Studio|Open World,RPG,Strategy|PC||Bringing you to an exotic desert where you'll recruit, train, and guide your troops into battle.|1094520|82",
"Five Nights at Freddy's: Security Breach|2021|Steel Wool Studios|Horror,Stealth,Exploration|PC||In Five Nights at Freddy's: Security Breach, play as Gregory, a young boy who's been trapped.|747660|86",
"Spelunky|2013|Mossmouth|Platformer,Roguelike,Co-op|PC|90|Spelunky is a unique platformer with randomized levels that offer a challenging new experience.|239350|92",
"Secret World Legends|2017|Funcom|MMO,RPG,Horror|PC|76|Secret World Legends is a story-driven, shared-world action RPG that plunges players into a.|215280|67",
"Mafia III: Definitive Edition|2020|Hangar 13|Open World,Action,Adventure|PC,Mac||After Lincoln Clay's surrogate family, the black mob, is betrayed and killed by the Italian.|360430|57",
"AMID EVIL|2019|Indefatigable|FPS,Shooter,Action|PC|85|A retro FPS for the ages! Once branded a HERETIC. Now YOU have been chosen as our champion!.|673130|94",
"Thunder Tier One|2021|KRAFTON, Inc.|Co-op,Tactical,Shooter|PC|65|Thunder Tier One is a realistic top-down shooter where you join an elite special operations.|377300|67",
"KINGDOM HEARTS -HD 1.5+2.5 ReMIX-|2024|Square Enix|Action,RPG,Adventure|PC||KINGDOM HEARTS -HD 1.5+2.5 ReMIX- is an HD remastered collection of 6 unforgettable KINGDOM.|2552430|84",
"Move or Die|2016|Xelu|Action,Co-op,Platformer|PC,Linux|80|Move or Die is an absurdly fast-paced 4-player local and online party game where the mechanics.|323850|90",
"BONEWORKS|2019|Stress Level Zero|VR,Action,Sandbox|PC|72|BONEWORKS is an Experimental Physics VR Adventure. Use found physics weapons, tools, and.|823500|92",
"NBA 2K19|2018|Visual Concepts|Sports,Simulation,Co-op|PC|76|NBA 2K celebrates 20 years of redefining what sports gaming can be. NBA 2K19 continues to push.|841370|39",
"Serious Sam II|2012|Croteam|Action,FPS,Co-op|PC|74|Serious Sam II is a shot of adrenaline to the hearts of first-person shooter fans across the.|204340|90",
"Outward Definitive Edition|2022|Nine Dots Studio|RPG,Open World,Survival|PC||No remarkable journey is achieved without great effort. In Outward, the cold of the night or an.|794260|73",
"Woodle Tree Adventures|2016|Fabio Ferrara|Platformer,Adventure,Action|PC,Mac,Linux||Woodle Tree Adventures is an old school platform game with a catchy and unique art style!.|299460|67",
"Capcom Arcade 2nd Stadium|2022|CAPCOM Co., Ltd.|Action,Arcade,Platformer|PC||Play more of your favorite arcade hits from yesteryear. Includes SONSON for free!|1755910|68",
"Strobophagia / Rave Horror|2020|Green Tile Digital|Adventure,Horror,Mystery|PC||An occult forest rave ⸸ Strange rituals ⸸ Enigmatic organisers ⸸ An ancient evil ⸸ Pure.|1266680|",
"Dead Rising 3 Apocalypse Edition|2014|Capcom Game Studio Vancouver|Open World,Action,Co-op|PC||Explore the zombie-infested city of Los Perdidos, and find a way to escape before a military.|265550|77",
"Viscera Cleanup Detail|2015|RuneStorm|Simulation,Co-op,Horror|PC,Mac||In Viscera Cleanup Detail, you step into the boots of a space-station janitor tasked with.|246900|93",
"Jack Orlando: Director's Cut|2013|Toontraxx Studios|Adventure,Point and Click,Detective|PC,Mac,Linux||1933 will go down in the history books as the year America passed the 21st Amendment to the.|253960|69",
"The Lab|2016|Valve|VR,Action,Adventure|PC||Welcome to The Lab, a compilation of Valve's room-scale VR experiments set in a pocket universe.|450390|95",
"Command & Conquer Red Alert 3|2009|EA Los Angeles|Strategy,RTS,Action|PC|82|The desperate leadership of a doomed Soviet Union travels back in time to change history and.|17480|85",
"The Long Drive|2019|Genesz|Racing,Open World,Survival|PC||Random generated open world semi-post apocalyptic survival car driving game.|1017180|90",
"The Past Within|2022|Rusty Lake|Co-op,Puzzle,Horror|PC,Mac||The Past Within is the new co-op experience from Rusty Lake! Play together with someone you.|1515210|95",
"Not For Broadcast|2022|NotGames|Adventure,Simulation,Management|PC|82|A new political Party has won a landslide in the General Election, and for some reason the.|1147550|94",
"Lost Castle|2016|Hunter Studio|Beat 'em up,Dungeon Crawler,Roguelike|PC,Mac||Lost Castle is an action RPG beat'em up with roguelike elements and randomized dungeons for up.|434650|87",
"Aseprite|2016|Igara Studio|Horror|PC,Mac,Linux||Aseprite is a pixel-art tool to create 2D animations, sprites, and any kind of graphics for.|431730|99",
"The Riftbreaker|2021|EXOR Studios|Tower Defence,Survival,Strategy|PC|83|The Riftbreaker is a solo or Co-op base-building, survival game with Action-RPG elements for up.|780310|90",
"The Walking Dead: Season Two|2013|Telltale Games|Adventure,Point and Click,Horror|PC,Mac|80|The Walking Dead: Season Two continues the story of Clementine, a young girl orphaned by the.|261030|96",
"Age of Wonders III|2014|Triumph Studios|Strategy,RPG,Turn-Based|PC,Mac,Linux|80|Age of Wonders III is the long anticipated sequel to the award-winning strategy series..|226840|80",
"Portal Knights|2017|Keen Games GmbH|Adventure,Sandbox,RPG|PC|72|The world of Elysia needs YOU! Join this cooperative, 3D sandbox action RPG to level up your.|374040|83",
"Atomic Heart|2023|Mundfish|FPS,Horror,Puzzle|PC|76|In a mad and sublime utopian world, take part in explosive encounters. Adapt your fighting.|668580|82",
"Farthest Frontier|2025|Crate Entertainment|Strategy,Immersive Sim,City Builder|PC|83|Protect and guide your people as you forge a town from untamed wilderness at the edge of the.|1044720|86",
"Spiritfarer: Farewell Edition|2020|Thunder Lotus|Adventure,Management,Exploration|PC,Mac,Linux|84|Spiritfarer is a cozy management game about dying. As ferrymaster to the deceased, build a.|972660|95",
"OMORI|2020|OMOCAT, LLC|Horror,Adventure,RPG|PC,Mac|88|Explore a strange world full of colorful friends and foes. When the time comes, the path you've.|1150690|97",
"Warhammer 40,000: Dawn of War - Soulstorm|2008|Relic Entertainment|Strategy,RTS,Action|PC||The third and final expansion to the genre-defining and critically-acclaimed RTS, Dawn of War..|9450|95",
"Prismata|2018|Lunarch Studios|Strategy,Card Game,Simulation|PC,Mac||A perfect-information strategy game inspired by RTS, deckbuilders, and board games. Choose from.|490220|82",
"Escape Room - Der kranke Kollege|2020|Bitbeast Games|Horror,Puzzle,Adventure|PC||You only wanted to make a visit to your sick colleague, but what you encounter is beyond your.|1301720|82",
"Modern Combat 5|2018|Gameloft|FPS,Action,Shooter|PC||A fast-paced military FPS with a thrilling solo campaign and 10 multiplayer game modes.|921060|55",
"Dino D-Day|2011|800 North and Digital Ranch|Action,FPS,Shooter|PC|53|Frantic, multiplayer action involving Nazis and dinosaurs! What are you waiting for? This is.||84",
"Darkwood|2017|Acid Wizard Studio|Horror,Survival,Open World|PC,Mac,Linux|80|Darkwood - a new perspective on survival horror. Scavenge and explore a rich, ever-changing.|274520|95",
"Amnesia: A Machine for Pigs|2013|The Chinese Room|Horror,Adventure,Exploration|PC,Mac,Linux|72|From the creators of Amnesia: The Dark Descent and Dear Esther comes a new first-person.|239200|70",
"Serious Sam 4|2020|Croteam|Action,FPS,Co-op|PC|68|Serious Sam 4 reignites the classic FPS series in a high-powered prequel loaded with an.|257420|83",
"Action Taimanin|2020|LiLith|Action,Hack and Slash,RPG|PC||An intense, gorgeous hack-and-slash action RPG from the Taimanin fame!|1335200|83",
"The Last of Us Part I|2023|Naughty Dog LLC|Adventure,Shooter,Action Adventure|PC||Discover the award-winning game that inspired the critically acclaimed television show. Guide.|1888930|80",
"Civilization IV: Warlords|2007|Firaxis Games|Strategy,Turn-Based|PC,Mac|84|Sid Meier's Civilization IV: Warlords is the first expansion pack for the award-winning game.|34450|",
"Dream Daddy: A Dad Dating Simulator|2017|Game Grumps|Visual Novel,Simulation,Adventure|PC,Mac,Linux|72|Dream Daddy: A Dad Dating Simulator is a game where you play as a Dad and your goal is to meet.|654880|92",
"Stoneshard|2020|Ink Stains Games|RPG,Roguelike,Strategy|PC,Linux||Stoneshard is a hardcore turn-based RPG about the harsh life of a medieval mercenary: travel.|625960|74",
"PICO PARK|2021|TECOPARK|Co-op,Platformer,Action|PC||PICO PARK is a cooperative local/online multiplay action puzzle game for 2-8 players.|1509960|91",
"The Callisto Protocol|2022|Striking Distance Studios|Horror,TPS,Shooter|PC||Survive to escape the horrors of Callisto and uncover the dark secrets of Jupiter's dead moon.|1544020|65",
"Furry Killer|2022|Sujikon|Tactics,Simulation,Shoot 'em up|PC,Linux||Furry Killer is a fast-paced arena shooter where you fight against waves of evil furry.|2206460|",
"X-COM: UFO Defense|2008|MicroProse Software, Inc|Strategy,Turn-Based,Tactical|PC||You are in control of X-COM: an organization formed by the world's governments to fight the.|7760|95",
"Warriors of Vilvatikta|2016|RPG Video|RPG,Adventure|PC||Warriors of Vilvatikta is an epic RPG inspired by real Indonesian history.||",
"ORION: Prelude|2013|DANKIE|Action,FPS,Co-op|PC||Work together to survive the devastating Dinosaur horde in huge, endless environments.|104900|75",
"Strife|2015|S2 Games|MOBA,Action,Strategy|PC,Linux||Strife is a truly free to play, competitive, MOBA that features non-stop action and engaging.||77",
"Dungeons 2|2015|Realmforge Studios|Strategy,Management,RPG|PC,Mac,Linux|70|The Dungeon Lord is back - and this time he's serious! In Dungeons 2, fulfil the Dungeon Lord's.|262280|82",
"BLEACH Brave Souls|2020|KLab Inc.|RPG,Action,Action RPG|PC||The world of mega-hit manga and anime BLEACH comes to Steam in this exciting 3D action game!.|1201240|89",
"Bopl Battle|2023|Johan Grönvall|Fighting,Action,Co-op|PC||A couch/online game where you battle your friends with unique and wild abilities. There are.|1686940|97",
"Secret Neighbor: Hello Neighbor Multiplayer|2019|Hologryph|Horror,Co-op,Stealth|PC||Hello Neighbor Multiplayer. Secret Neighbor is a Multiplayer Social Horror Game where a group.|859570|86",
"Need for Speed Unbound|2022|Criterion Games|Racing,Open World,Action|PC||Race to the top, definitely don't flop. Outsmart the cops, and enter weekly qualifiers for The.|1846380|60",
"Stranded Deep|2022|Beam Team Games|Survival,Open World,Adventure|PC,Mac,Linux||Take the role of a plane crash survivor stranded somewhere in the Pacific Ocean. Come face to.|313120|74",
"Escape Simulator|2021|Pine Studio|Puzzle,Co-op,Adventure|PC,Mac,Linux|82|First-person puzzler you can play solo or in an online co-op. Explore a set of highly.|1435790|94",
"Timberborn|2026|Mechanistry|City Builder,Colony Sim,Sandbox|PC,Mac|85|Humans are long gone. In a world struck by droughts and toxic waste, will your lumberpunk.|1062090|96",
"F.E.A.R. 3|2011|Day 1 Studios|FPS,Horror,Co-op|PC|74|F.E.A.R. 3 delivers all the hallmarks that define the F.E.A.R. brand: terrifying paranormal.||71",
"eFootball PES 2021 SEASON UPDATE|2020|Konami Digital Entertainment|Sports,Co-op,Horror|PC||Celebrate 25 years of PES with the eFootball PES 2021 Season Update* - available at a special.|1259970|77",
"Crysis 2 Remastered|2022|Crytek|Action,FPS,Shooter|PC||Relive the legendary single-player campaign from the classic first-person shooter, Crysis 2.|2096600|89",
"ShareX|2015|ShareX Team|Action|PC||ShareX is a free and open source program that can capture or record selected area from the.|400040|96",
"Streets of Rogue|2019|Matt Dabrowski|Roguelike,RPG,Action|PC,Mac,Linux||Fight, sneak, and hack your way through randomly generated cities. It's like Nuclear Throne.|512900|96",
"Sakura Clicker|2015|Winged Cloud|Adventure,RPG,Simulation|PC||The latest entry in the Sakura series is more action-packed than ever before! Sakura Clickers.|383080|83",
"Stormworks: Build and Rescue|2020|Geometa|Sandbox,Open World,Immersive Sim|PC,Mac||Join a world where you design, create and pilot your own air sea rescue service. Release your.|573090|90",
"S.T.A.L.K.E.R.: Clear Sky|2008|GSC Game World|Open World,FPS,Survival|PC|75|S.T.A.L.K.E.R.: Clear Sky - standalone prequel for the acclaimed S.T.A.L.K.E.R.: Shadow of.|20510|85",
"Starship Troopers: Extermination|2024|Offworld|Co-op,Action,FPS|PC||Starship Troopers: Extermination is a 16-player co-op FPS that puts you on the far-off.|1268750|81",
"Project Winter|2019|Other Ocean Interactive|Exploration,Adventure,Social Deduction|PC||Project Winter 2.0: Cabin Fever is an 8-player survival and social deception game where.|774861|83",
"Necesse|2025|Fair Games ApS|Survival,Open World,Sandbox|PC,Mac,Linux||Build, quest, and conquer across an infinite procedurally generated world. Play alone or with.|1169040|94",
"Lords of the Fallen|2023|CI Games|Souls-like,Exploration,Action|PC|75|A vast world awaits in the medieval, dark fantasy action-RPG, Lords of the Fallen. As a fabled.|1501750|66",
"SpongeBob SquarePants: Battle for Bikini Bottom - Rehydrated|2020|Purple Lamp|Platformer,Adventure,Action|PC||Are you ready, kids? The cult classic is back, faithfully remade in spongetastic splendor! Play.|969990|94",
"My Summer Car|2025|Amistech Games|Simulation,Racing,Open World|PC||My Summer Car is the ultimate car owning, building, fixing, tuning, maintenance AND permadeath.|516750|95",
"Turmoil|2016|Gamious|Management,Strategy,Tactics|PC,Mac,Linux|73|Drill for oil like it's 1899! Turmoil offers players a visually charming, tongue-in-cheek take.|361280|93",
"High Octane Drift|2016|Cruderocks|Racing,Simulation,Sports|PC||Enter the world of professional competitive drift and win online series amongst hundreds of.|457330|55",
"The Pillage|2018|Bishop Armstrong|Action,Arcade,Hack and Slash|PC||A fast paced hack-n-slash arcade game where kidneys are harvested from everyone in your path.|715210|",
"Zero Escape: Zero Time Dilemma|2016|Spike Chunsoft Co., Ltd.|Puzzle,Visual Novel,Adventure|PC|78|Nine participants awaken, trapped in an underground facility. To escape, they must play a game.|311240|83",
"Warhammer 40,000: Dawn of War - Dark Crusade|2007|Relic Entertainment|Strategy,RTS,Action|PC|87|Deep under the central desert of Kronus, a vast honeycomb of skull-lined tunnels and funeral.|4580|96",
"Little Nightmares II|2021|Tarsier Studios|Horror,Adventure,Puzzle|PC|83|Little Nightmares II is the second game in a series that has thrilled and captivated millions.|860510|94",
"The Ship: Murder Party|2006|Outerlight Ltd.|Action,Stealth,Mystery|PC|76|The Ship is a murder mystery multiplayer.||86",
"Furi|2016|The Game Bakers|Shoot 'em up,Hack and Slash,Beat 'em up|PC|76|The jailer is the key, kill him and you'll be free. Fight your way free in this.|423230|91",
"Drug Dealer Simulator|2020|Byterunners|Simulation,Action,Open World|PC|59|Have you ever considered creating your own crime empire, without the legal and moral.|682990|75",
"Spooky's Jump Scare Mansion|2015|Lag Studios|Horror,Adventure,Survival|PC||Can you survive 1000 rooms of cute terror? Or will you break once the cuteness starts to fade.|356670|93",
"Cell to Singularity - Evolution Never Ends|2021|Computer Lunch|Simulation,Sandbox,Point and Click|PC,Mac||The epic story of evolution, technology, humanity, and dinosaurs is yours to tap.|977400|90",
"Just Survive|2015|Daybreak Game Company|Survival,Open World,MMO|PC||Just Survive is a post-apocalyptic survival game that immerses you in a world where humanity is.||59",
"Poker Night at the Inventory (2010 Original Version)|2010|Telltale Games|Card Game,Strategy,Sports|PC,Mac|71|Prepare for a different kind of poker night in a very different kind of club and play against.||90",
"Need for Speed|2020|Ghost Games|Racing,Open World,Action|PC||Ready to own the streets? Get behind the wheel of iconic cars and floor it through Ventura Bay.|1262540|70",
"Fallout 2: A Post Nuclear Role Playing Game|2009|Black Isle Studios|RPG,Open World,Turn-Based|PC|86|Fallout 2 is the sequel to the critically acclaimed game that took RPG'ing out of the dungeons.|38410|94",
"Bloody Spell|2022|艺龙游戏|Action RPG,Hack and Slash,Action|PC||This is a martial arts action role-playing game. The core of the game is battle-oriented, and.|992300|89",
"Worms Armageddon|2013|Team17 Digital Ltd|Strategy,Turn-Based,Co-op|PC||Those intrepid invertebrates return with a vengeance in the much-loved Worms Armageddon. It's.|217200|94",
"GROUND BRANCH|2026|BlackFoot Studios|Tactical,FPS,Shooter|PC||From one of the developers behind the original Rainbow Six and Ghost Recon games, comes a.|16900|89",
"SUNLESS SEA|2015|Failbetter Games|Exploration,Survival,Adventure|PC,Mac,Linux|81|LOSE YOUR MIND. EAT YOUR CREW. DIE. Take the helm of your steamship and set sail for the.|304650|83",
"Far Cry 3 - Blood Dragon|2013|Ubisoft Montreal|FPS,Open World,Action|PC|81|Far Cry 3: Blood Dragon is THE Kick-Ass Cyber Shooter.Welcome to an 80's vision of the future..||88"
]);
