/* Postgame - game catalogue, part 14
   Harvested from Steam. Rows carry two extra fields: the Steam app id
   (for the 600x900 capsule) and the percentage of Steam reviews that
   are positive. */
window.GAME_ROWS = (window.GAME_ROWS || []).concat([
"Trine Enchanted Edition|2009|Frozenbyte|Platformer,Action,Co-op|PC,Mac,Linux|80|Three Heroes make their way through dangers untold in a fairytale world of great castles and.|35700|96",
"Sanctum 2|2013|Coffee Stain Studios|Tower Defence,FPS,Co-op|PC,Mac,Linux|77|Sanctum 2 is the sequel to the world's first Tower Defense/FPS hybrid game. Pick from four.|210770|90",
"State of Decay 2: Juggernaut Edition|2020|Undead Labs|Survival,Open World,Co-op|PC|69|The dead have risen and civilization has fallen. Now it's up to you to gather survivors.|495420|83",
"Jotun: Valhalla Edition|2015|Thunder Lotus|Adventure,Action,Exploration|PC,Mac,Linux|79|Jotun is a hand-drawn action-exploration game set in Norse mythology. In Jotun, you play Thora.|323580|77",
"Brutal Legend|2013|Double Fine Productions|Action,Adventure,Open World|PC,Mac,Linux|80|Brütal Legend is an action-adventure that marries visceral action combat with open-world.|225260|93",
"Buckshot Roulette|2024|Mike Klubnika|Horror,Strategy,Puzzle|PC,Linux||Play Russian roulette with a 12-gauge shotgun. Four enter. One leaves. Roll the dice with your.|2835570|96",
"Surviving Mars|2018|Haemimont Games|Colony Sim,City Builder,Strategy|PC,Mac,Linux|76|There will be challenges to overcome. Execute your strategy and improve your colony's chances.|464920|85",
"Star Trek Online|2012|Cryptic Studios|MMO,RPG,Open World|PC|66|In Star Trek Online, the Star Trek universe appears for the first time on a truly massive.|9900|79",
"Kholat|2015|IMGN.PRO|Horror,Adventure,Exploration|PC|64|The most terrifying journey of your life set in the beautiful winter scenery of the Ural.|343710|67",
"The Red Solstice|2015|Ironward|Strategy,Tactical,RTS|PC|74|2280 A.D. The last few survivors of a ruined Earth seek a new home: Mars, a planet whose.|265590|71",
"HELLDIVERS Dive Harder Edition|2015|Arrowhead Game Studios|Co-op,Shooter,Action|PC|83|HELLDIVERS is a hardcore, cooperative, twin stick shooter. As part of the elite unit called.|394510|90",
"RISK: Global Domination|2020|SMG Studio|Strategy,Turn-Based,Tactical|PC,Mac||Take over the world in RISK: Global Domination, the iconic strategy board game with 100+.|1128810|80",
"Total War: ATTILA|2015|CREATIVE ASSEMBLY|Strategy,RTS,Tactical|PC,Mac,Linux|80|Against a darkening background of famine, disease and war, a new power is rising in the great.|325610|82",
"Call of Juarez: Gunslinger|2013|Techland|FPS,Action,Shooter|PC|79|From the dust of a gold mine to the dirt of a saloon, Call of Juarez Gunslinger is a real.|204450|95",
"Aura Kingdom|2014|X-Legend|MMO,RPG,Adventure|PC||Aura Kingdom is a free-to-play Anime MMORPG featuring strong PVE elements, a uniquely detailed.|268420|78",
"Football Manager 2017|2016|Sports Interactive|Sports,Simulation,Management|PC,Mac,Linux|80|Take control of your favourite football team in Football Manager 2017, the most realistic and.|482730|60",
"Heaven Forest NIGHTS|2017|Fabio Ferrara|Adventure,Action,VR|PC,Mac,Linux||The sequel to the Heaven Forest series. While the first game was about the meaning of life.||67",
"Naruto Shippuden: Ultimate Ninja Storm 4|2016|CyberConnect2 Co. Ltd.|Fighting,Action,Adventure|PC||The latest opus in the acclaimed STORM series is taking you on a colourful and breathtaking.|349040|91",
"Totally Accurate Battlegrounds|2018|Landfall|MMO,Simulation,Strategy|PC||Grab your balloon crossbow and trusty inflatable hammer, because things are about to get.|823130|88",
"Pathfinder: Kingmaker - Enhanced Plus Edition|2018|Owlcat Games|RPG,Adventure,Strategy|PC,Mac,Linux|73|Pathfinder: Kingmaker - Enhanced Plus Edition is the first isometric party-based cRPG set in.|640820|78",
"Darksiders|2010|Vigil Games|Action,Adventure,Hack and Slash|PC|83|Deceived by the forces of evil into prematurely bringing about the end of the world, War - the.|50620|89",
"For The King|2018|IronOak Games|RPG,Co-op,Strategy|PC,Mac,Linux|79|For The King is a strategic RPG that blends tabletop and roguelike elements in a challenging.|527230|88",
"RIFT|2011|gamigo US Inc.|MMO,RPG,Open World|PC|84|Dive into a world of epic adventure! Create your perfect hero thanks to a uniquely customizable.|39120|74",
"Age of Mythology: Extended Edition|2014|SkyBox Labs|Strategy,RTS,Simulation|PC|66|Age of Mythology is back! Choose your god and take to the battlefield in this classic, upgraded.|266840|93",
"Car Mechanic Simulator 2018|2017|Red Dot Games|Simulation,Racing,Sandbox|PC,Mac||Build and expand your repair service empire in this incredibly detailed and highly realistic.|645630|91",
"Day of Defeat: Source|2010|Valve|FPS,Action,Shooter|PC,Linux|80|Valve's WWII Multiplayer Classic - Now available for Mac.|300|92",
"Dragon Ball: Sparking! ZERO|2024|Spike Chunsoft Co., Ltd.|Action,Fighting,Co-op|PC|83|DRAGON BALL: Sparking! ZERO takes the legendary gameplay of the Budokai Tenkaichi series and.|1790600|89",
"Marvel's Midnight Suns|2022|Firaxis Games|Tactics,Card Game,Strategy|PC||FIGHT AND STRATEGIZE LIKE A SUPER HERO IN THE DARKER CORNERS OF THE MARVEL UNIVERSE. Play as.|368260|82",
"Mitos.is: The Game|2015|Freakinware Studios|MMO,Strategy,Survival|PC,Mac||Step into the microscopic world of Mitos.is! Eat or be eaten-become the ultimate cell in a.|389570|81",
"Operation: Harsh Doorstop|2023|Drakeling Labs|FPS,Tactical,Shooter|PC||Operation: Harsh Doorstop is the ultimate, free to play, tactical shooter sandbox. Play.|736590|77",
"Dome Keeper|2022|Bippinbits|Roguelike,Action,Tower Defence|PC,Mac,Linux||Defend against waves of alien monsters in this unique roguelike action miner. Dig for.|1637320|92",
"Warhammer 40,000: Dawn of War II - Anniversary Edition (Classic)|2009|Relic Entertainment|Strategy,RTS,Tactical|PC,Mac,Linux|85|All of Warhammer 40,000: Dawn of War II in one package. Play the award-winning real-time.|15620|88",
"No Rest for the Wicked|2024|Moon Studios GmbH|Open World,Souls-like,Action RPG|PC||From Moon Studios, the award-winning creators of Ori and the Blind Forest and Ori and the Will.|1371980|78",
"Lossless Scaling|2018|THS|FPS|PC||All-in-one gaming utility for frame generation and scaling|993090|89",
"Heaven Forest - VR MMO|2016|Fabio Ferrara|MMO,Adventure,VR|PC,Mac,Linux||The pressing human questions about life depend directly on our attitudes toward the universe..||68",
"The Bureau: XCOM Declassified|2013|2K Marin|Action,Tactical,TPS|PC,Mac|66|The year is 1962 and the Cold War has the nation gripped by fear. A top-secret government unit.|65930|70",
"Monster Hunter Stories 2: Wings of Ruin|2021|CAPCOM Co., Ltd.|RPG,Adventure,JRPG|PC|82|A new adventure awaits you in this second installment of the turn-based RPG series set in the.|1277400|82",
"Barotrauma|2023|FakeFish|Co-op,Survival,Horror|PC,Mac,Linux|81|Barotrauma is a 2D co-op submarine simulator - in space, with survival horror and RPG elements..|602960|94",
"Moonlighter|2018|Digital Sun|Hack and Slash,Dungeon Crawler,Roguelike|PC,Mac,Linux|74|Moonlighter is an Action RPG with rogue-lite elements that demonstrates two sides of the coin -.|606150|82",
"MechWarrior Online Legends|2015|Piranha Games Inc.|Shooter,Action,Simulation|PC||MechWarrior Online Legends is a tactical, 'Mech-based online shooter set in the vast.|342200|80",
"Chivalry 2|2022|Torn Banner Studios|MMO,Hack and Slash,Action|PC|82|Chivalry 2 is a multiplayer first person slasher inspired by epic medieval movie battles..|1824220|80",
"Warhammer 40,000: Space Marine - Anniversary Edition|2011|Relic Entertainment|Action,TPS,Shooter|PC|74|In Warhammer 40,000 Space Marine you are Captain Titus, a Space Marine of the Ultramarines.|55150|92",
"Duck Game|2015|Landon Podbielski|Action,Platformer,Shooter|PC|82|Enter the futuristic year of 1984, an age where ducks run wild in a frantic battle for glory..|312530|97",
"Freddy Fazbear's Pizzeria Simulator|2017|Scott Cawthon|Horror,Simulation,Strategy|PC||Start your own Freddy Fazbear's Pizzeria with Freddy Fazbear Pizzeria Simulator!||94",
"Creative Destruction|2018|NetEase Games|Battle Royale,Action,Shooter|PC||Welcome to the world of Creative Destruction where everything is fully destructible! Creative.|893520|79",
"Shadowrun Returns|2013|Harebrained Schemes|RPG,Turn-Based,Strategy|PC,Mac,Linux|76|The unique cyberpunk-meets-fantasy world of Shadowrun has gained a huge cult following since.|234650|88",
"Dead Frontier 2|2019|Creaky Corpse Ltd|Horror,Co-op,TPS|PC||Survival horror MMO. As one of the few survivors of the outbreak, you must scratch a living out.|744900|70",
"Microsoft Flight Simulator X: Steam Edition|2014|Microsoft Game Studios|Simulation,Open World,Adventure|PC||Take to the skies in the World's favourite flight simulator! The multi award winning Microsoft.|314160|86",
"Life is Strange: Before the Storm|2017|Deck Nine|Adventure,Mystery,Action|PC,Mac,Linux|77|Life is Strange: Before the Storm is a new three part standalone story adventure set three.|554620|93",
"Assassin's Creed Syndicate|2015|Ubisoft Quebec, in collaboration with Ubisoft An|Open World,Action,Stealth|PC|74|London, 1868. Lead your underworld organization in the midst of the Industrial Revolution to.|368500|80",
"Awesomenauts|2012|Ronimo Games|MOBA,Platformer,Action|PC|78|Use your power, show your might! Play this Multiplayer Online Battle Arena (MOBA) game!.|204300|85",
"SoulWorker - Anime Action MMO|2018|Lion Games Co., Ltd.|MMO,RPG,Action|PC||SoulWorker, free-2-play anime action MMO, combines pacy combos with a real anime feel. You'll.|630100|79",
"Line of Sight|2017|BlackSpot Entertainment|FPS,Action,Shooter|PC||Fast paced FPS with high customizational freedom. From game mode customization to an in depth.|436520|60",
"HITMAN World of Assassination|2022|IO Interactive A/S|Stealth,Action,VR|PC,Mac|87|Enter the world of the ultimate assassin. HITMAN World of Assassination delivers the definitive.|1659040|86",
"Neon Abyss|2020|Veewo Games|Roguelike,Platformer,Shooter|PC||Neon Abyss is a frantic, roguelite action-platformer where you run 'n' gun your way into the.|788100|86",
"Tribes of Midgard|2021|Norsfell|Survival,Co-op,Action RPG|PC||A vibrant blend of survival and action RPG for 1-10 players! Craft legendary items, grow your.|858820|77",
"OUTRIDERS|2021|People Can Fly|Shooter,RPG,Co-op|PC||Outriders' brutal and bloody combat combines frenetic gunplay, violent powers and deep RPG.|680420|67",
"Warhammer 40,000: Chaos Gate - Daemonhunters|2022|Complex Games|Strategy,Tactics,Tactical|PC|81|Lead humanity's greatest weapon, the Grey Knights, in this fast-paced turn-based tactical RPG..|1611910|78",
"To the Moon|2012|Freebird Games|Adventure,RPG|PC,Mac,Linux|81|A story-driven experience about two doctors traversing backwards through a dying man's memories.|206440|96",
"Secret in Story|2017|Naivus Luo|Adventure,Visual Novel|PC,Mac||Accompanied by beautiful piano music, you begin to experience a wonderful love journey. There.||",
"Iron Snout|2016|SnoutUp|Fighting,Action,Survival|PC,Mac,Linux||Iron Snout is a fast, colorful and brutal fighting game in which you will be helping a piglet.|424280|98",
"Vindictus|2012|NEXON|Hack and Slash,MMO,Action|PC|76|Vindictus is an Action RPG that delivers the highest level of combat mechanics and high-quality.|212160|67",
"Hacknet|2015|Team Fractal Alligator|Simulation,Adventure,Detective|PC,Mac,Linux|82|Hacknet is an immersive, terminal-based hacking simulator for PC. Dive down a rabbit hoIe as.|365450|94",
"Ryse: Son of Rome|2014|Crytek|Hack and Slash,Action,Adventure|PC|61|'Ryse: Son of Rome' tells the story of Marius Titus, a young Roman soldier who witnesses the.|302510|87",
"Magicka 2|2015|Pieces Interactive|Co-op,Adventure,Action|PC,Mac,Linux||The world's most irreverent co-op action adventure returns! In the next chapter of Magicka.|238370|83",
"Monaco: What's Yours Is Mine|2013|Pocketwatch Games|Co-op,Stealth,Strategy|PC,Mac,Linux|83|Monaco: What's Yours Is Mine is a single player or co-op heist game. Assemble a crack team of.|113020|91",
"TCG Card Shop Simulator|2024|OPNeon Games|Simulation,Management,Card Game|PC||Open your own local game store. Stock shelves with the latest booster packs, or crack them and.|3070070|97",
"A Dance of Fire and Ice|2019|7th Beat Games|Rhythm,Arcade,Action|PC,Mac,Linux||A Dance of Fire and Ice is a strict rhythm game. Keep your focus as you guide two orbiting.|977950|94",
"Crucible Beta|2020|Relentless Studios|Action,Shooter,Hero Shooter|PC|56|Crucible is a free-to-play team-based PvP action shooter. Pick an alien, human, or robot hunter.|1057240|43",
"Glass Masquerade|2016|Onyx Lute|Puzzle|PC,Mac||Welcome to Glass Masquerade - an artistic puzzle game inspired by Art Deco & stained glass.|511470|97",
"Knight Online|2016|Noah System|MMO,Action,Open World|PC||The Great Battle between Karus and El Morad has arrived to Steam! Pledge allegiance to one of.|389430|50",
"ENDLESS Legend|2014|AMPLITUDE Studios|Strategy,Turn-Based,RPG|PC,Mac|82|ENDLESS Legend is a 4X turn-based fantasy strategy game by the creators of ENDLESS Space and.|289130|84",
"South Park: The Fractured But Whole|2017|Ubisoft San Francisco|RPG,Turn-Based,Adventure|PC||From the creators of South Park, Trey Parker and Matt Stone, comes South Park: The Fractured.|488790|85",
"GTFO|2021|10 Chambers|Co-op,Horror,FPS|PC|78|GTFO is a hardcore cooperative horror shooter that throws you from gripping suspense to.|493520|84",
"Stories: The Path of Destinies|2016|Spearhead Games|Adventure,RPG,Action|PC|74|Stories: The Path of Destinies is an Action RPG, an enchanted storybook filled with madcap.|439190|88",
"The Darkness II|2012|Digital Extremes|FPS,Action,Shooter|PC,Mac|77|An intense first person shooter that delivers a twisted and gripping narrative of tragedy.|67370|92",
"The Awesome Adventures of Captain Spirit|2018|DONTNOD Entertainment|Adventure,Point and Click,Action|PC|79|Have you ever dreamt of being a superhero? Meet Chris, a creative and imaginative 9 year old.|845070|93",
"Shadowverse CCG|2016|Cygames, Inc.|Card Game,Strategy,Turn-Based|PC,Mac||Four million battles every day. One Shadowverse. Japan's #1 strategic card game. Made by card.|453480|74",
"Naruto to Boruto: Shinobi Striker|2023|Soleil Ltd.|Action,Fighting,Co-op|PC||Battle as a team of 4 to compete against other teams online! Graphically, SHINOBI STRIKER is.|633230|84",
"Red Dead Online|2020|Rockstar Games|Open World,Action,Adventure|PC||Step into the vibrant, ever-evolving world of Red Dead Online and experience life in frontier.|1404210|83",
"ROUNDS|2021|Landfall|Fighting,Card Game,Roguelike|PC,Mac||Rounds is a 1v1 rogue-lite shooter where each round gets more intense. The losing player of.|1557740|95",
"Heart of a Warrior|2022|Techworld Communication|Action,Adventure,Action RPG|PC||Heart of a warrior is a RPG game in an open world where you play as Nahele, a young warrior of.|1619450|",
"One-armed robber|2023|Duhndal|Co-op,Action,Simulation|PC||One-armed robber is a chaotic first-person heist game that centers around a uniquely.|2551020|91",
"Ultimate Chicken Horse|2016|Clever Endeavour Games|Platformer,Co-op,Party|PC,Mac,Linux||Ultimate Chicken Horse is a party platformer game where you build the level as you play.|386940|96",
"Besiege|2020|Spiderling Studios|Simulation,Sandbox,Puzzle|PC,Mac,Linux||Besiege is a physics building game about constructing medieval machines to annihilate armies.|346010|95",
"Back 4 Blood|2021|Turtle Rock Studios|Co-op,FPS,Shooter|PC|77|Back 4 Blood is a thrilling cooperative first-person shooter from the creators of the.|924970|68",
"Romero's Aftermath|2015|Free Reign Entertainment|Survival,Open World,Action|PC||Play with your friends in a Zombie Infested World as you face the remnants of zombie hordes &.||49",
"ENDLESS Space - Definitive Edition|2012|AMPLITUDE Studios|Strategy,Turn-Based,Exploration|PC,Mac|77|ENDLESS Space is a turn-based 4X strategy game, covering the space colonization age in the.|208140|81",
"AirMech|2018|Carbon Games|Strategy,RTS,MOBA|PC||AirMech Strike is a fast paced Action-RTS game that can be played solo, coop, or competitively.|206500|84",
"Tropico 4|2011|Haemimont Games|City Builder,Simulation,Strategy|PC|78|The world is changing and Tropico is moving with the times - geographical powers rise and fall.|57690|92",
"Depth|2014|Ammobox Studios|Shooter,FPS,Horror|PC|65|Play as a shark or a diver in a dark aquatic world and overcome your enemies by employing.|274940|88",
"DDNet|2020|DDNet Team|Co-op,Platformer,Puzzle|PC,Mac,Linux||Want to play the hardest cooperative 2D platformer ever? Want to finish no map ever? Want to be.|412220|89",
"PowerWash Simulator|2022|FuturLab|Simulation,Sandbox,Co-op|PC||Release the Pressure with PowerWash Simulator! Wash away your worries with the soothing sounds.|1290000|97",
"Tiny Tina's Wonderlands|2022|Gearbox Software|Adventure,Shooter,RPG|PC||Embark on an epic adventure full of whimsy, wonder, and high-powered weaponry! Roll your own.|1286680|72",
"Gothic 3|2009|Piranha Bytes|RPG,Open World,Action|PC|63|A nameless hero becomes a legend! Myrtana, a world in upheaval: overrun by orcs from the dark.|39500|81",
"Football Manager 2019|2018|Sports Interactive|Simulation,Sports,Management|PC,Mac|86|Simulation gaming perfected. Create your unique footballing story by taking charge of the club.|872790|87",
"Crysis Warhead|2008|Crytek|FPS,Action,Shooter|PC|84|Pulse-racing new installment from 2007's PC Game of the Year*: Play as Sergeant Sykes and.|17330|86",
"Gorilla Tag|2023|Another Axiom Inc.|VR,Horror,Platformer|PC||Run, jump, and climb using only your hands. Play tag or infection with people online. Run away.|1533390|91",
"Darksiders III|2018|Gunfire Games|Hack and Slash,Action,Souls-like|PC|70|Return to an apocalyptic Earth in Darksiders III, a hack-n-slash Action Adventure where players.|606280|77",
"Total War: EMPIRE - Definitive Edition|2009|CREATIVE ASSEMBLY|Strategy,Tactical,RTS|PC,Mac,Linux|90|Command the seas, control the land, forge a new nation, and conquer the globe.|10500|91"
]);
