/* Postgame — game catalogue, part 1 of 5
   Row format: Title | Year | Developer | Genres | Platforms | Critic score | Blurb */
window.GAME_ROWS = (window.GAME_ROWS || []).concat([
"Elden Ring|2022|FromSoftware|Action RPG,Souls-like,Open World|PC,PS5,PS4,Xbox Series,Xbox One|96|A vast dark fantasy world co-written with George R. R. Martin.",
"The Legend of Zelda: Breath of the Wild|2017|Nintendo EPD|Action Adventure,Open World|Switch,Wii U|97|Hyrule reinvented as a physics playground of total freedom.",
"The Legend of Zelda: Tears of the Kingdom|2023|Nintendo EPD|Action Adventure,Open World|Switch|96|Build, fuse and fly across a Hyrule split into sky islands.",
"The Witcher 3: Wild Hunt|2015|CD Projekt Red|Action RPG,Open World|PC,PS5,PS4,Xbox Series,Xbox One,Switch|93|Geralt hunts monsters and worse people across a war-torn continent.",
"Red Dead Redemption 2|2018|Rockstar Games|Action Adventure,Open World|PC,PS4,Xbox One|97|The slow, gorgeous death of the American frontier.",
"Grand Theft Auto V|2013|Rockstar North|Action,Open World|PC,PS5,PS4,PS3,Xbox Series,Xbox One,Xbox 360|97|Three criminals, one satirical Los Angeles, endless chaos.",
"Minecraft|2011|Mojang|Sandbox,Survival|PC,Switch,PS4,Xbox One,Mobile|93|Dig, craft and build anything out of blocks.",
"Fortnite|2017|Epic Games|Battle Royale,Shooter|PC,PS5,Xbox Series,Switch,Mobile|81|Hundred-player battle royale with building and constant reinvention.",
"Baldur's Gate 3|2023|Larian Studios|RPG,Turn-Based|PC,PS5,Xbox Series,Mac|96|A tabletop epic where almost every wild idea works.",
"God of War|2018|Santa Monica Studio|Action Adventure|PS4,PC|94|Kratos and his son walk the nine realms of Norse myth.",
"God of War Ragnarok|2022|Santa Monica Studio|Action Adventure|PS5,PS4,PC|94|Fimbulwinter closes in as father and son face prophecy.",
"The Last of Us|2013|Naughty Dog|Action Adventure,Survival|PS3,PS4,PS5,PC|95|A smuggler escorts a girl across a ruined America.",
"The Last of Us Part II|2020|Naughty Dog|Action Adventure|PS4,PS5,PC|93|A brutal study of revenge told from both sides.",
"Marvel's Spider-Man|2018|Insomniac Games|Action Adventure,Open World|PS4,PC|87|The most joyful web-swinging ever put in a game.",
"Marvel's Spider-Man 2|2023|Insomniac Games|Action Adventure,Open World|PS5,PC|90|Two Spider-Men, one expanded New York, one hungry symbiote.",
"Horizon Zero Dawn|2017|Guerrilla Games|Action RPG,Open World|PS4,PC|89|Hunt robot dinosaurs in a lush post-collapse wilderness.",
"Horizon Forbidden West|2022|Guerrilla Games|Action RPG,Open World|PS5,PS4,PC|88|Aloy heads west into drowned cities and machine herds.",
"Ghost of Tsushima|2020|Sucker Punch Productions|Action Adventure,Open World|PS4,PS5,PC|83|A samurai becomes something dishonourable to save his island.",
"Ghost of Yotei|2025|Sucker Punch Productions|Action Adventure,Open World|PS5|87|A lone wanderer hunts six killers across northern Ezo.",
"Cyberpunk 2077|2020|CD Projekt Red|Action RPG,Open World|PC,PS5,Xbox Series|86|Night City chews up mercenaries with beautiful teeth.",
"Hades|2020|Supergiant Games|Roguelike,Action|PC,Switch,PS5,Xbox Series|93|Escape the underworld again and again, and love every run.",
"Hades II|2025|Supergiant Games|Roguelike,Action|PC,Switch,Switch 2,PS5|93|A witch of the underworld wages war on Time itself.",
"Hollow Knight|2017|Team Cherry|Metroidvania,Platformer|PC,Switch,PS4,Xbox One|90|A tiny knight explores a hauntingly beautiful ruined hive.",
"Hollow Knight: Silksong|2025|Team Cherry|Metroidvania,Platformer|PC,Switch,PS5,Xbox Series|92|Hornet climbs a hostile kingdom that wants her back.",
"Celeste|2018|Extremely OK Games|Platformer|PC,Switch,PS4,Xbox One|92|A precision climb up a mountain and through anxiety.",
"Stardew Valley|2016|ConcernedApe|Farming,Life Sim|PC,Switch,PS4,Xbox One,Mobile|89|Inherit a farm, befriend a town, never sleep again.",
"Undertale|2015|Toby Fox|RPG|PC,Switch,PS4,Vita|92|An RPG where you never have to kill anyone.",
"Dark Souls|2011|FromSoftware|Action RPG,Souls-like|PC,PS3,Xbox 360,Switch|89|Lordran interlocks like a puzzle box built of despair.",
"Dark Souls II|2014|FromSoftware|Action RPG,Souls-like|PC,PS4,PS3,Xbox 360|87|A stranger kingdom, harsher rules, still unmistakably Souls.",
"Dark Souls III|2016|FromSoftware|Action RPG,Souls-like|PC,PS4,Xbox One|89|The fading of the flame, fought at full speed.",
"Demon's Souls|2020|Bluepoint Games|Action RPG,Souls-like|PS5|92|The original Souls rebuilt in staggering detail.",
"Sekiro: Shadows Die Twice|2019|FromSoftware|Action,Souls-like|PC,PS4,Xbox One|90|Deflect everything. Sengoku swordplay as rhythm and nerve.",
"Bloodborne|2015|FromSoftware|Action RPG,Souls-like|PS4|92|Gothic horror that rewards aggression and punishes hesitation.",
"Armored Core VI: Fires of Rubicon|2023|FromSoftware|Action,Mech|PC,PS5,PS4,Xbox Series|86|Build a mech, then take apart everything in front of it.",
"Elden Ring Nightreign|2025|FromSoftware|Action RPG,Roguelike|PC,PS5,Xbox Series|78|Three-player runs through a shrinking, shifting Limveld.",
"Nier: Automata|2017|PlatinumGames|Action RPG|PC,PS4,Switch,Xbox One|88|Androids question their purpose in an endlessly replayed war.",
"Nier Replicant ver.1.22474487139|2021|Toylogic|Action RPG|PC,PS4,Xbox One|82|A brother's search for his sister turns very dark.",
"Persona 5 Royal|2019|Atlus|JRPG,Turn-Based|PS4,PS5,PC,Switch,Xbox Series|95|Steal corrupt hearts by night, survive school by day.",
"Persona 4 Golden|2012|Atlus|JRPG,Turn-Based|Vita,PC,Switch,PS4|93|A murder mystery inside a small town and a TV.",
"Persona 3 Reload|2024|Atlus|JRPG,Turn-Based|PC,PS5,Xbox Series,Switch 2|89|The Dark Hour rebuilt with modern style and polish.",
"Metaphor: ReFantazio|2024|Atlus|JRPG,Turn-Based|PC,PS5,PS4,Xbox Series|94|A fantasy election campaign fought with archetypes and ideals.",
"Final Fantasy VII|1997|Square|JRPG|PS1,PC,Switch,PS4|92|Cloud, Sephiroth, and the game that made JRPGs mainstream.",
"Final Fantasy VII Remake|2020|Square Enix|Action RPG|PS4,PS5,PC|87|Midgar expanded into a full, gorgeous, strange retelling.",
"Final Fantasy VII Rebirth|2024|Square Enix|Action RPG,Open World|PS5,PC|92|The world opens up and the party carries it.",
"Final Fantasy X|2001|Square|JRPG|PS2,PS4,Switch,PC|92|A pilgrimage toward a sacrifice nobody wants to name.",
"Final Fantasy IX|2000|Square|JRPG|PS1,PC,Switch,PS4|94|A storybook fantasy about mortality and belonging.",
"Final Fantasy VI|1994|Square|JRPG|SNES,PC,Switch,PS4|94|An ensemble opera that lets the villain win halfway.",
"Final Fantasy XIV|2013|Square Enix|MMO,RPG|PC,PS5,PS4,Mac,Xbox Series|83|An MMO saved by rebuilding it from scratch.",
"Final Fantasy XVI|2023|Square Enix|Action RPG|PS5,PC,Xbox Series|87|Political tragedy plus kaiju-scale summon battles.",
"Chrono Trigger|1995|Square|JRPG|SNES,DS,PC,Mobile|92|Time travel with no wasted minute anywhere in it.",
"Super Mario Odyssey|2017|Nintendo EPD|Platformer|Switch|97|Cappy lets Mario possess almost anything, everywhere.",
"Super Mario Galaxy|2007|Nintendo EPD|Platformer|Wii,Switch|97|Gravity-bending planet hopping with an unforgettable score.",
"Super Mario 64|1996|Nintendo EAD|Platformer|N64,DS,Switch|94|The blueprint every 3D platformer still copies.",
"Super Mario World|1990|Nintendo EAD|Platformer|SNES,Switch|94|Yoshi, capes, and a near-perfect world map.",
"Super Mario Bros. 3|1988|Nintendo EAD|Platformer|NES,SNES,Switch|97|Suits, ships and the peak of NES design.",
"Super Mario Bros.|1985|Nintendo|Platformer|NES,Switch|84|The game that taught the world how platformers work.",
"Super Mario Bros. Wonder|2023|Nintendo EPD|Platformer|Switch|92|2D Mario at its most playful and inventive in decades.",
"Mario Kart 8 Deluxe|2017|Nintendo EPD|Racing|Switch|92|The definitive kart racer, endlessly replayed on couches.",
"Mario Kart World|2025|Nintendo EPD|Racing,Open World|Switch 2|87|One connected world to drive between every track.",
"Super Smash Bros. Ultimate|2018|Bandai Namco Studios|Fighting,Party|Switch|93|Every fighter, every stage, one absurd celebration.",
"Animal Crossing: New Horizons|2020|Nintendo EPD|Life Sim|Switch|90|A deserted island slowly becomes home.",
"Splatoon 3|2022|Nintendo EPD|Shooter|Switch|83|Turf war shooting where covering ground beats killing.",
"Metroid Dread|2021|MercurySteam|Metroidvania|Switch|88|Samus hunted through corridors by relentless machines.",
"Super Metroid|1994|Nintendo R&D1|Metroidvania|SNES,Switch|96|Atmospheric, wordless mastery of exploration design.",
"Metroid Prime|2002|Retro Studios|FPS,Metroidvania|GameCube,Wii,Switch|97|Metroid in first person without losing an ounce of mood.",
"The Legend of Zelda: Ocarina of Time|1998|Nintendo EAD|Action Adventure|N64,3DS,Switch|99|The 3D adventure template, still astonishing.",
"The Legend of Zelda: Majora's Mask|2000|Nintendo EAD|Action Adventure|N64,3DS,Switch|95|Three days until the moon falls. Try again.",
"The Legend of Zelda: A Link to the Past|1991|Nintendo EAD|Action Adventure|SNES,GBA,Switch|95|Two worlds, one perfect 2D dungeon crawl.",
"The Legend of Zelda: The Wind Waker|2002|Nintendo EAD|Action Adventure|GameCube,Wii U|96|A great sea to sail and cel-shaded charm forever.",
"The Legend of Zelda: Twilight Princess|2006|Nintendo EAD|Action Adventure|Wii,GameCube,Wii U|95|Darker Hyrule, wolf form, superb dungeons.",
"The Legend of Zelda: Link's Awakening|1993|Nintendo EAD|Action Adventure|GB,Switch|90|A dream island packed into a handheld cartridge.",
"Half-Life|1998|Valve|FPS|PC|96|Black Mesa goes wrong and shooters never recover.",
"Half-Life 2|2004|Valve|FPS|PC,Xbox 360,PS3|96|Physics, gravity gun, and City 17's quiet dread.",
"Half-Life: Alyx|2020|Valve|FPS,VR|PC|93|The argument that VR can carry a real Valve game.",
"Portal|2007|Valve|Puzzle,FPS|PC,Xbox 360,PS3|90|Two portals, one deadpan AI, zero wasted minutes.",
"Portal 2|2011|Valve|Puzzle,FPS|PC,Xbox 360,PS3|95|Bigger, funnier, and co-op that ruins friendships.",
"Team Fortress 2|2007|Valve|FPS,Hero Shooter|PC|92|Nine classes, cartoon violence, immortal design.",
"Left 4 Dead 2|2009|Valve|FPS,Co-op,Horror|PC,Xbox 360|89|Four survivors, one director, endless zombie chaos.",
"Counter-Strike: Global Offensive|2012|Valve|FPS,Tactical|PC|83|The purest competitive shooter of its generation.",
"Counter-Strike 2|2023|Valve|FPS,Tactical|PC|80|Counter-Strike rebuilt on a new engine.",
"Dota 2|2013|Valve|MOBA|PC|90|The deepest and least forgiving MOBA there is.",
"League of Legends|2009|Riot Games|MOBA|PC,Mac|78|The MOBA that turned esports into an industry.",
"Valorant|2020|Riot Games|FPS,Tactical|PC|80|Tactical gunplay plus agent abilities, tuned razor sharp.",
"Overwatch|2016|Blizzard Entertainment|FPS,Hero Shooter|PC,PS4,Xbox One,Switch|91|Team shooting with personality in every hero.",
"World of Warcraft|2004|Blizzard Entertainment|MMO,RPG|PC,Mac|93|Azeroth, and two decades of people living in it.",
"Diablo II|2000|Blizzard North|Action RPG|PC,Mac|88|Click demons, chase loot, sleep never.",
"Diablo III|2012|Blizzard Entertainment|Action RPG|PC,PS4,Switch,Xbox One|88|Rough launch, magnificent long tail.",
"Diablo IV|2023|Blizzard Entertainment|Action RPG,Open World|PC,PS5,Xbox Series|86|Sanctuary as a gloomy shared open world.",
"StarCraft|1998|Blizzard Entertainment|RTS|PC,Mac|88|Three asymmetric races that defined real-time strategy.",
"StarCraft II: Wings of Liberty|2010|Blizzard Entertainment|RTS|PC,Mac|93|Immaculate strategy and a decade of pro play.",
"Hearthstone|2014|Blizzard Entertainment|Card Game|PC,Mobile|88|Card battling smoothed down to pure pleasure.",
"The Elder Scrolls V: Skyrim|2011|Bethesda Game Studios|Action RPG,Open World|PC,PS5,PS4,PS3,Switch,Xbox 360,Xbox One|94|A whole province to wander and mod forever.",
"The Elder Scrolls IV: Oblivion|2006|Bethesda Game Studios|Action RPG,Open World|PC,PS3,Xbox 360|94|Cyrodiil, gates to hell, and unmatched side quests.",
"The Elder Scrolls III: Morrowind|2002|Bethesda Game Studios|Action RPG,Open World|PC,Xbox|89|Alien fungal landscapes and no quest markers.",
"Fallout 3|2008|Bethesda Game Studios|Action RPG,Open World|PC,PS3,Xbox 360|91|Leave the vault, love the Capital Wasteland.",
"Fallout: New Vegas|2010|Obsidian Entertainment|Action RPG,Open World|PC,PS3,Xbox 360|84|The Mojave, four factions, and real consequences.",
"Fallout 4|2015|Bethesda Game Studios|Action RPG,Open World|PC,PS4,Xbox One|84|Shooting and settlement building in the Commonwealth.",
"Fallout 2|1998|Black Isle Studios|RPG,Turn-Based|PC|86|Bleak, funny, and enormously flexible.",
"Starfield|2023|Bethesda Game Studios|Action RPG,Open World|PC,Xbox Series|83|A thousand planets and a very long spacefaring RPG.",
"Doom (2016)|2016|id Software|FPS|PC,PS4,Xbox One,Switch|85|Rip and tear, restored to glory."
]);
