/* Postgame — game catalogue, part 5 of 5 */
window.GAME_ROWS = (window.GAME_ROWS || []).concat([
"Dishonored 2|2016|Arkane Studios|Immersive Sim,Stealth|PC,PS4,Xbox One|88|Two assassins and the best level in stealth games.",
"Deathloop|2021|Arkane Studios|Immersive Sim,FPS|PC,PS5,Xbox Series|88|One perfect day, learned murder by murder.",
"Prey|2017|Arkane Studios|Immersive Sim,FPS|PC,PS4,Xbox One|82|A space station where anything might be a mimic.",
"Deus Ex|2000|Ion Storm|Immersive Sim,FPS|PC,PS2,Mac|90|Conspiracy, augmentation, and a hundred ways through.",
"Deus Ex: Human Revolution|2011|Eidos Montreal|Immersive Sim,FPS|PC,PS3,Xbox 360,Wii U|90|Gold-tinted cyberpunk with real choice.",
"BioShock|2007|Irrational Games|FPS,Immersive Sim|PC,PS3,Xbox 360,Switch|96|Would you kindly visit Rapture.",
"BioShock 2|2010|2K Marin|FPS|PC,PS3,Xbox 360,Switch|88|A Big Daddy's return, mechanically the sharpest.",
"BioShock Infinite|2013|Irrational Games|FPS|PC,PS3,Xbox 360,Switch|94|Columbia in the clouds, and a lot of questions.",
"System Shock 2|1999|Irrational Games|Immersive Sim,FPS|PC|92|SHODAN, and the template for everything after.",
"Thief II: The Metal Age|2000|Looking Glass Studios|Stealth|PC|87|Pure light-and-shadow first-person thievery.",
"Hitman 3|2021|IO Interactive|Stealth,Action|PC,PS5,Switch,Xbox Series|87|Enormous sandbox murder puzzles, perfected.",
"Hitman: Blood Money|2006|IO Interactive|Stealth,Action|PC,PS2,Xbox 360|82|Accidents arranged with real craft.",
"Tom Clancy's Splinter Cell: Chaos Theory|2005|Ubisoft Montreal|Stealth|PC,PS2,Xbox,GameCube|93|Light, sound and Michael Ironside at their best.",
"Psychonauts|2005|Double Fine Productions|Platformer,Adventure|PC,Xbox,PS2|88|Platforming through wonderfully strange minds.",
"Psychonauts 2|2021|Double Fine Productions|Platformer,Adventure|PC,PS4,Xbox Series|89|Sixteen years later, and worth every one.",
"Grim Fandango|1998|LucasArts|Point and Click,Adventure|PC,PS4,Switch,Mobile|94|Film noir in the Land of the Dead.",
"The Secret of Monkey Island|1990|Lucasfilm Games|Point and Click,Adventure|PC,Mac,Switch|90|Insult swordfighting and perfect comic timing.",
"Day of the Tentacle|1993|LucasArts|Point and Click,Adventure|PC,PS4,Switch|91|Three eras, one time-travelling toilet.",
"Full Throttle|1995|LucasArts|Point and Click,Adventure|PC,PS4,Switch|88|Bikers, betrayal, and a great voice cast.",
"Myst|1993|Cyan|Puzzle,Adventure|PC,Mac,Switch,PS4|83|An island of machinery and silence.",
"Riven|1997|Cyan|Puzzle,Adventure|PC,Mac|82|The sequel that doubled down on the mystery.",
"The Witness|2016|Thekla|Puzzle|PC,PS4,Xbox One,Mobile|87|A hundred panel puzzles that teach without words.",
"Braid|2008|Number None|Puzzle,Platformer|PC,Xbox 360,PS3,Switch|93|Time manipulation as puzzle grammar.",
"Baba Is You|2019|Hempuli|Puzzle|PC,Switch,Mobile|87|Rewrite the rules that are written on the floor.",
"The Talos Principle|2014|Croteam|Puzzle,FPS|PC,PS4,Switch,Xbox Series|85|Philosophy between laser puzzles.",
"Return of the Obra Dinn|2018|Lucas Pope|Puzzle,Mystery|PC,PS4,Switch,Xbox One|89|Deduce sixty deaths from frozen moments.",
"Papers, Please|2013|Lucas Pope|Simulation,Puzzle|PC,Vita,Mobile|85|Glory to Arstotzka. Next.",
"The Stanley Parable|2013|Galactic Cafe|Adventure|PC,PS5,Switch,Xbox Series|88|A narrator you can disobey.",
"Firewatch|2016|Campo Santo|Adventure|PC,PS4,Switch,Xbox One|81|A fire lookout, a radio, and a Wyoming summer.",
"What Remains of Edith Finch|2017|Giant Sparrow|Adventure|PC,PS4,Switch,Xbox One|88|A family house of short, astonishing stories.",
"Gone Home|2013|Fullbright|Adventure|PC,PS4,Switch,Xbox One|86|An empty house that tells you everything.",
"Life is Strange|2015|Dontnod Entertainment|Adventure|PC,PS4,Switch,Xbox One|85|Rewind time in a small Oregon town.",
"Detroit: Become Human|2018|Quantic Dream|Adventure|PS4,PC|78|Branching android drama with enormous flowcharts.",
"Heavy Rain|2010|Quantic Dream|Adventure|PS3,PS4,PC|87|Four characters chasing the Origami Killer.",
"The Walking Dead|2012|Telltale Games|Adventure|PC,PS3,Xbox 360,Switch|89|Choices that genuinely hurt.",
"Citizen Sleeper|2022|Jump Over the Age|RPG|PC,Switch,PS5,Xbox Series|84|Dice, debt and rest on a decaying station.",
"Doki Doki Literature Club|2017|Team Salvato|Visual Novel|PC,Switch,PS4|81|Not the club it appears to be.",
"Danganronpa: Trigger Happy Havoc|2010|Spike Chunsoft|Visual Novel,Adventure|PSP,Vita,PC,Switch|80|Class trials with a murderous cartoon bear.",
"Zero Escape: Virtue's Last Reward|2012|Spike Chunsoft|Visual Novel,Puzzle|3DS,Vita,PC|84|Prisoner's dilemma escape rooms.",
"Steins;Gate|2009|5pb.|Visual Novel|PC,PS4,Switch,Vita|84|Microwave time travel and real consequences.",
"Tunic|2022|Andrew Shouldice|Adventure,Puzzle|PC,PS5,Switch,Xbox Series|85|A tiny fox and a manual you must decode.",
"Stray|2022|BlueTwelve Studio|Adventure|PC,PS5,Switch,Xbox Series|78|Be a cat in a neon walled city.",
"Kena: Bridge of Spirits|2021|Ember Lab|Action Adventure|PC,PS5,Xbox Series|81|Pixar-grade animation over solid combat.",
"Cult of the Lamb|2022|Massive Monster|Roguelike,Management|PC,PS5,Switch,Xbox Series|82|Run a cult, then go clear a dungeon.",
"Blasphemous|2019|The Game Kitchen|Metroidvania,Action|PC,PS4,Switch,Xbox One|76|Baroque religious horror pixel art.",
"Nine Sols|2024|Red Candle Games|Metroidvania,Action|PC,PS5,Switch,Xbox Series|87|Taopunk deflection combat with gorgeous art.",
"Rain World|2017|Videocult|Platformer,Survival|PC,PS4,Switch,Xbox One|76|A brutal ecosystem that does not care about you.",
"Cave Story|2004|Studio Pixel|Metroidvania,Platformer|PC,Switch,3DS,Wii|89|One developer, five years, a masterpiece.",
"Super Meat Boy|2010|Team Meat|Platformer|PC,Xbox 360,Switch,PS4|90|Instant restarts and enormous difficulty.",
"Geometry Dash|2013|RobTop Games|Platformer,Rhythm|Mobile,PC|80|One button, impossible timing, endless levels.",
"Crypt of the NecroDancer|2015|Brace Yourself Games|Rhythm,Roguelike|PC,Switch,PS4,Mobile|85|Move to the beat or die to it.",
"Beat Saber|2018|Beat Games|Rhythm,VR|PC,PS4|89|Lightsabers, cubes, actual exercise.",
"Guitar Hero III: Legends of Rock|2007|Neversoft|Rhythm|PS3,Xbox 360,Wii,PC|86|Plastic guitars in every living room.",
"Rock Band|2007|Harmonix|Rhythm|PS3,Xbox 360,Wii|92|A whole band on the carpet.",
"Tony Hawk's Pro Skater 2|2000|Neversoft|Sports|PS1,PC,Dreamcast|98|Two minutes, one combo, perfect soundtrack.",
"Skate 3|2010|EA Black Box|Sports|PS3,Xbox 360|80|Flick-stick skating and glorious physics bugs.",
"SSX 3|2003|EA Canada|Sports,Racing|PS2,Xbox,GameCube|93|One mountain, top to bottom, huge air.",
"NBA Jam|1993|Midway|Sports|Arcade,SNES,Genesis|89|He's on fire. Boomshakalaka.",
"NBA 2K25|2024|Visual Concepts|Sports|PC,PS5,Switch,Xbox Series|80|The basketball sim standard, microtransactions included.",
"EA Sports FC 25|2024|EA Vancouver|Sports|PC,PS5,Switch,Xbox Series|75|Football's biggest annual release, renamed.",
"FIFA 18|2017|EA Vancouver|Sports|PC,PS4,Switch,Xbox One|83|The Journey mode and peak FIFA presentation.",
"Madden NFL 25|2024|EA Tiburon|Sports|PC,PS5,Xbox Series|77|American football's only game in town.",
"MLB The Show 24|2024|San Diego Studio|Sports|PS5,Switch,Xbox Series|84|The best-feeling baseball on any platform.",
"Forza Horizon 4|2018|Playground Games|Racing,Open World|PC,Xbox One|92|Britain, four seasons, endless car joy.",
"Forza Horizon 5|2021|Playground Games|Racing,Open World|PC,PS5,Xbox Series|92|Mexico as the prettiest playground in racing.",
"Need for Speed: Most Wanted|2005|EA Black Box|Racing|PS2,Xbox 360,PC|83|Police chases and a very grey filter.",
"Burnout 3: Takedown|2004|Criterion Games|Racing|PS2,Xbox|94|Crashing as a legitimate strategy.",
"Mario Kart Wii|2008|Nintendo EAD|Racing|Wii|82|Motion steering and the bike meta.",
"Dirt Rally 2.0|2019|Codemasters|Racing,Simulation|PC,PS4,Xbox One|85|Rally driving that demands total respect.",
"F1 24|2024|Codemasters|Racing,Simulation|PC,PS5,Xbox Series|78|Formula One careers in fine detail.",
"Pac-Man|1980|Namco|Arcade,Maze|Arcade,Multi|92|Four ghosts and a cultural icon.",
"Space Invaders|1978|Taito|Arcade,Shoot 'em up|Arcade,Multi|90|The row of aliens that started an industry.",
"Donkey Kong|1981|Nintendo|Arcade,Platformer|Arcade,NES,Switch|88|A carpenter, a gorilla, four girders.",
"Mortal Kombat|1992|Midway|Fighting|Arcade,SNES,Genesis|85|Digitised fighters and a moral panic.",
"Tekken 3|1997|Namco|Fighting|Arcade,PS1|96|The 3D fighter everyone still measures against.",
"Tekken 8|2024|Bandai Namco Studios|Fighting|PC,PS5,Xbox Series|90|Aggressive heat systems and gorgeous fighters.",
"Mortal Kombat 11|2019|NetherRealm Studios|Fighting|PC,PS4,Switch,Xbox One|84|Brutal fatalities and a great story mode.",
"Mortal Kombat 1|2023|NetherRealm Studios|Fighting|PC,PS5,Switch,Xbox Series|82|A rebooted timeline with kameo fighters.",
"Injustice 2|2017|NetherRealm Studios|Fighting|PC,PS4,Xbox One|88|DC heroes with gear and a real story.",
"Guilty Gear Strive|2021|Arc System Works|Fighting|PC,PS5,Switch,Xbox Series|87|The most beautiful fighting game made.",
"Dragon Ball FighterZ|2018|Arc System Works|Fighting|PC,PS4,Switch,Xbox One|87|Anime made playable, frame for frame.",
"Super Smash Bros. Melee|2001|HAL Laboratory|Fighting,Party|GameCube|92|Twenty-plus years of tournament devotion.",
"Crash Bandicoot N. Sane Trilogy|2017|Vicarious Visions|Platformer|PC,PS4,Switch,Xbox One|80|Three brutal classics, beautifully rebuilt.",
"Spyro Reignited Trilogy|2018|Toys for Bob|Platformer|PC,PS4,Switch,Xbox One|83|Purple dragon gliding, gorgeously remade.",
"LittleBigPlanet|2008|Media Molecule|Platformer,Sandbox|PS3,PSP|95|Play, create, share, in sackcloth.",
"Katamari Damacy|2004|Namco|Puzzle,Action|PS2,PC,Switch|86|Roll a ball until it swallows the world.",
"Viva Pinata|2006|Rare|Simulation,Sandbox|Xbox 360,PC|84|Garden management with paper animals.",
"Sea of Thieves|2018|Rare|Adventure,Multiplayer|PC,PS5,Xbox Series|69|The best pirate ship simulator, with strangers.",
"Fable|2004|Big Blue Box|Action RPG|Xbox,PC|85|Grow up, get famous, choose a haircut.",
"Fable II|2008|Lionhead Studios|Action RPG|Xbox 360|89|Albion, a dog, and warm British comedy.",
"Black & White|2001|Lionhead Studios|Simulation,Strategy|PC,Mac|90|Be a god, raise a creature, judge nothing.",
"Warcraft III: Reign of Chaos|2002|Blizzard Entertainment|RTS|PC,Mac|92|Heroes, creeps, and the birth of the MOBA.",
"Warhammer 40,000: Space Marine 2|2024|Saber Interactive|TPS,Action|PC,PS5,Xbox Series|80|Enormous hordes and satisfying chainsword work.",
"Black Myth: Wukong|2024|Game Science|Action RPG|PC,PS5,Xbox Series|81|Chinese mythology as a spectacular action game.",
"Lies of P|2023|Neowiz Games|Souls-like,Action RPG|PC,PS5,Switch,Xbox Series|82|Pinocchio, belle epoque, excellent parries.",
"Nioh 2|2020|Team Ninja|Souls-like,Action RPG|PC,PS5,PS4|85|Yokai combat with dizzying build depth.",
"Bayonetta|2009|PlatinumGames|Action,Hack and Slash|PS3,Xbox 360,PC,Switch|90|Witch time, absurd style, flawless combat.",
"Metal Gear Rising: Revengeance|2013|PlatinumGames|Action,Hack and Slash|PS3,Xbox 360,PC|82|Cut anything, memes forever.",
"The Witcher 2: Assassins of Kings|2011|CD Projekt Red|Action RPG|PC,Xbox 360|88|Dense political fantasy with branching acts.",
"Deltarune|2025|Toby Fox|RPG,Turn-Based|PC,Switch,PS5,Switch 2|91|A strange, funny, musical parallel to Undertale."
]);
