/* Postgame - game catalogue, part 19
   Harvested from Steam. Rows carry two extra fields: the Steam app id
   (for the 600x900 capsule) and the percentage of Steam reviews that
   are positive. */
window.GAME_ROWS = (window.GAME_ROWS || []).concat([
"Last Oasis|2020|Donkey Crew|MMO,Survival,Open World|PC||Nomadic Survival MMO. Build wooden walking machines to travel to new lands. Create clans and.|903950|62",
"Murdered: Soul Suspect|2014|Airtight Games|Detective,Adventure,Mystery|PC|59|MURDERED: SOUL SUSPECT takes players into a whole new realm of mystery where the case is.||86",
"Farming Simulator 25|2024|GIANTS Software|Simulation,Farming,Immersive Sim|PC,Mac||Farming Simulator 25 invites you to join the rewarding farm life, single-handedly or.|2300320|84",
"VTube Studio|2021|DenchiSoft|Co-op,Horror,Souls-like|PC,Mac||VTube Studio is all you'll ever need to become a Live2D VTuber, with innovative features such.|1325860|93",
"Marvel's Avengers - The Definitive Edition|2020|Crystal Dynamics|Action,Adventure,RPG|PC||Assemble your team of Earth's Mightiest Heroes, embrace your powers, and live your Super Hero.|997070|67",
"Dawn of Man|2019|Madruga Works|City Builder,Colony Sim,Survival|PC,Mac||Command a settlement of ancient humans, guide them through the ages in their struggle for.|858810|87",
"World of Tanks|2021|Wargaming Group Limited|Action,Tactical,MMO|PC|80|World of Tanks is a tactical action game with very different gameplay depending on the vehicle.|1407200|83",
"Contagion|2013|Monochrome, Inc|Co-op,Horror,FPS|PC|62|Contagion isn't your average Zombie Shooter but instead takes a more realistic and different.|238430|73",
"Jurassic World Evolution 2|2021|Frontier Developments|Simulation,Management,Sandbox|PC|76|Jurassic World Evolution 2 is the much-anticipated sequel to Frontier's highly successful.|1244460|90",
"RetroArch|2022|Libretro|Arcade,Simulation,Co-op|PC,Mac,Linux||RetroArch is an open source and cross platform frontend/framework for emulators, game engines.|1118310|90",
"XCOM: Chimera Squad|2020|Firaxis Games|Strategy,Tactics,Turn-Based|PC||XCOM: Chimera Squad delivers an all-new story and turn-based tactical combat experience in the.|882100|72",
"Gotham City Impostors Free to Play|2012|Monolith Productions, Inc.|Action,FPS,Shooter|PC||Gotham City Impostors is now Free to Play! Join the Batman helpers or junior Jokerz in the.||85",
"Battlerite Royale|2019|Stunlock Studios|Battle Royale,MOBA,MMO|PC||Explore the fantastical Talon Island in a thrilling fusion between a MOBA and Battle Royale.|879160|74",
"Hydroneer|2020|Foulball Hangover|Simulation,Sandbox,Co-op|PC||Hydroneer is a mining and base building sandbox. Dig for gold and other resources to turn a.|1106840|87",
"Potion Craft: Alchemist Simulator|2022|niceplay games|Simulation,Management,Life Sim|PC||Potion Craft is an alchemist simulator where you physically interact with your tools and.|1210320|92",
"Islands of Nyne: Battle Royale|2018|Define Human Studios|Battle Royale,FPS,Action|PC||Drop into massive, alien-built arenas and begin the frantic search for weapons and gear - all.||51",
"Ranch Simulator: Build, Hunt, Farm|2023|Toxic Dog|Simulation,Co-op,Open World|PC||Builder. Farmer. Hunter. Trader. Ranching certainly isn't your average job. Think you have the.|1119730|80",
"Slime Rancher 2|2025|Monomi Park|Open World,Adventure,Simulation|PC||Continue the adventures of Beatrix LeBeau as she journeys across the Slime Sea to Rainbow.|1657630|94",
"Kingdom Rush - Tower Defense|2014|Ironhide Game Studio|Tower Defence,Strategy,Tactical|PC,Mac,Linux||Get ready for an epic journey to defend your kingdom against hordes of orcs, trolls, evil.|246420|97",
"Nobody - The Turnaround|2022|U.Ground Game Studio|Life Sim,Simulation,Survival|PC,Mac||Nobody - The Turnaround is a life simulator set in a parallel world that echoes modern society..|1810580|60",
"Marvel's Spider-Man: Miles Morales|2022|Insomniac Games|Open World,Action,Adventure|PC||After the events of Marvel's Spider-Man Remastered, teenage Miles Morales is adjusting to his.|1817190|93",
"Men of War: Assault Squad 2|2014|Digitalmindsoft|Strategy,RTS,Simulation|PC|68|Men of War: Assault Squad 2 expands the real-time tactics series with new skirmish missions.|244450|91",
"Easy eSports|2015|EasyAntiCheat Ltd|Action|PC||Keeping games fun! Play fair with the leading third-party anti-cheat client for Counter-Strike.||81",
"Beyond: Two Souls|2020|Quantic Dream|Adventure,Co-op,Horror|PC|76|A unique psychological action thriller delivered by A-list Hollywood performances by Elliot.|960990|88",
"Dead Island: Riptide Definitive Edition|2016|Techland|Co-op,Open World,Action|PC,Linux||Welcome to the zombie apocalypse experience of a lifetime - more beautiful than ever. Caught in.|383180|71",
"Call of Duty: Advanced Warfare - Gold Edition|2014|Sledgehammer Games|FPS,Action,Shooter|PC|78|Call of Duty: Advanced Warfare envisions a powerful future, where both technology and tactics.|209650|62",
"Forager|2019|HopFrog|Survival,Farming,Sandbox|PC|78|The highly popular and quirky idle game that you want to actively keep playing. Explore, craft.|751780|90",
"Darwin Project|2020|Scavengers Studio|Battle Royale,Survival,Action|PC|74|In Darwin Project, ten inmates must survive the elements, track each other, fight, craft tools.|544920|81",
"Galactic Civilizations III|2015|Stardock Entertainment|Strategy,Sandbox,Turn-Based|PC|81|Build a civilization that will stand the test of time in the largest space-based strategy game.|226860|77",
"Dread Hunger|2022|Dread Hunger Team|Survival,Social Deduction,Co-op|PC||A game of survival and betrayal. Eight Explorers path their ship through the unforgiving.|1418630|60",
"LoveChoice|2021|Akaba Studio|Adventure,Visual Novel,Simulation|PC,Mac||What is love? We try to answer that with this game. The game encourages people to have a warm.|939400|93",
"Deep Rock Galactic: Survivor|2025|Funday Games|Roguelike,Shoot 'em up,Action|PC||DEEP ROCK GALACTIC: SURVIVOR is a single player survivor-like auto-shooter. Take on hordes of.|2321470|87",
"Satellite Reign|2015|5 Lives Studios|Strategy,Action,Tactical|PC,Mac,Linux|75|Satellite Reign is a real-time, class-based strategy game, set in an open-world cyberpunk city..|268870|71",
"CARRION|2020|Phobia Game Studio|Action,Horror,Metroidvania|PC,Mac,Linux|75|CARRION is a reverse horror game in which you assume the role of an amorphous creature of.|953490|95",
"Scorn|2022|Ebb Software|Horror,Puzzle,Adventure|PC||Scorn is an atmospheric first-person horror adventure game set in a nightmarish universe of odd.|698670|77",
"EVERSPACE 2|2023|ROCKFISH Games|Shooter,Exploration,Open World|PC,Mac|81|EVERSPACE 2 is a fast-paced single-player spaceship shooter with exploration in space and on.|1128920|87",
"Swords of Legends Online|2021|Wangyuan Shengtang Entertainment Technology CO.|MMO,Open World,Action RPG|PC||Swords of Legends Online is an action MMORPG set in a breathtaking fantasy world with.|1418100|67",
"Gems of War - Puzzle RPG|2014|Infinity Plus 2|Puzzle,Card Game,Strategy|PC||Gems of War is a Match-3 RPG from the original creators of Puzzle Quest! Start your RPG journey.|329110|80",
"The Wind Road|2020|甘肃嘉元数字科技有限公司|RPG,Action,Adventure|PC||The Wind Road is an ARPG real-time combat game, constructing a martial-arts world based on the.|1264670|69",
"Deponia|2012|Daedalic Entertainment|Adventure,Point and Click,Puzzle|PC,Mac,Linux|74|In Deponia, the world has degenerated into a vast garbage dump, in which the crotchety Rufus.|214340|87",
"Hell Yeah! Wrath of the Dead Rabbit|2012|Arkedo|Platformer,Action,Metroidvania|PC|64|A crazy action-adventure platformer... In Hell.|205230|85",
"Pirates Vikings & Knights II|2010|Octoshark Studios|Action,FPS,Hack and Slash|PC,Linux||Step into the ultimate three-way war for honor, glory, and gold! This beloved community-driven.|17570|88",
"Shop Titans|2020|Kabam Games, Inc.|Simulation,Management,RPG|PC||Shop Titans is the ultimate RPG shopkeeper simulation. Craft powerful equipment, stock your.|1258080|78",
"Realm Grinder|2017|Divine Games|Strategy,City Builder,Simulation|PC,Mac||Grow your realm, build alliances, and explore one of the deepest idle RPGs ever!|610080|87",
"Cursed Dawn|2025|Cursed Studios|FPS,Co-op,Shooter|PC||Cursed Dawn is a wave survival FPS featuring complex maps packed with secrets, dynamic spawns.|2713550|",
"Skater XL - The Ultimate Skateboarding Game|2020|Easy Day Studios Pty Ltd|Sports,Sandbox,Co-op|PC|56|Experience unparalleled board control and responsiveness while you skate iconic real-world.|962730|86",
"Anno 2205|2015|Blue Byte|City Builder,Strategy,Simulation|PC|72|In Anno 2205, you join humankind's next step into the future with the promise to build a.|375910|70",
"Need for Speed Rivals|2020|Criterion Games|Racing,Open World,Action|PC|76|Erase the line between single player and multiplayer in this street-racing rivalry between Cops.|1262600|75",
"My Singing Monsters|2021|Big Blue Bubble|Simulation,Farming,Colony Sim|PC||Dive into the Musical World of My Singing Monsters! Breed them, feed them, listen to them sing!.|1419170|94",
"Risk of Rain Returns|2023|Hopoo Games|Co-op,Shooter,Action|PC||Carefully designed, beautifully remastered, and loaded with new ways to play-Risk of Rain is.|1337520|90",
"Your Only Move Is HUSTLE|2023|Ivy Sly|Fighting,Strategy,Action|PC,Linux||Master your technique, execute flashy combos, and outsmart opponents across the world.|2212330|96",
"F1 2021|2021|Codemasters|Racing,Sports,Immersive Sim|PC|86|Every story has a beginning in F1 2021, the official videogame of the 2021 FIA FORMULA ONE.|1134570|86",
"Dinkum|2025|James Bendon|Survival,Farming,Life Sim|PC||Dinkum is a survival life simulation game set on an island inspired by the rugged Australian.|1062520|92",
"Gujian3|2018|上海烛龙信息科技有限公司|RPG,Adventure,Action RPG|PC||Gujian 3 is a mass 3D single-person RPG developed by Aurogon Info & Tech (Shanghai), a.|994280|86",
"Star Wars: Squadrons|2020|MOTIVE|VR,Action,Simulation|PC|79|Master the art of starfighter combat in the authentic piloting experience STAR WARS.|1222730|66",
"Sniper Ghost Warrior 3|2017|CI Games|Open World,FPS,Stealth|PC||Go behind enemy lines with the ultimate modern military shooter. Play as an American sniper.|368070|67",
"Volcano Princess|2023|养蛋人 Egg Hatcher|Life Sim,RPG,Simulation|PC||Prepare the next monarch by finding her hobbies, training her for battle, and befriending the.|1669980|98",
"Dead Space 2|2011|Visceral Games|Horror,TPS,Shooter|PC|87|Three years after the Necromorph infestation aboard the USS Ishimura, Isaac Clarke awakens from.|47780|94",
"ROMANCE OF THE THREE KINGDOMS XIV|2020|KOEI TECMO GAMES CO., LTD.|Tactics,Immersive Sim,Strategy|PC||Triumph over the land, take charge of the fate of China! Conquer territories and fly your.|872410|62",
"Tropico 3|2009|Haemimont Games|Simulation,Strategy,City Builder|PC|79|Become the dictator of a remote island during the Cold War. Charm, persuade, intimidate.|23490|89",
"Just Shapes & Beats|2018|Berzerk Studio|Rhythm,Shoot 'em up,Action|PC,Mac,Linux||Just Shapes & Beats is a chaotic co-op musical bullet-hell based on three simple things: avoid.|531510|98",
"My Beautiful Paper Smile|2021|Two Star Games|Horror,Adventure,Puzzle|PC||Welcome, child, to your new home. Here you shall learn the art of perfection. Here you shall.|1036700|85",
"Legion TD 2 - Multiplayer Tower Defense|2021|AutoAttack Games|Tower Defence,Auto Battler,Strategy|PC,Mac||An infinitely replayable multiplayer and single-player tower defense. Defend against waves of.|469600|86",
"Teeworlds|2015|Teeworlds Team|Action,Platformer,Shooter|PC,Mac,Linux||Teeworlds is a free online multiplayer game, available for all major operating systems. Battle.|380840|88",
"Need for Speed Undercover|2008|EA Black Box|Racing,Open World,Action|PC|65|You never thought it would turn out like this. An all-out chase where you're the hunted. And.|17430|75",
"SpaceChem|2011|Zachtronics|Puzzle,Simulation,Strategy|PC,Mac,Linux|84|Zachtronics is back with an ambitious new design-based puzzle game. Take on the role of a.|92800|92",
"Dust: An Elysian Tail|2013|Humble Hearts LLC|Action,Platformer,Metroidvania|PC,Mac,Linux||Immerse yourself in a gorgeous hand-painted world on a search for your true identity. As the.|236090|95",
"Deus Ex: Invisible War|2007|Ion Storm|Action,FPS,RPG|PC|80|Approximately 20 years after Deus Ex, the world is only beginning to recover from a.|6920|58",
"Marauders|2022|Small Impact Games|Shooter,FPS,Open World|PC||Marauders is a tactical first-person multiplayer looter shooter set in a sci-fi universe. As a.|1789480|71",
"Terraformers|2023|Asteroid Lab|Simulation,Survival,Roguelike|PC,Mac,Linux|80|Terraform Mars in this turn-based colony builder and resource management game with roguelike.|1244800|88",
"Sniper: Ghost Warrior|2010|City Interactive|Action,FPS,Stealth|PC|55|As a Ghost Warrior, an elite sniper in a highly trained special ops unit, your unique skills in.|34830|58",
"Golf It!|2023|Perfuse Entertainment|Sports,Co-op,Simulation|PC,Mac||Embark on an exciting journey with Golf It! Seize your putter, rally your friends, and immerse.|571740|91",
"Brick-Force|2014|Exe Games Inc.|FPS,Shooter,Action|PC||Brick-Force is a sandbox shooter that lets you BUILD your own battlefields, SHARE them with.||42",
"OneShot|2016|Future Cat LLC|Adventure,Puzzle,Exploration|PC,Mac,Linux|80|OneShot is a surreal top down Puzzle/Adventure game with unique gameplay capabilities. You are.|420530|98",
"Cortex Command|2012|Data Realms|Strategy,Action,Sandbox|PC,Mac|44|Choose between different factions, with their own set of expendable soldiers, mechas, and.|209670|72",
"House Party|2022|Eek! Games, LLC|Simulation,Sandbox,Adventure|PC||House Party is an edgy comedy adventure game inspired by classic comedies of the '90s. Every.|611790|86",
"The Incredible Adventures of Van Helsing|2013|NeocoreGames|RPG,Hack and Slash,Action RPG|PC|72|Put on your wide-brimmed hat, grab your weapons and embark on an incredible adventure in the.|215530|83",
"Warhammer: End Times - Vermintide|2015|Fatshark|Action,Co-op,FPS|PC|79|Vermintide is an epic co-operative action combat adventure set in the End Times of the iconic.|235540|80",
"Clone Drone in the Danger Zone|2021|Doborog Games|Action,Fighting,Co-op|PC,Mac|82|Clone Drone in the Danger Zone is a robot voxel slice-em-up where any part of your body can be.|597170|97",
"Sword Art Online: Fatal Bullet|2018|Dimps Corporation|RPG,Action,JRPG|PC|61|Experience an original story where you are the protagonist in the world of Gun Gale Online..|626690|79",
"Overcast - Walden and the Werewolf|2014|Microblast Games|Horror,Adventure,Action|PC||A mysterious creature has destroyed a village located near Walden's cabin, killing every person.||61",
"Songs of Conquest|2024|Lavapotion|Tactics,Strategy,Tactical|PC,Mac||Raise mighty armies, wield ancient magic and forge an empire. This turn-based strategy.|867210|86",
"LOCKDOWN Protocol|2025|Mirage Creative Lab|Social Deduction,Action,Puzzle|PC||A first person social deduction game, combining real time action and communication, playable up.|2780980|88",
"WWII Online|2023|Cornered Rat Software|FPS,Shooter,Action|PC,Mac|73|WWII Online is a massive, persistent free-to-play MMO FPS driven entirely by players. Fight as.|251950|50",
"Final Fantasy XII THE ZODIAC AGE|2018|Square Enix|RPG,JRPG,Adventure|PC||FINAL FANTASY XII THE ZODIAC AGE - This revered classic returns, now fully remastered for the.|595520|90",
"Transport Fever 2|2019|Urban Games|Simulation,Strategy,Management|PC,Mac,Linux|76|The classic transport simulation genre has a new gold standard with Transport Fever 2. Discover.|1066780|90",
"Will To Live Online|2018|AlphaSoft LLC|Survival,Open World,FPS|PC||Will To Live is a MMORPG-shooter whose action takes place in a severe post-apocalyptic world..|707010|70",
"Zombie Army Trilogy|2015|Rebellion|Action,Co-op,TPS|PC|72|The cult horror shooter series comes to an apocalyptic conclusion with an epic new third.|301640|86",
"Ragnarok Online|2013|Gravity Interactive|RPG,MMO,Adventure|PC|79|In the world of Rune Midgard, it was a time of strife between the Gods, Humans and.|215100|72",
"Make it indie!|2015|Sometimes You|Adventure,Simulation|PC,Mac,Linux||Claw your way through the abyss of the mind and survive the horrors that stalk you as you.|357900|46",
"Bombergrounds: Reborn|2022|Gigantic Duck Games|Battle Royale,Co-op,Arcade|PC,Mac||BOMBERGROUNDS: Immerse in a free-to-play massive multiplayer action-packed arena inspired by.|1104450|86",
"F1 2020|2020|Codemasters|Racing,Simulation,Sports|PC||F1 2020 allows you to create your F1 team for the very first time and race alongside the.|1080110|94",
"RADical ROACH Remastered|2014|Dried Lemons|Action,Adventure,Simulation|PC||RADical ROACH is a fast paced shoot em' up, set minutes after nuclear hell falls from the sky.|301750|57",
"Door Kickers: Action Squad|2018|PixelShard|Platformer,Co-op,Action|PC||Rescue hostages, disarm bombs and save the day in this old school, side-scroller action game.|686200|95",
"Poker Night 2|2013|Telltale Games|Card Game,Strategy,Sports|PC,Mac|75|The chips are down and the ante is up in this sentence already bursting with poker clichés!.||88",
"Tails Noir|2021|Eggnut|Detective,Visual Novel,Adventure|PC,Mac||Tails Noir is a post-noir narrative adventure. Become raccoon private eye Howard Lotor and.|865610|67",
"Double Action: Boogaloo|2014|Double Action Factory|Action,Shooter,TPS|PC||Double Action is a free stylish multiplayer game about diving, flipping, and sliding your way.|317360|93",
"Pixel Sketch|2017|mimicryTeam|Arcade,Simulation,Puzzle|PC,Mac||Become the best painter in the universe in this colorful online game!|648120|73",
"Call of Cthulhu|2018|Cyanide Studio|Horror,Adventure,Detective|PC||1924. Private Investigator Pierce is sent to look into the tragic death of the Hawkins family..|399810|79",
"Evil West|2022|Flying Wild Hog|Beat 'em up,Action Adventure,Co-op|PC||A dark menace consumes the Old West. In solo or coop, fight with style in visceral, explosive.|1065310|74"
]);
