/* Postgame — game catalogue, part 2 of 5 */
window.GAME_ROWS = (window.GAME_ROWS || []).concat([
"Doom Eternal|2020|id Software|FPS|PC,PS4,Xbox One,Switch|88|Combat as a puzzle you solve with a chainsaw.",
"Doom (1993)|1993|id Software|FPS|PC|94|The shooter that lit the fuse for everything.",
"Doom: The Dark Ages|2025|id Software|FPS|PC,PS5,Xbox Series|86|A medieval Slayer prequel built around shield and siege.",
"Quake|1996|id Software|FPS|PC|94|True 3D, rocket jumps, and modding culture.",
"Wolfenstein: The New Order|2014|MachineGames|FPS|PC,PS4,Xbox One|81|Alternate-history Nazi killing with a real story.",
"Call of Duty 4: Modern Warfare|2007|Infinity Ward|FPS|PC,PS3,Xbox 360|94|The campaign and multiplayer that reset the genre.",
"Call of Duty: Modern Warfare 2|2009|Infinity Ward|FPS|PC,PS3,Xbox 360|94|Blockbuster set pieces at absurd velocity.",
"Call of Duty: Black Ops|2010|Treyarch|FPS|PC,PS3,Xbox 360|87|Cold War conspiracy plus the birth of Zombies.",
"Call of Duty: Black Ops II|2012|Treyarch|FPS|PC,PS3,Xbox 360,Wii U|83|Branching near-future campaign and peak multiplayer.",
"Call of Duty: Warzone|2020|Raven Software|Battle Royale,FPS|PC,PS5,Xbox Series|76|Free-to-play battle royale at Call of Duty pace.",
"Call of Duty: Black Ops 6|2024|Treyarch|FPS|PC,PS5,Xbox Series|83|Omnimovement makes every gunfight faster.",
"Battlefield 1|2016|DICE|FPS|PC,PS4,Xbox One|88|World War I as spectacle and mud.",
"Battlefield 3|2011|DICE|FPS|PC,PS3,Xbox 360|89|Large-scale destruction and vehicle warfare done right.",
"Battlefield 6|2025|Battlefield Studios|FPS|PC,PS5,Xbox Series|82|A return to grounded, destructible all-out war.",
"Apex Legends|2019|Respawn Entertainment|Battle Royale,Hero Shooter|PC,PS5,Xbox Series,Switch|89|Movement, pinging and squads that click.",
"Titanfall 2|2016|Respawn Entertainment|FPS|PC,PS4,Xbox One|86|Wall-running plus mechs plus the best FPS campaign.",
"Destiny 2|2017|Bungie|FPS,MMO|PC,PS5,Xbox Series|83|Shooting that feels incredible, forever.",
"Destiny|2014|Bungie|FPS,MMO|PS4,Xbox One,PS3|76|A shared-world shooter that grew into a decade.",
"Halo: Combat Evolved|2001|Bungie|FPS|Xbox,PC|97|Thirty seconds of fun, repeated perfectly.",
"Halo 2|2004|Bungie|FPS|Xbox,PC|95|Dual wielding and the birth of console matchmaking.",
"Halo 3|2007|Bungie|FPS|Xbox 360,PC|94|Finish the fight, with Forge and theatre attached.",
"Halo: Reach|2010|Bungie|FPS|Xbox 360,PC|91|A doomed squad and Bungie's finest goodbye.",
"Halo Infinite|2021|343 Industries|FPS|PC,Xbox Series,Xbox One|87|Grappleshot and an open Zeta Halo.",
"Gears of War|2006|Epic Games|TPS|Xbox 360,PC|94|Cover shooting, chainsaw bayonets, grey concrete.",
"Gears of War 3|2011|Epic Games|TPS|Xbox 360|91|The trilogy lands with Horde mode perfected.",
"Gears 5|2019|The Coalition|TPS|Xbox One,PC|84|Bigger spaces and the series at its prettiest.",
"Mass Effect|2007|BioWare|Action RPG|Xbox 360,PC,PS3|91|A galaxy of choices and one great crew.",
"Mass Effect 2|2010|BioWare|Action RPG|PC,PS3,Xbox 360|96|The suicide mission where everyone can die.",
"Mass Effect 3|2012|BioWare|Action RPG|PC,PS3,Xbox 360|89|War against the Reapers, and that ending argument.",
"Dragon Age: Origins|2009|BioWare|RPG,Tactics|PC,PS3,Xbox 360|91|A dark, chewy party RPG with six openings.",
"Dragon Age: Inquisition|2014|BioWare|RPG|PC,PS4,Xbox One|89|Leading an order across enormous regions.",
"Star Wars: Knights of the Old Republic|2003|BioWare|RPG|Xbox,PC,Switch,Mobile|93|The best Star Wars story games ever told.",
"Star Wars Jedi: Fallen Order|2019|Respawn Entertainment|Action Adventure|PC,PS4,Xbox One|79|Souls-lite lightsaber duels and Metroid-style planets.",
"Star Wars Jedi: Survivor|2023|Respawn Entertainment|Action Adventure|PC,PS5,Xbox Series|85|Cal Kestis grows up and the combat blooms.",
"Star Wars Battlefront II|2017|DICE|Shooter|PC,PS4,Xbox One|68|Gorgeous Star Wars battles, infamous launch economy.",
"Star Wars: The Old Republic|2011|BioWare|MMO,RPG|PC|85|A fully voiced MMO with class stories.",
"Grand Theft Auto III|2001|DMA Design|Action,Open World|PS2,PC,Xbox|97|The leap to 3D crime that changed everything.",
"Grand Theft Auto: Vice City|2002|Rockstar North|Action,Open World|PS2,PC,Xbox,Mobile|95|Neon, pastel suits and the best radio ever.",
"Grand Theft Auto: San Andreas|2004|Rockstar North|Action,Open World|PS2,PC,Xbox,Mobile|95|Three cities, jets, gang war, absurd scope.",
"Grand Theft Auto IV|2008|Rockstar North|Action,Open World|PS3,Xbox 360,PC|98|Liberty City as a heavy, believable place.",
"Red Dead Redemption|2010|Rockstar San Diego|Action,Open World|PS3,Xbox 360,PS4,Switch,PC|95|A western elegy with the best final act.",
"Max Payne|2001|Remedy Entertainment|TPS|PC,PS2,Xbox|89|Bullet time and hard-boiled noir narration.",
"Max Payne 3|2012|Rockstar Studios|TPS|PC,PS3,Xbox 360|87|Sweaty Sao Paulo shootouts, superb animation.",
"Bully|2006|Rockstar Vancouver|Action Adventure|PS2,Xbox 360,PC,Switch|87|Boarding school as an open world of pranks.",
"L.A. Noire|2011|Team Bondi|Adventure,Detective|PS3,Xbox 360,PC,Switch|89|Read faces, solve 1947 homicides.",
"Mafia II|2010|2K Czech|Action,Open World|PC,PS3,Xbox 360|77|A mob life story across two decades.",
"Sleeping Dogs|2012|United Front Games|Action,Open World|PC,PS3,Xbox 360|80|Undercover in Hong Kong with excellent brawling.",
"Saints Row: The Third|2011|Volition|Action,Open World|PC,PS3,Xbox 360|84|Open-world crime, all the way silly.",
"Watch Dogs 2|2016|Ubisoft Montreal|Action,Open World|PC,PS4,Xbox One|82|Hack a sunny San Francisco with drones and friends.",
"Assassin's Creed II|2009|Ubisoft Montreal|Action Adventure,Stealth|PC,PS3,Xbox 360|90|Renaissance Italy and Ezio's whole life.",
"Assassin's Creed IV: Black Flag|2013|Ubisoft Montreal|Action Adventure,Open World|PC,PS4,Xbox One|88|Pirate ships, sea shanties, Caribbean freedom.",
"Assassin's Creed Odyssey|2018|Ubisoft Quebec|Action RPG,Open World|PC,PS4,Xbox One|83|Ancient Greece as an enormous RPG playground.",
"Assassin's Creed Valhalla|2020|Ubisoft Montreal|Action RPG,Open World|PC,PS5,Xbox Series|84|Viking raids across a beautiful England.",
"Assassin's Creed Shadows|2025|Ubisoft Quebec|Action RPG,Open World|PC,PS5,Xbox Series|81|Two protagonists, one gorgeous feudal Japan.",
"Far Cry 3|2012|Ubisoft Montreal|FPS,Open World|PC,PS3,Xbox 360|88|An island, a villain, and outpost sandbox chaos.",
"Far Cry 5|2018|Ubisoft Montreal|FPS,Open World|PC,PS4,Xbox One|78|Montana cult country with co-op mayhem.",
"Tom Clancy's Rainbow Six Siege|2015|Ubisoft Montreal|FPS,Tactical|PC,PS5,Xbox Series|79|Destructible walls and the tensest rounds in shooters.",
"Tom Clancy's The Division 2|2019|Massive Entertainment|TPS,RPG|PC,PS4,Xbox One|82|Looter shooting through a fallen Washington.",
"Rayman Legends|2013|Ubisoft Montpellier|Platformer|PC,PS4,Switch,Xbox One|90|Gorgeous hand-drawn platforming with musical levels.",
"Prince of Persia: The Sands of Time|2003|Ubisoft Montreal|Platformer,Action|PS2,Xbox,PC|92|Rewind time and dance across collapsing palaces.",
"Beyond Good & Evil|2003|Ubisoft Montpellier|Action Adventure|PS2,GameCube,PC|87|A photojournalist uncovers a planetary conspiracy.",
"The Sims|2000|Maxis|Life Sim|PC,Mac|92|Build people, build houses, remove the pool ladder.",
"The Sims 3|2009|Maxis|Life Sim|PC,Mac,Xbox 360|86|An open neighbourhood full of tiny lives.",
"The Sims 4|2014|Maxis|Life Sim|PC,PS4,Xbox One|70|The best build mode in the series.",
"SimCity 2000|1993|Maxis|City Builder|PC,Mac,SNES|92|Zoning, budgets and disasters in perfect balance.",
"Cities: Skylines|2015|Colossal Order|City Builder,Simulation|PC,PS4,Xbox One,Switch|85|Traffic management as a beautiful obsession.",
"RollerCoaster Tycoon 2|2002|Chris Sawyer Productions|Management,Simulation|PC|84|Build the park, then break the coasters.",
"Civilization VI|2016|Firaxis Games|Strategy,Turn-Based|PC,Switch,PS4,Xbox One|88|One more turn, districts edition.",
"Civilization V|2010|Firaxis Games|Strategy,Turn-Based|PC,Mac|90|Hex tiles that made empire building elegant.",
"Age of Empires II|1999|Ensemble Studios|RTS|PC|92|Villagers, castles and twenty-five years of ladder play.",
"Age of Empires IV|2021|Relic Entertainment|RTS|PC,Xbox Series|81|Historic sieges with modern clarity.",
"Command & Conquer: Red Alert 2|2000|Westwood Studios|RTS|PC|86|Cheesy live action and immaculate skirmishes.",
"Total War: Warhammer III|2022|Creative Assembly|Strategy,Turn-Based|PC,Mac|86|Fantasy armies at ridiculous scale.",
"Total War: Shogun 2|2011|Creative Assembly|Strategy,Turn-Based|PC|90|The cleanest campaign the series ever shipped.",
"XCOM 2|2016|Firaxis Games|Tactics,Strategy|PC,PS4,Xbox One,Switch|88|Guerrilla turn-based tactics that punish greed.",
"XCOM: Enemy Unknown|2012|Firaxis Games|Tactics,Strategy|PC,PS3,Xbox 360|89|Name your squad, then watch them die.",
"Crusader Kings III|2020|Paradox Development Studio|Strategy,Simulation|PC,PS5,Xbox Series|91|Medieval dynasties as a soap opera generator.",
"Stellaris|2016|Paradox Development Studio|Strategy,Simulation|PC,PS4,Xbox One|78|Grand strategy among the stars.",
"Into the Breach|2018|Subset Games|Tactics,Strategy|PC,Switch,Mobile|90|Perfect information mech chess in eight turns.",
"FTL: Faster Than Light|2012|Subset Games|Roguelike,Strategy|PC,iOS|84|Manage a doomed spaceship, one jump at a time.",
"Slay the Spire|2019|Mega Crit|Roguelike,Card Game|PC,Switch,PS4,Mobile|89|Deckbuilding roguelike that spawned a genre.",
"Balatro|2024|LocalThunk|Roguelike,Card Game|PC,Switch,PS5,Xbox Series,Mobile|90|Poker hands turned into joyful number breaking.",
"Vampire Survivors|2022|Poncle|Roguelike,Action|PC,Switch,Xbox Series,Mobile|87|Barely any inputs, enormous screen-filling payoff.",
"Dead Cells|2018|Motion Twin|Roguelike,Metroidvania|PC,Switch,PS4,Xbox One|89|Fast, weighty runs through a shifting castle.",
"Risk of Rain 2|2020|Hopoo Games|Roguelike,TPS|PC,Switch,PS4,Xbox One|85|Stack items until you break physics.",
"Enter the Gungeon|2016|Dodge Roll|Roguelike,Shooter|PC,Switch,PS4,Xbox One|82|Bullet hell dungeon crawling with gun puns.",
"The Binding of Isaac: Rebirth|2014|Nicalis|Roguelike,Action|PC,Switch,PS4,Vita|84|Grotesque, endlessly deep item combinations.",
"Spelunky 2|2020|Mossmouth|Roguelike,Platformer|PC,PS4,Switch,Xbox One|88|Systems that conspire against you, hilariously.",
"Cuphead|2017|Studio MDHR|Run and Gun,Platformer|PC,Switch,PS4,Xbox One|88|1930s cartoon art over ferocious boss fights.",
"Ori and the Blind Forest|2015|Moon Studios|Metroidvania,Platformer|PC,Xbox One,Switch|88|Painterly forest platforming with real heart.",
"Ori and the Will of the Wisps|2020|Moon Studios|Metroidvania,Platformer|PC,Xbox One,Switch|90|Bigger, sharper and even more beautiful.",
"Shovel Knight|2014|Yacht Club Games|Platformer|PC,Switch,3DS,PS4|85|An 8-bit tribute that outclasses its influences.",
"Katana Zero|2019|Askiisoft|Action,Platformer|PC,Switch,Xbox One|82|One-hit kills, time rewinds, neon violence.",
"Hyper Light Drifter|2016|Heart Machine|Action RPG|PC,Switch,PS4,Xbox One|84|Wordless pixel-art melancholy and razor combat.",
"Bastion|2011|Supergiant Games|Action RPG|PC,Xbox 360,Switch|86|A narrator describes your every move.",
"Transistor|2014|Supergiant Games|Action RPG,Tactics|PC,PS4,Switch|83|Plan turns, then let them fly.",
"Pyre|2017|Supergiant Games|RPG,Sports|PC,PS4|85|A fantasy road trip decided by magic basketball.",
"Disco Elysium|2019|ZA/UM|RPG|PC,PS5,Switch,Xbox Series|91|A detective story argued with your own skills.",
"Divinity: Original Sin II|2017|Larian Studios|RPG,Turn-Based|PC,PS4,Switch,Xbox One|93|Elemental chaos and total systemic freedom.",
"Planescape: Torment|1999|Black Isle Studios|RPG|PC|91|What can change the nature of a man?"
]);
