/* Postgame — game catalogue, part 4 of 5 */
window.GAME_ROWS = (window.GAME_ROWS || []).concat([
"Uncharted 2: Among Thieves|2009|Naughty Dog|Action Adventure,TPS|PS3,PS4,PC|96|Blockbuster adventure filmmaking you actually play.",
"Uncharted 4: A Thief's End|2016|Naughty Dog|Action Adventure,TPS|PS4,PC|93|A gorgeous, grown-up goodbye to Nathan Drake.",
"Jak and Daxter: The Precursor Legacy|2001|Naughty Dog|Platformer|PS2,PS3,PS4|90|Seamless worlds and buttery platforming.",
"Ratchet & Clank: Rift Apart|2021|Insomniac Games|Action Platformer|PS5,PC|88|Dimension hopping with no loading screens.",
"Sly Cooper and the Thievius Raccoonus|2002|Sucker Punch Productions|Platformer,Stealth|PS2,PS3,Vita|86|Cartoon heist platforming with real style.",
"Shadow of the Colossus|2005|Team Ico|Action Adventure|PS2,PS3,PS4|91|Sixteen enormous, sorrowful boss climbs.",
"Ico|2001|Team Ico|Adventure,Puzzle|PS2,PS3|90|Hold her hand and escape the castle.",
"Gran Turismo 3: A-Spec|2001|Polyphony Digital|Racing,Simulation|PS2|95|The racing sim that sold the PS2.",
"Gran Turismo 7|2022|Polyphony Digital|Racing,Simulation|PS5,PS4|87|A car museum you can drive through.",
"Returnal|2021|Housemarque|Roguelike,TPS|PS5,PC|86|Bullet-hell roguelike wrapped in cosmic horror.",
"Journey|2012|Thatgamecompany|Adventure|PS3,PS4,PC,Mobile|92|Wordless companionship across a desert.",
"Flower|2009|Thatgamecompany|Adventure|PS3,PS4,PC,Mobile|87|Wind, petals, and pure calm.",
"Inside|2016|Playdead|Puzzle,Platformer|PC,PS4,Switch,Xbox One|93|A dread-soaked side-scroller with no wasted frame.",
"Limbo|2010|Playdead|Puzzle,Platformer|PC,PS3,Xbox 360,Switch|88|Silhouettes, spiders, and lethal trial and error.",
"Little Nightmares|2017|Tarsier Studios|Horror,Puzzle|PC,PS4,Switch,Xbox One|79|A tiny child in a grotesque, enormous world.",
"Outer Wilds|2019|Mobius Digital|Adventure,Exploration|PC,PS5,Switch,Xbox Series|85|A solar system in a 22-minute time loop.",
"Subnautica|2018|Unknown Worlds|Survival,Exploration|PC,PS4,Switch,Xbox One|87|An alien ocean that is beautiful and terrifying.",
"Valheim|2021|Iron Gate Studio|Survival,Sandbox|PC,Xbox Series|89|Viking survival building with genuinely great bosses.",
"Rust|2018|Facepunch Studios|Survival,Multiplayer|PC,PS4,Xbox One|69|Other players are the whole horror.",
"ARK: Survival Evolved|2017|Studio Wildcard|Survival,Sandbox|PC,PS4,Switch,Xbox One|70|Tame dinosaurs, build bases, lose everything.",
"DayZ|2018|Bohemia Interactive|Survival,Multiplayer|PC,PS4,Xbox One|68|The zombie survival sim that started the genre.",
"The Forest|2018|Endnight Games|Survival,Horror|PC,PS4|78|Crash landing, treehouse, cannibals.",
"Terraria|2011|Re-Logic|Sandbox,Survival|PC,PS4,Switch,Mobile|83|A 2D world with more content than seems legal.",
"Don't Starve|2013|Klei Entertainment|Survival|PC,PS4,Switch,Mobile|79|Gothic Tim Burton wilderness that kills you politely.",
"Oxygen Not Included|2019|Klei Entertainment|Simulation,Colony Sim|PC|83|Asteroid colony management down to each calorie.",
"RimWorld|2018|Ludeon Studios|Simulation,Colony Sim|PC,PS4,Xbox One|87|A story generator disguised as a colony sim.",
"Factorio|2020|Wube Software|Simulation,Strategy|PC,Switch|90|The factory must grow.",
"Satisfactory|2024|Coffee Stain Studios|Simulation,Sandbox|PC|86|First-person factory building on an alien planet.",
"Dyson Sphere Program|2021|Youthcat Studio|Simulation,Strategy|PC|84|Automation that scales to a whole star.",
"Kerbal Space Program|2015|Squad|Simulation|PC,PS4,Xbox One|88|Rocket science taught by cheerful catastrophe.",
"Microsoft Flight Simulator|2020|Asobo Studio|Simulation|PC,Xbox Series|91|The entire planet, rendered and flyable.",
"Euro Truck Simulator 2|2012|SCS Software|Simulation|PC,Mac|79|Long hauls, podcasts, unexpected serenity.",
"Football Manager 2024|2023|Sports Interactive|Management,Sports|PC,Switch,Mobile|84|Spreadsheets that make grown adults cry.",
"Prison Architect|2015|Introversion Software|Management,Simulation|PC,PS4,Xbox One|78|Build a prison, confront its logic.",
"Two Point Hospital|2018|Two Point Studios|Management,Simulation|PC,PS4,Switch,Xbox One|82|Theme Hospital's spirit, modernised.",
"Theme Hospital|1997|Bullfrog Productions|Management,Simulation|PC,PS1|84|Cure bloaty head, ignore the queue.",
"Dwarf Fortress|2006|Bay 12 Games|Simulation,Colony Sim|PC|88|Losing is fun, and unfathomably deep.",
"Slime Rancher|2017|Monomi Park|Simulation,Adventure|PC,PS4,Switch,Xbox One|76|Vacuum up adorable slimes for profit.",
"PUBG: Battlegrounds|2017|Krafton|Battle Royale,Shooter|PC,PS4,Xbox One,Mobile|86|The tense original battle royale.",
"Among Us|2018|Innersloth|Party,Social Deduction|PC,Switch,Mobile,PS5|85|Four sentences of accusation per round.",
"Fall Guys|2020|Mediatonic|Party,Platformer|PC,PS5,Switch,Xbox Series|81|Beans falling over in delightful obstacle courses.",
"Overcooked 2|2018|Ghost Town Games|Party,Simulation|PC,PS4,Switch,Xbox One|81|Cooperative cooking as relationship stress test.",
"It Takes Two|2021|Hazelight Studios|Co-op,Platformer|PC,PS5,Switch,Xbox Series|88|Every level invents a brand-new mechanic.",
"A Way Out|2018|Hazelight Studios|Co-op,Action Adventure|PC,PS4,Xbox One|71|A prison break built entirely for two.",
"Split Fiction|2025|Hazelight Studios|Co-op,Action Adventure|PC,PS5,Xbox Series|91|Two writers trapped inside their own genres.",
"Human: Fall Flat|2016|No Brakes Games|Puzzle,Party|PC,PS4,Switch,Mobile|72|Floppy physics puzzles, funnier with friends.",
"Untitled Goose Game|2019|House House|Puzzle,Sandbox|PC,Switch,PS4,Xbox One|81|Be a horrible goose. That is the whole pitch.",
"Rocket League|2015|Psyonix|Sports,Racing|PC,PS5,Switch,Xbox Series|86|Football with rocket cars, endlessly skillful.",
"Helldivers 2|2024|Arrowhead Game Studios|TPS,Co-op|PC,PS5,Xbox Series|82|Chaotic co-op satire and glorious friendly fire.",
"Deep Rock Galactic|2020|Ghost Ship Games|FPS,Co-op|PC,PS5,Xbox Series|85|Rock and stone. Dwarves in space, mining.",
"Warframe|2013|Digital Extremes|TPS,Action|PC,PS5,Switch,Xbox Series|82|Space ninja movement and a decade of depth.",
"Path of Exile|2013|Grinding Gear Games|Action RPG|PC,PS4,Xbox One|86|The most intimidating skill tree in gaming.",
"Path of Exile 2|2024|Grinding Gear Games|Action RPG|PC,PS5,Xbox Series|87|Slower, weightier, brutally ambitious loot hunting.",
"Grim Dawn|2016|Crate Entertainment|Action RPG|PC,Xbox One|83|Dual-class looting in a ruined Victorian world.",
"Last Epoch|2024|Eleventh Hour Games|Action RPG|PC,PS5,Xbox Series|80|Time-travelling loot with excellent crafting.",
"Lost Ark|2019|Smilegate RPG|MMO,Action RPG|PC|81|Spectacular raid choreography, enormous grind.",
"Guild Wars 2|2012|ArenaNet|MMO,RPG|PC,Mac|90|Living world events and no subscription.",
"Old School RuneScape|2013|Jagex|MMO,RPG|PC,Mobile|85|A community-voted museum of 2007 that never died.",
"RuneScape|2001|Jagex|MMO,RPG|PC,Mobile|82|Skilling in a browser for a generation.",
"EVE Online|2003|CCP Games|MMO,Simulation|PC,Mac|88|Spreadsheets in space, and real wars.",
"The Elder Scrolls Online|2014|ZeniMax Online Studios|MMO,RPG|PC,PS5,Xbox Series|81|All of Tamriel, together.",
"Black Desert Online|2016|Pearl Abyss|MMO,Action RPG|PC,PS4,Xbox One|72|Combat and character creation to obsess over.",
"New World|2021|Amazon Games|MMO,Action RPG|PC,PS5,Xbox Series|70|Territory war on a colonial island.",
"EverQuest|1999|Verant Interactive|MMO,RPG|PC|85|The first 3D MMO obsession.",
"Ultima Online|1997|Origin Systems|MMO,RPG|PC|89|The blueprint for every online world after it.",
"Genshin Impact|2020|miHoYo|Action RPG,Open World|PC,PS5,Mobile,Switch|84|A gorgeous free open world with a gacha attached.",
"Honkai: Star Rail|2023|HoYoverse|JRPG,Turn-Based|PC,PS5,Mobile|82|Turn-based sci-fi with immaculate presentation.",
"Zenless Zone Zero|2024|HoYoverse|Action RPG|PC,PS5,Mobile|81|Stylish urban action with excellent combat feel.",
"Wuthering Waves|2024|Kuro Games|Action RPG,Open World|PC,PS5,Mobile|76|Fast parry-driven combat in an open world.",
"Fate/Grand Order|2015|Delightworks|JRPG,Mobile|Mobile|75|Enormous story, legendary gacha economy.",
"Clash of Clans|2012|Supercell|Strategy,Mobile|Mobile|74|Base building and clan wars in your pocket.",
"Clash Royale|2016|Supercell|Card Game,Strategy|Mobile|86|Three-minute tower duels, perfectly tuned.",
"Candy Crush Saga|2012|King|Puzzle,Mobile|Mobile,PC|72|The match-three that swallowed the commute.",
"Angry Birds|2009|Rovio Entertainment|Puzzle,Mobile|Mobile,PC|85|Slingshot physics that defined early smartphones.",
"Monument Valley|2014|ustwo games|Puzzle,Mobile|Mobile,PC|89|Escher architecture as gentle puzzling.",
"Subway Surfers|2012|SYBO Games|Endless Runner,Mobile|Mobile|70|The most downloaded runner on earth.",
"Honor of Kings|2015|TiMi Studio Group|MOBA,Mobile|Mobile|78|The biggest mobile MOBA in the world.",
"Garena Free Fire|2017|111dots Studio|Battle Royale,Mobile|Mobile|71|Battle royale built for every phone.",
"Puzzle & Dragons|2012|GungHo Online|Puzzle,Mobile|Mobile|80|Match orbs, collect monsters, repeat for years.",
"Marvel Snap|2022|Second Dinner|Card Game|PC,Mobile|85|Card duels that respect your lunch break.",
"Teamfight Tactics|2019|Riot Games|Strategy,Auto Battler|PC,Mobile|80|Auto chess refined into a real sport.",
"Roblox|2006|Roblox Corporation|Sandbox,Platform|PC,Xbox One,Mobile,PS5|75|Millions of games made by their own players.",
"Phasmophobia|2020|Kinetic Games|Horror,Co-op|PC,PS5,Xbox Series|80|Amateur ghost hunting with real screaming.",
"Dead by Daylight|2016|Behaviour Interactive|Horror,Multiplayer|PC,PS5,Switch,Xbox Series|71|Four survivors, one killer, endless licences.",
"Outlast|2013|Red Barrels|Horror|PC,PS4,Switch,Xbox One|80|Camcorder night vision and nowhere to hide.",
"Amnesia: The Dark Descent|2010|Frictional Games|Horror|PC,PS4,Switch,Xbox One|85|Darkness itself is the enemy.",
"Five Nights at Freddy's|2014|Scott Cawthon|Horror|PC,Mobile,Switch,PS4|78|Animatronics, security cameras, a cultural phenomenon.",
"Dead Space|2008|EA Redwood Shores|Horror,TPS|PC,PS3,Xbox 360|89|Strategic dismemberment aboard the Ishimura.",
"Dead Space Remake|2023|Motive Studio|Horror,TPS|PC,PS5,Xbox Series|89|One seamless ship, rebuilt magnificently.",
"The Evil Within|2014|Tango Gameworks|Horror,TPS|PC,PS4,Xbox One|75|Resident Evil's creator going surreal.",
"Alien: Isolation|2014|Creative Assembly|Horror,Stealth|PC,PS4,Switch,Xbox One|81|One xenomorph that genuinely learns you.",
"Alan Wake|2010|Remedy Entertainment|Horror,Action|Xbox 360,PC,PS4|83|A writer fights darkness with a flashlight.",
"Alan Wake 2|2023|Remedy Entertainment|Horror,Action|PC,PS5,Xbox Series|89|Two detectives inside a story that rewrites itself.",
"Control|2019|Remedy Entertainment|Action Adventure|PC,PS5,Switch,Xbox Series|82|Brutalist architecture and telekinetic office warfare.",
"Quantum Break|2016|Remedy Entertainment|Action,TPS|Xbox One,PC|77|Time-frozen shootouts spliced with live action.",
"Hi-Fi Rush|2023|Tango Gameworks|Rhythm,Action|PC,PS5,Switch,Xbox Series|87|Every punch lands on the beat.",
"Sifu|2022|Sloclap|Action,Beat 'em up|PC,PS5,Switch,Xbox Series|78|Age a year each death. Kung fu revenge.",
"Ghostrunner|2020|One More Level|Action,FPS|PC,PS5,Switch,Xbox Series|76|One-hit-kill cyberpunk parkour.",
"Mirror's Edge|2008|DICE|Action,Platformer|PC,PS3,Xbox 360|81|First-person free running across white rooftops.",
"Dishonored|2012|Arkane Studios|Immersive Sim,Stealth|PC,PS3,Xbox 360|91|Blink, choke, or kill everyone. Your call."
]);
