/* Postgame — game catalogue, part 9 of 10 */
window.GAME_ROWS = (window.GAME_ROWS || []).concat([
"Quake II|1997|id Software|FPS|PC,N64,Switch|93|Coloured lighting, and the shooter that taught modding.",
"Quake III Arena|1999|id Software|FPS|PC,Dreamcast|93|Nothing but arenas, rocket jumps and rail shots.",
"Unreal|1998|Epic Games|FPS|PC|91|Skaarj, huge outdoor vistas, and a famous engine.",
"Unreal Tournament|1999|Epic Games|FPS|PC,PS2,Dreamcast|92|Flak cannon, shock rifle, and the best bot AI of its day.",
"Unreal Tournament 2004|2004|Epic Games|FPS|PC|93|Onslaught mode and vehicles at scale.",
"Duke Nukem 3D|1996|3D Realms|FPS|PC,Switch|89|Interactive levels years ahead, and a very dated mouth.",
"Wolfenstein 3D|1992|id Software|FPS|PC,Switch|89|The first-person shooter, more or less invented here.",
"Return to Castle Wolfenstein|2001|Gray Matter Interactive|FPS|PC,PS2,Xbox|88|Occult Nazis and a legendary multiplayer mode.",
"Wolfenstein II: The New Colossus|2017|MachineGames|FPS|PC,PS4,Switch|86|Nazi-occupied America, and a lot of nerve.",
"Serious Sam: The First Encounter|2001|Croteam|FPS|PC,Xbox|84|Hundreds of screaming enemies at once.",
"Painkiller|2004|People Can Fly|FPS|PC,Xbox|81|A stake gun and pure arena aggression.",
"F.E.A.R.|2005|Monolith Productions|FPS,Horror|PC,PS3,Xbox 360|88|Slow motion firefights and the best AI of its generation.",
"Crysis|2007|Crytek|FPS|PC,PS3,Xbox 360|91|The nanosuit, the jungle, and a decade of benchmark jokes.",
"Far Cry|2004|Crytek|FPS,Open World|PC|89|Open tropical islands when nobody else was doing them.",
"Far Cry 2|2008|Ubisoft Montreal|FPS,Open World|PC,PS3,Xbox 360|85|Fire propagation, malaria, and jamming guns. Uncompromising.",
"Far Cry 4|2014|Ubisoft Montreal|FPS,Open World|PC,PS4,Xbox One|85|The Himalayas, elephants, and Pagan Min.",
"Far Cry 6|2021|Ubisoft Toronto|FPS,Open World|PC,PS5,Xbox Series|73|A Caribbean dictatorship and a very good crocodile.",
"Call of Duty|2003|Infinity Ward|FPS|PC,Mac|91|Squad-based World War II, and the series begins.",
"Call of Duty 2|2005|Infinity Ward|FPS|PC,Xbox 360|89|Regenerating health arrives and shooters change.",
"Call of Duty: World at War|2008|Treyarch|FPS|PC,PS3,Xbox 360|84|Brutal Pacific campaign, and Nazi Zombies as a bonus.",
"Call of Duty: Modern Warfare 3|2011|Infinity Ward|FPS|PC,PS3,Xbox 360|78|The trilogy closes at maximum volume.",
"Call of Duty: Modern Warfare (2019)|2019|Infinity Ward|FPS|PC,PS4,Xbox One|80|A tense reboot, and Gunfight.",
"Call of Duty: Modern Warfare II (2022)|2022|Infinity Ward|FPS|PC,PS5,Xbox Series|76|Gorgeous, and the best gunsmith yet.",
"Call of Duty: Black Ops III|2015|Treyarch|FPS|PC,PS4,Xbox One|81|Wall running, specialists, and enormous Zombies maps.",
"Call of Duty: Black Ops Cold War|2020|Treyarch|FPS|PC,PS5,Xbox Series|76|Branching campaign and a genuinely good twist.",
"Call of Duty: WWII|2017|Sledgehammer Games|FPS|PC,PS4,Xbox One|77|Back to boots on the ground, health packs included.",
"Call of Duty: Black Ops 7|2025|Treyarch|FPS|PC,PS5,Xbox Series|78|Co-op campaign and the fastest movement in years.",
"Battlefield 4|2013|DICE|FPS|PC,PS4,Xbox One|81|Levolution, and the multiplayer people still go back to.",
"Battlefield: Bad Company 2|2010|DICE|FPS|PC,PS3,Xbox 360|88|Destruction 2.0, and the most-missed Battlefield.",
"Battlefield 2|2005|DICE|FPS|PC|91|Commanders, squads and voice comms in 2005.",
"Battlefield V|2018|DICE|FPS|PC,PS4,Xbox One|81|Beautiful, and launched with too little of it.",
"Medal of Honor: Allied Assault|2002|2015 Inc.|FPS|PC|88|The Omaha Beach landing, before Call of Duty existed.",
"Star Wars: Republic Commando|2005|LucasArts|FPS,Tactical|Xbox,PC,Switch|82|A four-man clone squad with real personality.",
"Star Wars: Battlefront II (2005)|2005|Pandemic Studios|Shooter|PS2,Xbox,PC|84|Galactic conquest and space battles. The one people mean.",
"Overwatch 2|2022|Blizzard Entertainment|FPS,Hero Shooter|PC,PS5,Switch,Xbox Series|79|Five-a-side now, and the PvE never arrived.",
"The Finals|2023|Embark Studios|FPS|PC,PS5,Xbox Series|80|Fully destructible arenas as a game show.",
"Marvel Rivals|2024|NetEase Games|FPS,Hero Shooter|PC,PS5,Xbox Series|81|Hero shooting with destructible cover and huge rosters.",
"Escape from Tarkov|2017|Battlestate Games|FPS,Survival|PC|82|Lose everything on death. Terrifying, and addictive.",
"Squad|2020|Offworld Industries|FPS,Tactical|PC|80|Fifty-a-side with radios and actual squad leaders.",
"Insurgency: Sandstorm|2018|New World Interactive|FPS,Tactical|PC,PS5,Xbox Series|79|Lethal, quiet, and no hit markers.",
"Arma 3|2013|Bohemia Interactive|FPS,Simulation|PC|82|A military sandbox that mods into anything.",
"Hell Let Loose|2021|Black Matter|FPS,Tactical|PC,PS5,Xbox Series|76|A hundred players and a supply chain to manage.",
"Ready or Not|2023|VOID Interactive|FPS,Tactical|PC,PS5,Xbox Series|82|Door-by-door police work with awful consequences.",
"SWAT 4|2005|Irrational Games|FPS,Tactical|PC|85|Shout at suspects before you shoot. Still the benchmark.",
"Tom Clancy's Ghost Recon Wildlands|2017|Ubisoft Paris|TPS,Open World|PC,PS4,Xbox One|70|Bolivia, four friends, and total tactical freedom.",
"Tom Clancy's Splinter Cell|2002|Ubisoft Montreal|Stealth|Xbox,PC,PS2|93|Light and shadow as a health bar.",
"Metro 2033|2010|4A Games|FPS,Horror|PC,Xbox 360|81|Moscow's tunnels, bullets as currency, gas mask filters.",
"Metro: Last Light|2013|4A Games|FPS,Horror|PC,PS3,Xbox 360|82|Tighter and sadder than the first.",
"Metro Exodus|2019|4A Games|FPS,Open World|PC,PS4,Xbox One|82|Out of the tunnels, across a ruined Russia by train.",
"S.T.A.L.K.E.R.: Shadow of Chernobyl|2007|GSC Game World|FPS,Survival|PC|82|The Zone: hostile, atmospheric, unforgettable.",
"S.T.A.L.K.E.R. 2: Heart of Chornobyl|2024|GSC Game World|FPS,Survival|PC,Xbox Series|73|Made through a war, and the Zone still gets under your skin.",
"Borderlands|2009|Gearbox Software|FPS,Action RPG|PC,PS3,Xbox 360|84|Cel-shaded looter shooting, and a million guns.",
"Borderlands 2|2012|Gearbox Software|FPS,Action RPG|PC,PS3,Xbox 360|89|Handsome Jack carries the whole genre.",
"Borderlands 3|2019|Gearbox Software|FPS,Action RPG|PC,PS4,Xbox One|81|Best-feeling guns in the series, worst villains.",
"Borderlands 4|2025|Gearbox Software|FPS,Action RPG|PC,PS5,Xbox Series|82|Grappling and gliding, and the writing finally settles down.",
"TimeSplitters 2|2002|Free Radical Design|FPS|PS2,GameCube,Xbox|90|Split-screen and a map maker, from the GoldenEye team.",
"Dusk|2018|David Szymanski|FPS|PC,Switch|85|Nineties shooter design with modern movement.",
"Ultrakill|2020|Arsi Patala|FPS|PC|89|Style ranks in a first-person shooter. Absurdly good.",
"Titanfall|2014|Respawn Entertainment|FPS|Xbox One,PC|86|Wall running and mechs, and nothing else felt like it.",
"Warhammer: Vermintide 2|2018|Fatshark|FPS,Co-op|PC,PS4,Xbox One|80|Melee co-op against endless ratmen.",
"Warhammer 40,000: Darktide|2022|Fatshark|FPS,Co-op|PC,Xbox Series|79|Vermintide with lasguns and a better class system.",
"Payday 2|2013|Overkill Software|FPS,Co-op|PC,PS4,Switch|79|Heists that fall apart in the best way.",
"Lethal Company|2023|Zeekerss|Horror,Co-op|PC|85|Collect scrap for a corporation. Die screaming on voice chat.",
"Left 4 Dead|2008|Valve|FPS,Co-op,Horror|PC,Xbox 360|89|Four survivors and an AI director that hates you.",
"Assassin's Creed|2007|Ubisoft Montreal|Action Adventure,Stealth|PC,PS3,Xbox 360|81|Repetitive, and the parkour was a revelation.",
"Assassin's Creed Brotherhood|2010|Ubisoft Montreal|Action Adventure,Stealth|PC,PS3,Xbox 360|89|Rome, an assassin guild, and surprising multiplayer.",
"Assassin's Creed III|2012|Ubisoft Montreal|Action Adventure,Open World|PC,PS3,Wii U|85|Naval battles arrive, and the frontier is beautiful.",
"Assassin's Creed Unity|2014|Ubisoft Montreal|Action Adventure,Open World|PC,PS4,Xbox One|70|Broken at launch, and now the prettiest crowd in games.",
"Assassin's Creed Origins|2017|Ubisoft Montreal|Action RPG,Open World|PC,PS4,Xbox One|85|Ptolemaic Egypt, and the series becomes an RPG.",
"Assassin's Creed Mirage|2023|Ubisoft Bordeaux|Action Adventure,Stealth|PC,PS5,Xbox Series|76|Baghdad, and a deliberate return to being small.",
"Batman: Arkham Asylum|2009|Rocksteady Studios|Action Adventure|PC,PS3,Xbox 360|92|Freeflow combat, and the best licensed game ever made.",
"Batman: Arkham City|2011|Rocksteady Studios|Action Adventure,Open World|PC,PS3,Xbox 360|96|A whole walled district, and a perfect ending.",
"Batman: Arkham Knight|2015|Rocksteady Studios|Action Adventure,Open World|PC,PS4,Xbox One|87|Gorgeous Gotham, and rather a lot of tank.",
"Middle-earth: Shadow of Mordor|2014|Monolith Productions|Action,Open World|PC,PS4,Xbox One|84|The Nemesis system remembers who killed you.",
"Middle-earth: Shadow of War|2017|Monolith Productions|Action,Open World|PC,PS4,Xbox One|80|Orc armies and sieges, once the loot boxes left.",
"Mad Max|2015|Avalanche Studios|Action,Open World|PC,PS4,Xbox One|69|Car combat in a wasteland that genuinely feels dry.",
"Prototype|2009|Radical Entertainment|Action,Open World|PC,PS3,Xbox 360|79|Absurd power in a Manhattan that fights back.",
"Saints Row IV|2013|Volition|Action,Open World|PC,PS3,Xbox 360|82|Superpowers, an alien invasion, and a dubstep gun.",
"Saints Row 2|2008|Volition|Action,Open World|PC,PS3,Xbox 360|82|The one that balanced crime story and total nonsense.",
"Watch Dogs|2014|Ubisoft Montreal|Action,Open World|PC,PS4,Xbox One|80|Hack the city, and mind the downgrade discourse.",
"Watch Dogs: Legion|2020|Ubisoft Toronto|Action,Open World|PC,PS5,Xbox Series|76|Recruit anyone in London, including pensioners.",
"Spider-Man 2|2004|Treyarch|Action Adventure,Open World|PS2,Xbox,GameCube|80|The first web-swinging that obeyed physics.",
"Marvel's Guardians of the Galaxy|2021|Eidos Montreal|Action Adventure|PC,PS5,Xbox Series|80|Nobody expected the writing to be this good.",
"Marvel's Avengers|2020|Crystal Dynamics|Action,Co-op|PC,PS4,Xbox One|68|A strong campaign strapped to a dead live service.",
"Star Wars: The Force Unleashed|2008|LucasArts|Action|PS3,Xbox 360,Wii|73|Physics-driven Force powers and a lot of throwing.",
"Lego Star Wars: The Skywalker Saga|2022|Traveller's Tales|Action Adventure|PC,PS5,Switch|81|All nine films, and hundreds of characters.",
"A Plague Tale: Innocence|2019|Asobo Studio|Action Adventure,Stealth|PC,PS4,Xbox One|81|Rats in their thousands, and a brother to protect.",
"A Plague Tale: Requiem|2022|Asobo Studio|Action Adventure,Stealth|PC,PS5,Xbox Series|82|Bigger, bleaker, and technically astonishing.",
"No Man's Sky|2016|Hello Games|Survival,Open World|PC,PS5,Switch,Xbox Series|71|The comeback story of the decade.",
"Elite Dangerous|2014|Frontier Developments|Simulation,Open World|PC,PS4,Xbox One|80|The Milky Way at one-to-one scale.",
"Astroneer|2019|System Era Softworks|Survival,Sandbox|PC,PS4,Switch,Xbox One|79|Terrain deformation and very cheerful space industry.",
"Space Engineers|2019|Keen Software House|Simulation,Sandbox|PC,Xbox One|76|Build a ship bolt by bolt, then watch it break.",
"Sons of the Forest|2024|Endnight Games|Survival,Horror|PC,PS5,Xbox Series|79|The Forest again, with a companion who helps.",
"Palworld|2024|Pocketpair|Survival,Sandbox|PC,PS5,Xbox Series|78|Creature collecting plus base building plus firearms.",
"Enshrouded|2024|Keen Games|Survival,Action RPG|PC,PS5,Xbox Series|79|Voxel building with genuinely good combat.",
"Green Hell|2019|Creepy Jar|Survival|PC,PS4,Switch,Xbox One|75|Amazon survival that tracks your sanity and your parasites.",
"V Rising|2022|Stunlock Studios|Survival,Action RPG|PC,PS5|82|Build a castle, avoid the sun, hunt bosses.",
"Conan Exiles|2018|Funcom|Survival,Open World|PC,PS4,Xbox One|71|Brutal building in Conan's world.",
"7 Days to Die|2013|The Fun Pimps|Survival,Horror|PC,PS5,Xbox Series|72|Voxel base building against a weekly horde.",
"Project Zomboid|2013|The Indie Stone|Survival,Simulation|PC,Mac|84|This is how you died. Isometric, merciless, deep."
]);
