/* Postgame — game catalogue, part 7 of 10 */
window.GAME_ROWS = (window.GAME_ROWS || []).concat([
"Halo 4|2012|343 Industries|FPS|Xbox 360,PC|87|343's first swing, and the prettiest Halo of its era.",
"Halo 5: Guardians|2015|343 Industries|FPS|Xbox One|84|Great multiplayer, a campaign nobody defends.",
"Halo 3: ODST|2009|Bungie|FPS|Xbox 360,PC|83|Noir Mombasa at night, jazz and no super soldier.",
"Halo Wars|2009|Ensemble Studios|RTS|Xbox 360,PC|82|A console RTS that actually controls well.",
"Gears of War 2|2008|Epic Games|TPS|Xbox 360|93|Bigger, meatier, and Horde mode arrives.",
"Gears of War 4|2016|The Coalition|TPS|Xbox One,PC|84|A safe, extremely well-made handover.",
"Fable III|2010|Lionhead Studios|Action RPG|Xbox 360,PC|80|Become king, then find out ruling is admin.",
"Forza Motorsport 4|2011|Turn 10 Studios|Racing,Simulation|Xbox 360|91|The high point of the track-day sim on console.",
"Forza Horizon 3|2016|Playground Games|Racing,Open World|Xbox One,PC|91|Australia, convoys, and the festival format perfected.",
"Crackdown|2007|Realtime Worlds|Action,Open World|Xbox 360|83|Jump higher, throw further, collect the orbs.",
"Sunset Overdrive|2014|Insomniac Games|Action,TPS|Xbox One,PC|81|Grinding rails through an energy-drink apocalypse.",
"Hellblade: Senua's Sacrifice|2017|Ninja Theory|Action Adventure|PC,PS4,Xbox One|81|Psychosis rendered in binaural audio. Wear headphones.",
"Senua's Saga: Hellblade II|2024|Ninja Theory|Action Adventure|PC,Xbox Series|81|Astonishing to look at, narrow by design.",
"Avowed|2025|Obsidian Entertainment|Action RPG|PC,Xbox Series|81|First-person Obsidian RPG with excellent writing.",
"South of Midnight|2025|Compulsion Games|Action Adventure|PC,Xbox Series|80|Southern gothic folklore in stop-motion style.",
"Grounded|2022|Obsidian Entertainment|Survival,Sandbox|PC,Xbox One,Switch|82|Shrunk to ant size in a suburban back garden.",
"State of Decay 2|2018|Undead Labs|Survival,Open World|PC,Xbox One|68|Zombie community management with permanent death.",
"Killer Instinct|2013|Double Helix Games|Fighting|Xbox One,PC|80|Combo breakers and the best free-to-play fighter.",
"Jade Empire|2005|BioWare|Action RPG|Xbox,PC|89|Mythic China, real-time martial arts, BioWare choices.",
"Age of Mythology|2002|Ensemble Studios|RTS|PC|89|Age of Empires plus gods, hydras and Titans.",
"Rise of Nations|2003|Big Huge Games|RTS|PC|89|Civilization's sweep at real-time speed.",
"Indiana Jones and the Great Circle|2024|MachineGames|Action Adventure|PC,Xbox Series,PS5|86|Fists, whip and puzzles, and it nails the voice.",
"Battletoads|1991|Rare|Beat 'em up|NES|79|Beloved, and that bike level has ruined childhoods.",
"Sonic the Hedgehog|1991|Sonic Team|Platformer|Genesis,Switch|86|Speed as an argument against Mario.",
"Sonic 3 & Knuckles|1994|Sonic Team|Platformer|Genesis,PC|90|The best classic Sonic, once you lock the carts together.",
"Sonic CD|1993|Sonic Team|Platformer|Sega CD,PC,Switch|85|Time travel, and two soundtracks to argue about.",
"Sonic Generations|2011|Sonic Team|Platformer|PC,PS3,Xbox 360|79|Classic and modern Sonic sharing a birthday.",
"Sonic Colors|2010|Sonic Team|Platformer|Wii,PC,Switch|78|Wisps, bright colours, and the series briefly fine again.",
"Shenmue II|2001|Sega AM2|Adventure,Simulation|Dreamcast,Xbox,PC|91|Hong Kong, and the ambition somehow grows.",
"Yakuza Kiwami|2016|Ryu Ga Gotoku Studio|Action Adventure|PS4,PC,Xbox One|82|The first Yakuza rebuilt, Majima hunting you everywhere.",
"Judgment|2018|Ryu Ga Gotoku Studio|Action Adventure,Detective|PS4,PC,Xbox Series|80|Kamurocho again, this time as a defence lawyer.",
"Lost Judgment|2021|Ryu Ga Gotoku Studio|Action Adventure,Detective|PS5,PC,Xbox Series|84|A school bullying case with real teeth.",
"Virtua Fighter 2|1994|Sega AM2|Fighting|Arcade,Saturn|91|The purest 3D fighter of the arcade era.",
"Daytona USA|1994|Sega AM2|Racing|Arcade,Saturn|87|Rolling start. Daytonaaaa.",
"Crazy Taxi|1999|Hitmaker|Racing|Dreamcast,PC|87|Yeah yeah yeah yeah yeah. All you need to know.",
"Phantasy Star Online|2000|Sonic Team|MMO,Action RPG|Dreamcast,GameCube|89|Console players' first online RPG obsession.",
"Panzer Dragoon Saga|1998|Team Andromeda|JRPG,Turn-Based|Saturn|88|A rail shooter turned RPG, and impossibly rare.",
"NiGHTS into Dreams|1996|Sonic Team|Action,Platformer|Saturn,PC|85|Flight as pure score-chasing grace.",
"Skies of Arcadia|2000|Overworks|JRPG,Turn-Based|Dreamcast,GameCube|93|Sky pirates, airship battles, boundless optimism.",
"Valkyria Chronicles|2008|Sega|Tactics,JRPG|PS3,PC,Switch|86|Watercolour war with turn-based aiming.",
"Rome: Total War|2004|Creative Assembly|Strategy,Turn-Based|PC|92|Legions on screen at a scale nobody had seen.",
"Medieval II: Total War|2006|Creative Assembly|Strategy,Turn-Based|PC|88|Still the mod community's favourite battlefield.",
"Total War: Three Kingdoms|2019|Creative Assembly|Strategy,Turn-Based|PC|89|Character-driven strategy, the series' best campaign.",
"Streets of Rage 2|1992|Sega|Beat 'em up|Genesis,Switch|89|Yuzo Koshiro's soundtrack alone earns its place.",
"Streets of Rage 4|2020|Dotemu|Beat 'em up|PC,PS4,Switch,Xbox One|83|Hand-painted revival that respects the originals.",
"Golden Axe|1989|Sega|Beat 'em up|Arcade,Genesis|82|Barbarians, dwarves and dragons you can steal.",
"Out Run|1986|Sega AM2|Racing|Arcade,Genesis|88|Pick a road, pick a song, keep driving.",
"Space Harrier|1985|Sega AM2|Rail Shooter|Arcade,Genesis|83|Get ready. Absolute sensory assault for 1985.",
"Space Channel 5|1999|United Game Artists|Rhythm|Dreamcast,PS2|78|Report the news by dancing at aliens.",
"Etrian Odyssey|2007|Atlus|JRPG,Dungeon Crawler|DS,3DS|77|Draw your own map on the bottom screen.",
"Resident Evil|1996|Capcom|Horror|PS1,Saturn,PC|91|Fixed cameras, tank controls, and that first dog.",
"Resident Evil 3: Nemesis|1999|Capcom|Horror|PS1,PC,Dreamcast|91|A pursuer that follows you between rooms.",
"Resident Evil 3 Remake|2020|Capcom|Horror,TPS|PC,PS4,Xbox One|79|Great to play, over far too quickly.",
"Resident Evil 5|2009|Capcom|Horror,TPS|PC,PS3,Xbox 360|86|Co-op action horror, best with a friend.",
"Resident Evil 6|2012|Capcom|Horror,TPS|PC,PS3,Xbox 360|74|Four campaigns, no idea what it wants to be.",
"Devil May Cry|2001|Capcom|Action,Hack and Slash|PS2|94|Started as Resident Evil 4 and became a genre.",
"Devil May Cry 4|2008|Capcom|Action,Hack and Slash|PS3,Xbox 360,PC|84|Nero's arm, Dante's return, recycled levels.",
"Street Fighter Alpha 3|1998|Capcom|Fighting|Arcade,PS1|89|Three fighting styles and an enormous roster.",
"Street Fighter III: 3rd Strike|1999|Capcom|Fighting|Arcade,Dreamcast|92|Parries. Still the connoisseur's Street Fighter.",
"Street Fighter V|2016|Capcom|Fighting|PC,PS4|77|Rough launch, superb by the end of its life.",
"Marvel vs. Capcom 3|2011|Capcom|Fighting|PS3,Xbox 360|85|Three-on-three chaos with gorgeous art.",
"Mega Man 3|1990|Capcom|Platformer,Action|NES,Switch|88|The slide, Proto Man, and Rush.",
"Mega Man 11|2018|Capcom|Platformer,Action|PC,PS4,Switch,Xbox One|82|A proper modern Mega Man, gear system and all.",
"Monster Hunter Freedom Unite|2008|Capcom|Action RPG|PSP|89|The handheld hunt that made Japan obsessed.",
"Monster Hunter Generations Ultimate|2018|Capcom|Action RPG|Switch|85|A greatest-hits hunt with hunting styles.",
"Ghosts 'n Goblins|1985|Capcom|Platformer,Action|Arcade,NES|76|Famously, aggressively unfair.",
"Strider|1989|Capcom|Platformer,Action|Arcade,Genesis|85|A ninja with a plasma sword and no brakes.",
"Final Fight|1989|Capcom|Beat 'em up|Arcade,SNES|85|Haggar, a pipe, and Metro City's worst street.",
"Dino Crisis|1999|Capcom|Horror|PS1,PC|82|Resident Evil, but the dogs are raptors.",
"Onimusha: Warlords|2001|Capcom|Action Adventure|PS2,PC,Switch|85|Sengoku demons and sword duels with soul absorption.",
"Lost Planet|2006|Capcom|TPS,Action|Xbox 360,PC|79|Grappling hooks, snow, and enormous bugs.",
"Dead Rising|2006|Capcom|Action,Horror|Xbox 360,PC|85|Seventy-two hours in a mall with anything as a weapon.",
"Viewtiful Joe|2003|Clover Studio|Action,Beat 'em up|GameCube,PS2|93|Slow-motion as a combat mechanic. Henshin a go-go.",
"God Hand|2006|Clover Studio|Action,Beat 'em up|PS2|73|A brawler that knows exactly how stupid it is.",
"Ghost Trick: Phantom Detective|2010|Capcom|Puzzle,Adventure|DS,PC,Switch|83|Possess objects to undo your own murder.",
"Kunitsu-Gami: Path of the Goddess|2024|Capcom|Action,Strategy|PC,PS5,Xbox Series|82|Tower defence crossed with a sword and a dance.",
"Darkstalkers|1994|Capcom|Fighting|Arcade,PS1|82|Universal monsters as a fighting roster.",
"Silent Hill|1999|Konami|Horror|PS1,PC|86|The fog was a hardware limit and became an aesthetic.",
"Silent Hill 3|2003|Konami|Horror|PS2,PC|85|A direct sequel to the first, and the nastiest of them.",
"Silent Hill f|2025|NeoBards Entertainment|Horror|PC,PS5,Xbox Series|87|1960s rural Japan, and a genuinely new direction.",
"Metal Gear|1987|Konami|Stealth,Action|MSX,NES|80|Avoiding guards before anyone called it stealth.",
"Metal Gear Solid 4: Guns of the Patriots|2008|Kojima Productions|Stealth,Action|PS3|94|Old Snake, and cutscenes measured in hours.",
"Metal Gear Solid: Peace Walker|2010|Kojima Productions|Stealth,Action|PSP,PS3|89|Base building on a handheld, and the blueprint for MGSV.",
"Metal Gear Solid Delta: Snake Eater|2025|Konami|Stealth,Action|PC,PS5,Xbox Series|87|A faithful rebuild of the best one.",
"Castlevania|1986|Konami|Platformer,Action|NES,Switch|84|Whip, stairs, and merciless knockback.",
"Castlevania III: Dracula's Curse|1989|Konami|Platformer,Action|NES|88|Branching paths and three companions.",
"Super Castlevania IV|1991|Konami|Platformer,Action|SNES|89|A whip you can swing in eight directions.",
"Castlevania: Aria of Sorrow|2003|Konami|Metroidvania|GBA|91|Soul stealing, and the best of the GBA trilogy.",
"Gradius|1985|Konami|Shoot 'em up|Arcade,NES|83|The Options, the power meter, and Moai heads.",
"Frogger|1981|Konami|Arcade,Action|Arcade,Multi|80|Cross the road. Do not think about it too hard.",
"Bomberman|1983|Hudson Soft|Party,Action|NES,Multi|82|Blow up your friends in a grid. Perfect.",
"Suikoden II|1998|Konami|JRPG,Turn-Based|PS1|88|108 recruitable characters and a real villain.",
"Yu-Gi-Oh! Master Duel|2022|Konami|Card Game|PC,PS5,Switch,Mobile|78|Twenty years of cards, no training wheels.",
"Teenage Mutant Ninja Turtles: Turtles in Time|1991|Konami|Beat 'em up|Arcade,SNES|87|Throwing enemies at the screen. Still funny.",
"Teenage Mutant Ninja Turtles: Shredder's Revenge|2022|Tribute Games|Beat 'em up|PC,PS4,Switch,Xbox One|83|Six-player pizza-fuelled nostalgia done right.",
"Metal Slug|1996|Nazca Corporation|Run and Gun|Arcade,Switch|85|The finest pixel animation in any shooter.",
"Metal Slug 3|2000|SNK|Run and Gun|Arcade,PC,Switch|85|Branching paths, mummies, and a giant crab.",
"The King of Fighters '98|1998|SNK|Fighting|Arcade,PS2|89|The dream match, and the series' balance peak.",
"Samurai Shodown|1993|SNK|Fighting|Arcade,Switch|84|One clean hit can end a round.",
"Garou: Mark of the Wolves|1999|SNK|Fighting|Arcade,Dreamcast|89|The just-defend system and gorgeous sprites."
]);
