/* Postgame - game catalogue, part 15
   Harvested from Steam. Rows carry two extra fields: the Steam app id
   (for the 600x900 capsule) and the percentage of Steam reviews that
   are positive. */
window.GAME_ROWS = (window.GAME_ROWS || []).concat([
"IdleOn|2025|Lavaflame2|Simulation,MMO,Management|PC||The incremental idle MMO where your heroes keep fighting while you're gone! Spend their loot on.|1476970|80",
"Need for Speed Payback|2020|Ghost Games|Racing,Open World,Sports|PC|62|Set in the underworld of Fortune Valley, you and your crew were divided by betrayal and.|1262580|86",
"Plague Inc: Evolved|2016|Ndemic Creations|Strategy,Simulation,Tactical|PC,Mac,Linux||Plague Inc: Evolved is a unique mix of high strategy and terrifyingly realistic simulation..|246620|94",
"AX:EL - Air XenoDawn|2015|Alex Piola|Action,Simulation,Shooter|PC||Combining the very best of sci-fi and aerial dogfighting gameplay, AX:EL delivers a totally new.||75",
"Shadow Warrior 2|2016|Flying Wild Hog|Action,Shooter,FPS|PC|78|Shadow Warrior 2 is the stunning evolution of Flying Wild Hog's offbeat first-person shooter.|324800|87",
"Keep Talking and Nobody Explodes|2015|Steel Crate Games|Co-op,Puzzle,Party|PC,Mac,Linux|71|Find yourself trapped alone in a room with a ticking time bomb. Your friends have the manual to.|341800|97",
"SUPERHOT|2016|SUPERHOT Team|Action,FPS,Shooter|PC,Mac,Linux|82|SUPERHOT is the smash-hit FPS where time moves only when you move. No regenerating health bars..|322500|91",
"Far Cry New Dawn|2019|Ubisoft Montreal|Open World,FPS,Action|PC||Dive into a transformed vibrant post-apocalyptic Hope County, Montana, 17 years after a global.|939960|76",
"Game Dev Tycoon|2013|Greenheart Games 💚|Management,Simulation,Strategy|PC,Mac,Linux|68|In Game Dev Tycoon you replay the history of the gaming industry by starting your own video.|239820|95",
"BIGFOOT|2017|CyberLight Game Studio|Horror,Co-op,FPS|PC||You are a Bigfoot hunter with an important mission: to put an end to rumours once and for all.|509980|82",
"Total War: Warhammer|2016|CREATIVE ASSEMBLY|Strategy,RTS,Tactical|PC,Mac,Linux|86|The Old World is yours to command. Lead Legendary Lords in a combination of turn-based campaign.|364360|78",
"Tropico 6|2019|Limbic Entertainment|City Builder,Strategy,Simulation|PC,Mac,Linux|78|El Presidente is back! Prove yourself once again as a feared dictator or peace-loving statesman.|492720|87",
"Command & Conquer Remastered Collection|2020|Petroglyph|Strategy,RTS|PC|82|Command & Conquer and Red Alert are both remastered in 4K by the former Westwood Studios team.|1213210|91",
"Idle Champions of the Forgotten Realms|2020|Codename Entertainment Inc.|Simulation,Strategy,Adventure|PC,Mac||Idle Champions of the Forgotten Realms is a Dungeons & Dragons strategy management game uniting.|627690|77",
"Kingdoms and Castles|2017|Lion Shield, LLC|City Builder,Colony Sim,Strategy|PC,Mac,Linux||Kingdoms and Castles is a city-building simulation game about growing a kingdom from a tiny.|569480|93",
"FPS Chess|2022|Meta Fork|FPS,Shooter,Strategy|PC,Linux||Battle a friend in this fast paced 1v1 class-based first-person shooter. Chess takes a.|2021910|84",
"Verdun|2015|BlackMill Games|Shooter,Co-op,MMO|PC,Mac,Linux|70|Merciless trench warfare immerses you and your squad in intense battles of attack and defense..|242860|86",
"Thief|2014|Eidos-Montréal|Stealth,Action,Adventure|PC,Mac|70|Garrett, the Master Thief, steps out of the shadows into the City. In this treacherous place.|239160|75",
"WARMODE|2019|Novalink|FPS,Shooter,Action|PC||Free to play shooter about the confrontation of two irreconcilable sides, represented by the.|391460|62",
"Ravenfield|2017|SteelRaven7|FPS,Shooter,Action|PC,Mac,Linux||Fight upon the Ravenfield together with your Blue allies! Take down those pesky Reds using.|636480|97",
"Dark Messiah of Might & Magic|2006|Arkane Studios|RPG,Action,Adventure|PC|72|Discover a new breed of Action-RPG game powered by an enhanced version of the Source Engine by.|2100|91",
"HoloCure - Save the Fans!|2023|KayAnimate|Shoot 'em up,Roguelike,Action|PC||Play as your favorite Vtubers from Hololive! Fight, explore, and clear your way through armies.|2420510|99",
"Blade and Sorcery|2024|WarpFrog|VR,Sandbox,Action|PC||Blade & Sorcery is a built-for-VR medieval fantasy with full physics driven melee, ranged and.|629730|97",
"Fallen Earth Classic|2012|Little Orbit|Survival,Open World,MMO|PC|71|Fallen Earth Classic is a free-to-play massively multiplayer online role-playing game developed.|113420|60",
"Hero Siege|2014|Panic Art Studios Ltd|Action RPG,Hack and Slash,RPG|PC,Linux||Hero Siege is a fast paced Pixel Art ARPG featuring an expansive roster of unique classes, deep.|269210|69",
"BLOCKPOST LEGACY|2019|Skullcap Studios|FPS,Action,Shooter|PC||Procedural cubic 3D-shooter in the best traditions of the genre. The game is a rich cocktail.|706990|75",
"PC Building Simulator|2019|Claudiu Kiss|Simulation,Immersive Sim,Management|PC||Build and grow your very own computer repair enterprise as you learn to diagnose, fix and build.|621060|94",
"Train Simulator Classic|2015|Dovetail Games|Simulation,Racing,Open World|PC||The ultimate railway hobby for more than 15 years! From historic steam locomotives to modern.|24010|71",
"Wreckfest|2018|Bugbear|Racing,Simulation,Action|PC|81|Wreckfest is a demolition derby themed racing game with soft-body damage modeling.|228380|88",
"Gigantic|2017|Motiga Inc.|MOBA,Action,Strategy|PC|76|Gigantic is a fast and fluid Strategic Hero Shooter, where you battle against and alongside.||77",
"Emily is Away|2015|Kyle Seeley|Adventure,Simulation,Visual Novel|PC,Mac,Linux||Emily is Away is an interactive story. Create a screenname and choose your path through the.|417860|89",
"Star Wars Battlefront (Classic, 2004)|2019|Pandemic Studios|Action,FPS,TPS|PC||Fight the greatest battles in the STAR WARS universe any way you want to. The choice is yours.||96",
"Rise of Nations: Extended Edition|2014|SkyBox Labs|Strategy,RTS,Simulation|PC|89|Rise of Nations is back! Play the updated classic with full Steamworks integration and enhanced.|287450|95",
"We Were Here|2017|Total Mayhem Games|Co-op,Puzzle,Horror|PC,Mac||Lost in a frozen wasteland and split up from your partner inside an abandoned castle, the only.|582500|90",
"Riders of Icarus|2016|WeMade|MMO,RPG,Adventure|PC||Take the battle to the sky with fantastical flying mount combat unlike anything you've seen.|442080|66",
"Generation Zero|2019|Systemic Reaction|Open World,Survival,Co-op|PC||Generation Zero is a stealth-action shooter where you wage guerilla warfare against lethal.|704270|72",
"Mafia|2002|Illusion Softworks|Action,Adventure,Open World|PC|88|It's 1930. After an inadvertent brush with the mafia, cabdriver Tommy Angelo is reluctantly.|40990|87",
"Sabre Team|2021|Krisalis Software|Tactics,Turn-Based,Tactical|PC||Sabre Team is an isometric squad-level turn-based infiltration simulation that lets you.|1627140|",
"Murderous Pursuits|2018|Blazing Griffin|Action,Simulation,Strategy|PC|63|Murderous Pursuits is a kill-or-be-killed Victorian stealth-em-up for 1-8 players in which you.|638070|64",
"WEBFISHING|2024|lamedeveloper|Horror,Co-op,Sandbox|PC||WEBFISHING a multiplayer chatroom-focused fishing game! Relax and fish (on the web!)|3146520|98",
"Digimon Masters Online|2016|Move Games Co., Ltd.|MMO,Adventure,RPG|PC||DMO is MMO featuring the ever-popular Digimon franchise. This long awaited game will feature a.||67",
"Stronghold Crusader 2|2014|Firefly Studios|Strategy,City Builder,RTS|PC||Stronghold Crusader 2 is the long awaited sequel to the original castle sim. After 12 years.|232890|72",
"Superliminal|2020|Pillow Castle|Puzzle,Adventure,Exploration|PC,Mac,Linux||Perception is reality. In this mind-bending first-person puzzler, you escape a surreal dream.|1049410|95",
"Predecessor|2024|Omeda Studios|MOBA,Shooter,Strategy|PC||The tactical depth and iconic heroes of a hardcore MOBA meets the explosive verticality of a.|961200|73",
"Orcs Must Die!|2011|Robot Entertainment|Tower Defence,Action,Strategy|PC|83|Slice them, burn them, skewer them, and launch them - no matter how you get it done, orcs must.|102600|96",
"MiSide|2024|AIHASTO|Horror,Adventure,Puzzle|PC||Let's imagine that you have a game in which you care for a character. But could you imagine one.|2527500|98",
"Warhammer 40,000: Dawn of War III|2017|Relic Entertainment|Strategy,RTS,Action|PC,Mac,Linux|77|Step into a brutal battle between three warring factions In Dawn of War III you will have no.|285190|48",
"Tom Clancy's Splinter Cell Blacklist|2013|Ubisoft Toronto|Stealth,Action,Co-op|PC||In this stealth-action thriller, a terrorist group known as the Engineers launches the.||80",
"Total War: NAPOLEON - Definitive Edition|2010|CREATIVE ASSEMBLY|Strategy,RTS,Tactical|PC,Mac|81|Complete your Total War collection with this Definitive Edition of Total War: NAPOLEON, which.|34030|91",
"Crush Crush|2016|Sad Panda Studios|Visual Novel|PC,Mac,Linux||Welcome to Crush Crush - the Idle Dating Sim! Meet, flirt, and fall in love with a motley cast.|459820|89",
"EA Sports FIFA 21|2020|EA Canada|Sports,Simulation,Co-op|PC||Football is back with EA SPORTS FIFA 21, featuring more ways to team up on the street or in.|1313860|76",
"Creativerse|2017|Playful Corp.|Exploration,Sandbox,Survival|PC||A sandbox adventure game as big as your imagination.|280790|78",
"DOOM + DOOM II|2007|id Software|FPS,Action,Shooter|PC||Developed by id Software, and originally released in 1993 and 1994, the definitive, newly.|2280|96",
"BATTLETECH|2018|Harebrained Schemes|Strategy,Tactics,Turn-Based|PC,Mac,Linux|78|Take command of your own mercenary outfit of 'Mechs and the MechWarriors that pilot them.|637090|84",
"Thief Simulator|2018|Noble Muffins|Simulation,Stealth,Open World|PC,Mac||Become the best thief. Gather intel, steal things and sell them to buy hi-tech equipment. Do.|704850|88",
"Wolcen: Lords of Mayhem|2020|WOLCEN Studio|Action RPG,Hack and Slash,RPG|PC|60|Carve your path in this Hack'n'Slash free from class boundaries. Purify a world shattered by.|424370|56",
"Dragon Ball Z: KAKAROT|2020|CyberConnect2 Co. Ltd.|Action,RPG,Open World|PC|73|The Dragon Ball RPG of your dreams! For the first time, you can play the rest of the story..|851850|93",
"Orwell: Keeping an Eye On You|2016|Osmotic Studios|Adventure,Detective,Simulation|PC,Mac,Linux|77|Big Brother has arrived - and it's you. Investigate the lives of citizens to find those.|491950|91",
"Astral Party|2024|STAR ENGINE PROJECT|Party,Turn-Based,Strategy|PC||Astral Party is a multiplayer party game populated by cute anime girls! Choose your favorite.|2622000|56",
"Metal: Hellsinger|2022|The Outsiders|Rhythm,FPS,Shooter|PC||Slay to the rhythm of metal and vengeance on an infernal journey through the eight Hells. Make.|1061910|96",
"ENDLESS Space 2|2017|AMPLITUDE Studios|Strategy,Turn-Based,Action|PC,Mac|80|ENDLESS Space 2 is a Strategic Space Opera, featuring the compelling 'just one more turn'.|392110|83",
"Medal of Honor|2010|Electronic Arts|FPS,Action,Shooter|PC|72|Fight Today's War: Elite Special Forces in a gritty combat campaign using the surgical tactics.||71",
"Company of Heroes: Opposing Fronts|2007|Relic Entertainment|Strategy,RTS,Action|PC|87|The next chapter in the #1 rated RTS franchise thrusts players into a hellish war torn.|9340|92",
"Gear Up|2015|Doctor Entertainment AB|Action,Shooter,Sandbox|PC,Mac,Linux||Feel the adrenaline as you control your unique tank in multiplayer arcade action! Build your.||75",
"Shakes and Fidget|2016|Playa Games GmbH|RPG,MMO,Adventure|PC,Mac||Shakes & Fidget is a hilarious fantasy role-playing satire and at the same time, an.|438040|92",
"Squad 44|2018|Offworld|FPS,Simulation,MMO|PC||Team up and join the frontline in Squad 44, the most authentic tactical WW2 shooter. Experience.|736220|75",
"DC Universe Online|2011|Dimensional Ink Games|MMO,Action,RPG|PC|72|DC Universe Online is a Free-to-Play, massive multiplayer online action game set in the popular.|24200|81",
"Aeon Command|2014|Bat Country Games, LLC|Strategy|PC,Mac,Linux||Aeon Command is a tug of war strategy game, where you play as one of three unique factions to.||79",
"Surgeon Simulator|2013|Bossa Studios|Simulation,Puzzle,VR|PC,Mac,Linux|71|Surgeon Simulator is an over-the-top operation sim, stitching together pitch-black humour with.|233720|82",
"Draw & Guess|2021|Acureus|Co-op,Party,Puzzle|PC,Mac,Linux||An online party game of drawing and guessing for up to 16 players with a variety of modes..|1483870|84",
"POLYGON|2020|Redaster Studio|FPS,Shooter,Action|PC||POLYGON is a tactical multiplayer team 1st person shooter. Using various weapons, you will.|1241100|75",
"Resident Evil Revelations 2|2015|CAPCOM Co., Ltd.|Horror,Action,Co-op|PC||RE Revelations 2 continues the series acclaimed essential survival horror experience, while.|287290|78",
"NBA 2K21|2020|Visual Concepts|Sports,Simulation,Action|PC||NOTE: All multiplayer servers for NBA 2K21 will be shutdown as of 12/31/2022. After that time.|1225330|42",
"Natural Selection 2|2012|Unknown Worlds Entertainment|Strategy,FPS,Action|PC|80|A fast paced multiplayer shooter that pits aliens against humans in a strategic and.|4920|85",
"Capcom Arcade Stadium|2021|CAPCOM Co., Ltd.|Arcade,Action,Platformer|PC||Relive the Capcom classics! Get 1943 -The Battle of Midway- and game logo wallpapers free with.|1515950|54",
"The Ascent|2021|Neon Giant|RPG,Action,Co-op|PC||The Ascent is a solo and co-op Action-shooter RPG set in a cyberpunk world. The mega.|979690|74",
"Eador. Masters of the Broken World|2013|Snowbird Games|Strategy,Turn-Based,RPG|PC|74|Eador is a universe made of countless shards of land drifting in the Great Nothing. Each of the.|232050|68",
"Half-Life: Blue Shift|2001|Gearbox Software|FPS,Action,Shooter|PC,Mac,Linux|71|Made by Gearbox Software and originally released in 2001 as an add-on to Half-Life, Blue Shift.|130|92",
"Radical Heights|2018|Boss Key Productions|Battle Royale,Action,MMO|PC||Welcome to RADICAL HEIGHTS, a free X-TREME Early Access BATTLE ROYALE shooter. Partake in.||62",
"Enclave|2013|Starbreeze|RPG,Action,Hack and Slash|PC,Mac,Linux|71|Experience incredibly atmospheric and intense medieval combat action! Go ahead and enter a new.|253980|79",
"Call of Duty: Infinite Warfare|2016|Infinity Ward|Action,FPS,Shooter|PC|73|Infinite Warfare delivers three unique game modes: Campaign, Multiplayer, and Zombies.|292730|60",
"SEGA Mega Drive and Genesis Classics|2010|D3T Limited|Action,Adventure,RPG|PC,Mac,Linux||SEGA's collection of Mega Drive & Genesis Classics comes to a new generation, now updated with.|34270|81",
"Wargame: Red Dragon|2014|Eugen Systems|Strategy,RTS,Tactical|PC,Mac,Linux|78|The new reference in RTS at its best! The Wargame series returns to duty, larger, richer and.|251060|89",
"Star Wars Empire at War - Gold Pack|2010|Petroglyph|Strategy,RTS,Tactical|PC||Command or corrupt an entire galaxy in the definitive Star Wars strategy collection. It is a.||98",
"ATLAS|2018|Grapeshot Games|Survival,Open World,Adventure|PC||Set sail for the ultimate pirate experience! Embark on a grand adventure alongside thousands of.|834910|47",
"Dragon Ball XENOVERSE 2|2016|QLOC|Fighting,Action,Adventure|PC|78|DRAGON BALL XENOVERSE 2 builds upon the highly popular DRAGON BALL XENOVERSE with enhanced.|454650|90",
"GWENT: The Witcher Card Game|2020|CD PROJEKT RED|Strategy,Card Game,RPG|PC|80|Command mighty Witcher-world heroes in epic online PvP card battles!|1284410|82",
"Dragon Ball XENOVERSE|2015|DIMPS|Fighting,Action,Co-op|PC||DRAGON BALL XENOVERSE revisits famous battles from the series through your custom Avatar and.||90",
"The Henry Stickmin Collection|2020|PuffballsUnited|Point and Click,Adventure,Action|PC,Mac||A choose-your-own-path where failing is more fun than succeeding.|1089980|99",
"Skul: The Hero Slayer|2021|SOUTHPAW GAMES|Action,Roguelike,Platformer|PC,Mac,Linux|80|Guide 'Skul' on his quest to single-handedly take on the Imperial Army and rescue his King from.|1147560|93",
"Brothers - A Tale of Two Sons|2013|Starbreeze Studios AB|Adventure,Puzzle,Co-op|PC|90|Guide two brothers on an epic fairy tale journey from visionary Swedish film director, Josef.|225080|94",
"Defy Gravity Extended|2016|Paul Fisch|Platformer,Puzzle,Action|PC||Defy Gravity is an action platformer that is a mix between classic platforming and gravity.||86",
"The Binding of Isaac|2011|Edmund McMillen|Roguelike,Action,Adventure|PC,Mac|84|Now 20% More Evil with the Free Halloween update!|113200|95",
"Graveyard Keeper|2018|Lazy Bear Games|RPG,Simulation,Sandbox|PC,Mac,Linux|69|Build and manage a medieval graveyard while facing ethical dilemmas and making questionable.|599140|86",
"Source Filmmaker|2012|Valve|Sandbox,Horror,Souls-like|PC||The Source Filmmaker (SFM) is the movie-making tool built and used by us here at Valve to make.|1840|93",
"Sid Meier's Civilization: Beyond Earth|2014|Firaxis Games|Strategy,Turn-Based,Tactical|PC,Mac,Linux|81|Sid Meier's Civilization: Beyond Earth is a new science-fiction-themed entry into the award.|65980|60",
"Core Keeper|2024|Pugstorm|Survival,Co-op,Sandbox|PC,Linux|86|Explore a vast cavern of creatures, relics and resources in a mining sandbox adventure for 1-8.|1621690|93",
"ONE PIECE: PIRATE WARRIORS 4|2023|Koei Tecmo|Hack and Slash,Beat 'em up,Fighting|PC|75|ONE PIECE: PIRATE WARRIORS 4 is the latest evolution of PIRATE WARRIORS action! Based on the.|1089090|92",
"Data Hacker: Initiation|2014|New Reality Games|RPG,Adventure,Simulation|PC||Data Hacker: Initiation sets the stage for the Datastream saga; an epic series of tales.||65",
"Unheard - Voices of Crime|2019|NEXT Studios|Detective,Puzzle,Mystery|PC,Mac|72|What if you could hear every word spoken at the scene of a crime? 'Acoustic Detectives' wanted.|942970|96"
]);
