/* Postgame - game catalogue, part 18
   Harvested from Steam. Rows carry two extra fields: the Steam app id
   (for the 600x900 capsule) and the percentage of Steam reviews that
   are positive. */
window.GAME_ROWS = (window.GAME_ROWS || []).concat([
"Unreal Tournament 3|2009|Epic Games, Inc.|FPS,Action,Shooter|PC|83|Now includes the free Titan Pack expansion! The Titan Pack gives players a substantial amount.|13210|88",
"Bacteria|2016|Sometimes You|Puzzle|PC,Mac,Linux||'Bacteria' - A relaxing puzzle game based on the rules of the cellular automaton 'Life' devised.|448470|57",
"Team Fortress Classic|1999|Valve|Action,FPS,Hero Shooter|PC,Mac,Linux||One of the most popular online action games of all time, Team Fortress Classic features over.|20|87",
"RAGE|2011|id Software|FPS,Action,Open World|PC|79|Powered by id's revolutionary id Tech 5 technology, RAGE is an intense first-person shooter.|9200|78",
"Sultan's Game|2025|Double Cross|RPG,Simulation,Adventure|PC,Mac,Linux|83|Survive a mad Sultan's reign in this brutal resource management RPG. Draw a card every seven.|3117820|94",
"Rivals of Aether|2017|Aether Studios|Fighting,Platformer,Action|PC||RIVALS OF AETHER is an indie fighting game where warring civilizations summon the power of.|383980|96",
"Punch Club|2016|Lazy Bear Games|Management,Beat 'em up,RPG|PC,Linux|73|Train hard, fight crocodiles and find love. Earn your place in the Punch Club ranks, and.|394310|81",
"Foxhole|2022|Siege Camp|MMO,Open World,Sandbox|PC||Foxhole is a massively multiplayer game where thousands of players shape the outcome of a.|505460|84",
"The Wolf Among Us|2013|Telltale|Adventure,Detective,Point and Click|PC|85|From the makers of the 2012 Game of the Year: The Walking Dead, comes a thriller based on the.|250320|98",
"Call to Arms|2018|Digitalmindsoft|Strategy,Action,RTS|PC||Call to Arms offers an innovative mix of real-time strategy and 3rd, as well as 1st person.|302670|80",
"Assassin's Creed Rogue|2015|Ubisoft Sofia|Open World,Action,Stealth|PC|74|Introducing Assassin's Creed Rogue, the darkest chapter in the Assassin's Creed franchise yet..|311560|86",
"Chinese Parents|2018|墨鱼玩游戏|Life Sim,Horror,Simulation|PC,Mac||In this casual sim set in China, you step into the shoes of an average kid from birth towards.|736190|91",
"Universe Sandbox|2015|Giant Army|Sandbox,Simulation,Open World|PC,Mac||Create & destroy on an unimaginable scale with a realistic physics-based space simulator..|230290|96",
"NBA 2K24|2023|Visual Concepts|Sports,Simulation,Management|PC||This product will no longer be available for purchase as of 10/30/2025. NOTE: All multiplayer.|2338770|31",
"Dishonored: Death of the Outsider|2017|Arkane Studios|Stealth,Action,Adventure|PC|81|From the award-winning developers at Arkane Studios comes Dishonored: Death of the Outsider.|614570|88",
"MX Bikes|2019|PiBoSo|Simulation,VR,Racing|PC||MX Bikes is a realistic motocross simulator, based on a scratch built physics engine that.|655500|94",
"Kingdom: New Lands|2016|Noio|Tower Defence,Survival,Exploration|PC,Mac,Linux||Kingdom: New Lands builds upon the award-winning gameplay and mystery of Kingdom by introducing.|496300|86",
"Duke Nukem Forever|2011|Gearbox Software|FPS,Action,Shooter|PC,Mac|54|The King arrives with an arsenal of over-the-top weapons, giant explosions and pure.|57900|69",
"Cossacks 3|2016|GSC Game World|Strategy,RTS,City Builder|PC,Linux||Cossacks 3 is the return of RTS classics. Obtain resources, build cities and research.|333420|82",
"inZOI|2025|inZOI Studio|Life Sim,Simulation,Sandbox|PC,Mac||Every life becomes a story Create your unique story by controlling and observing the lives of.|2456740|79",
"Townscaper|2021|Oskar Stålberg|Sandbox,City Builder,Simulation|PC,Mac||Instant town building toy. Place housing blocks and watch them transform, piece by piece, into.|1291340|96",
"Injustice: Gods Among Us Ultimate Edition|2013|NetherRealm Studios|Fighting,Action,Arcade|PC|79|Injustice: Gods Among Us Ultimate Edition enhances the bold new franchise to the fighting game.||86",
"Hot Dogs, Horseshoes & Hand Grenades|2026|RUST LTD.|Sandbox,VR,Shooter|PC||Do you like hot dogs? How about horseshoes? Hand grenades? (everyone likes hand grenades).|450540|97",
"Dungeon of the ENDLESS|2014|AMPLITUDE Studios|Roguelike,Strategy,Tower Defence|PC,Mac||Dungeon of the ENDLESS is a Rogue-Like Dungeon-Defense game, in which the player and their.|249050|86",
"Gauntlet Slayer Edition|2014|Arrowhead Game Studios|Co-op,Dungeon Crawler,Hack and Slash|PC||The classic Gauntlet 4-player co-op action gameplay returns in a completely new experience!.||82",
"Assassin's Creed Revelations|2011|Ubisoft Montreal|Action,Open World,Stealth|PC|80|Ezio Auditore walks in the footsteps of the legendary mentor Altair, on a dangerous journey of.||85",
"ArcheAge|2015|XLGAMES|MMO,Open World,RPG|PC|80|Play ArcheAge - A vast open-world sandbox MMORPG with everything you can possibly imagine.|304030|52",
"SUPERHOT VR|2017|SUPERHOT Team|VR,Shooter,FPS|PC|83|Lose track of what's real. Commit yourself, body and mind. Confront the evocative, elegantly.|617830|75",
"Final Fantasy VII REMAKE INTERGRADE|2022|Square Enix|RPG,Action RPG,JRPG|PC||Cloud Strife, an ex-SOLDIER operative, descends on the mako-powered city of Midgar. The world.|1462040|89",
"Minecraft Dungeons|2021|Mojang Studios|Dungeon Crawler,Hack and Slash,Adventure|PC||Fight your way through an exciting action-adventure game, inspired by classic dungeon crawlers.|1672970|91",
"Zula Global|2018|Madbyte Games|FPS,Action,Shooter|PC||Zula is an intense free-to-play FPS in which you can play cooperatively with your teammates to.|747610|70",
"War Selection|2019|Glyph Worlds|Strategy,RTS,Co-op|PC,Linux||War Selection is a compelling RTS game featuring base building, resource extraction and.|1022450|86",
"Heaven Island - VR MMO|2015|Fabio Ferrara|Adventure,MMO,VR|PC,Mac,Linux||More a Journey in your Inner Self than a game, Heaven Island is an experience in which you'll.|400250|63",
"Kingdoms of Amalur: Re-Reckoning|2020|KAIKO|RPG,Action,Action RPG|PC||The hit RPG returns! Remastered with stunning visuals and refined gameplay Re-Reckoning.|1041720|77",
"Wartales|2023|Shiro Games|RPG,Open World,Strategy|PC||Wartales is an open world RPG in which you lead a group of mercenaries in their search for.|1527950|90",
"ShellShock Live|2020|kChamp Games|Strategy,Action,Turn-Based|PC,Mac,Linux||Demolish your friends with hundreds of upgradable weapons shot from your customizable tank in.|326460|93",
"Machinarium|2009|Amanita Design|Point and Click,Puzzle,Adventure|PC,Mac|85|Machinarium is the award-winning independent adventure game developed by the makers of Samorost.|40700|95",
"AudioSurf|2008|Dylan Fitterer|Rhythm,Arcade,Co-op|PC|85|Ride your music. Audiosurf is a music-adapting puzzle racer where you use your own music to.|12900|96",
"F1 23|2023|Codemasters|VR,Racing,Sports|PC|81|Be the last to brake in EA SPORTS F1 23, the official video game of the 2023 FIA Formula One.|2108330|86",
"NEEDY STREAMER OVERLOAD|2022|WSS playground|Horror,Visual Novel,Adventure|PC,Mac||NEEDY STREAMER OVERLOAD is a 'multi-ending ADV' depicting daily life with 'OMGkawaiiAngel', a.|1451940|95",
"Two Worlds Epic Edition|2009|Reality Pump Studios|RPG,Open World,Adventure|PC,Mac,Linux|65|... 300 years after Aziraal has been banished, a brother and sister are drawn into the conflict.|1930|77",
"Armello|2015|League of Geeks|Strategy,Card Game,Turn-Based|PC,Mac,Linux|75|Armello is a grim fairy-tale board game come to life, with every match combining deep, tactical.|290340|82",
"Police Simulator: Patrol Officers|2022|Aesir Interactive|Simulation,Open World,Co-op|PC||Welcome to Brighton! Join the police force of this fictitious American city and experience the.|997010|78",
"Torque Drift|2021|Grease Monkey Games|Racing,Open World,Sports|PC||Build your car, earn sponsors, and compete in online multiplayer drift battles!|1029550|76",
"Tricolour Lovestory|2017|HL-Galgame|Visual Novel,Simulation,Adventure|PC||Time flies and never comes back. But with an incredible 1-million-word script and 100+ original.|668630|82",
"ICEY|2016|FantaBlade Network|Action,Hack and Slash,Adventure|PC,Mac|84|ICEY is a 2D side-scrolling action game and a META game in disguise. As you follow the.|553640|90",
"The Culling|2017|Xaviant|Survival,Action,Battle Royale|PC,Linux||Battle Royale is back! In a remote island paradise, 16 contestants have 25 minutes to explore.||57",
"BRAIN / OUT|2017|Desertkun|Shooter,Action,Survival|PC,Mac,Linux||Brain / Out is a multiplayer shooter with a nostalgic post-Soviet feel. Experience dynamic.|578310|82",
"Project CARS|2015|Slightly Mad Studios|Racing,Simulation,Sports|PC|83|THE ULTIMATE DRIVER JOURNEY delivers the soul of motor racing in the world's most beautiful.|234630|79",
"LET IT DIE|2018|GRASSHOPPER MANUFACTURE INC.|Action,Souls-like,Roguelike|PC||It's finally here! The survival action game that pits the strong against the weak is finally on.|794600|75",
"Resident Evil 0|2016|CAPCOM Co., Ltd.|Horror,Adventure,Action|PC||Before the mansion, before the destruction of Raccoon City, there was Resident Evil 0. Now.|339340|81",
"BATTALION: Legacy|2019|BULKHEAD|FPS,Shooter,Arcade|PC||BATTALION: Legacy recaptures the core of classic shooters in the final iteration of Battalion.|489940|60",
"60 Seconds! Reatomized|2019|Robot Gentleman|Tactics,Exploration,Immersive Sim|PC,Mac||The post-apocalyptic dark comedy is back - remastered and even more radioactive than before!.|1012880|94",
"Zombie Defense: The Last Frontier|2024|LilMemes Production|Action,Arcade,Shooter|PC||A Single and cooperative game for 4 players, you are a fighter of a special purpose unit, your.|2390840|",
"Project CARS 2|2017|Slightly Mad Studios|Racing,Simulation,VR|PC|84|THE ULTIMATE DRIVER JOURNEY! Project CARS 2 delivers the soul of motor racing in the world's.|378860|81",
"Reflex|2017|Easy game|Action,Puzzle|PC||A simple puzzle game. Simple graphics and nice music. Try your mind in more than 70+ levels..|745740|85",
"Relic Hunters Zero: Remix|2015|Rogue Snail|Shooter,Action,Adventure|PC,Mac,Linux||Relic Hunters Zero: Remix is a remaster of the FREE 1 million player hit game about blasting.|382490|93",
"Just Cause 4 Reloaded|2018|Avalanche Studios|Open World,Action,Adventure|PC|68|Rogue agent Rico Rodriguez journeys to Solis, a huge South American world home of conflict.|517630|62",
"100% Orange Juice|2014|Orange_Juice|Strategy,Card Game,Turn-Based|PC,Mac,Linux||100% Orange Juice is a digital multiplayer board game populated by developer Orange Juice's.|282800|92",
"Victoria II|2010|Paradox Development Studio|Strategy,Management,Simulation|PC|75|Carefully guide your nation from the era of absolute monarchies in the early 19th century.|42960|92",
"Prototype 2|2012|Radical Entertainment|Action,Open World,Adventure|PC|76|Become the ultimate shape-shifting weapon!||76",
"Empyrion - Galactic Survival|2020|Eleon Game Studios|Simulation,Co-op,Survival|PC||Build and explore in a true space sandbox survival adventure. Construct mighty capital vessels.|383120|79",
"My Friend Pedro|2019|DeadToast Entertainment|Action,Shooter,Platformer|PC|81|My Friend Pedro is a violent ballet about friendship, imagination, and one man's struggle to.|557340|96",
"Moonbase Alpha|2010|Virtual Heroes|Simulation,Co-op,Strategy|PC||NASA has once again landed on the lunar surface with the goal of colonization, research, and.||91",
"Trine 4: The Nightmare Prince|2019|Frozenbyte|Co-op,Action Adventure,Adventure|PC|81|The best-selling Trine series returns to the magic of 2.5D! Join three iconic heroes as they.|690640|89",
"Prime World|2014|Nival|MOBA,RPG,MMO|PC|65|Prime World is a free online game in RPG / MOBA genre with a unique universe where tactical.|235340|58",
"Cthulhu Saves the World|2011|Zeboyd Digital Entertainment LLC|JRPG,RPG,Turn-Based|PC|78|The lord of insanity, Cthulhu was all set to plunge the world into insanity and destruction.||92",
"Hardspace: Shipbreaker|2022|Blackbird Interactive|Simulation,Sandbox,Puzzle|PC|83|Equipped with cutting-edge salvaging tech, carve & slice spaceships to recover valuable.|1161580|89",
"Scribble It!|2020|Detach Entertainment|Co-op|PC,Mac,Linux||Scribble It! is a multiplayer drawing and guessing game. Get in a lobby with up to 16 players.|1088150|86",
"Blood Bowl 2: Legendary Edition (Classic)|2017|Cyanide Studios|Strategy,Turn-Based,Tactical|PC,Mac|76|Blood Bowl 2 smashes Warhammer and American football together, in an explosive cocktail of.|236690|79",
"Solasta: Crown of the Magister|2021|Tactical Adventures|RPG,Turn-Based,Adventure|PC,Mac||Roll for initiative, take attacks of opportunity, manage player location and the verticality of.|1096530|87",
"World of Warplanes|2022|Wargaming Group Limited|FPS,TPS,Shooter|PC|69|World of Warplanes is an aerial combat MMO action game set in the Golden Age of military.|790710|71",
"Sally Face - Episode One|2016|Portable Moose|Adventure,Horror,Puzzle|PC,Mac,Linux||Delve into a dark adventure following the boy with a prosthetic face and a tragic past. Unravel.|541570|97",
"Dorfromantik|2022|Toukana Interactive|Puzzle,City Builder,Strategy|PC,Mac||Dorfromantik is a peaceful building strategy and puzzle game where you create a beautiful and.|1455840|97",
"Darksiders Genesis|2019|Airship Syndicate|Action,Adventure,Co-op|PC|77|DARKSIDERS: GENESIS gives players their first look at the world of DARKSIDERS before the events.|710920|82",
"Real Pool 3D - Poolians|2018|Poolians.com|Sports,Simulation,MMO|PC||Real Pool 3D (Poolians) is one of the best online pool games. Play against the computer or real.||77",
"HUMANKIND|2021|AMPLITUDE Studios|Strategy,City Builder,Management|PC,Mac||Rewrite history by shaping a civilization as unique as you are. Combine 60 cultures from the.|1124300|68",
"X-Plane 11|2017|Laminar Research|Simulation,Open World,VR|PC,Mac,Linux||The future of flight simulation is now! X-Plane 11 is the detailed, realistic, and modern.|269950|93",
"Portal 2 Sixense Perceptual Pack|2013|Unknown|Adventure,Action,Puzzle|PC||Portal 2 Sixense Perceptual Pack is a free stand-alone game, developed with the Intel.||57",
"Road Redemption|2017|Redemption Road|Racing,Beat 'em up,Action|PC,Mac,Linux||Road Redemption lets you lead a biker gang on an epic journey across the country in this.|300380|82",
"Dark Deception|2018|Glowstick Entertainment|Horror,Action,Survival|PC||Death awaits you in Dark Deception, a story-driven first-person horror maze game. There's.|332950|89",
"Euro Truck Simulator|2013|SCS Software|Simulation,Racing,Open World|PC,Mac||The original Euro Truck Simulator - the game which has become the classic of the genre and is.|232010|84",
"KartRider: Drift|2023|NEXON Korea Corporation|Racing,Arcade,MMO|PC|76|KartRider: Drift is the only online free-to-play, cross-platform kart racer with deep kart and.|1184140|73",
"VEGA Conflict|2015|KIXEYE|MMO,Strategy,Open World|PC,Mac||Stake your claim, command your fleets, and wage epic war in space.|339600|59",
"Forts|2017|EarthWork Games|Strategy,Sandbox,Action|PC|74|Unleash your creativity and strategic prowess in Forts, the exhilarating physics-based RTS!.|410900|92",
"We Were Here Expeditions: The FriendShip|2023|Total Mayhem Games|Co-op,Puzzle,Adventure|PC|82|Partner up with your friend online and set sail for an unforgettable puzzle adventure in this.|2296990|91",
"Salt and Sanctuary|2016|Ska Studios|Souls-like,Metroidvania,RPG|PC,Mac,Linux|84|Explore a haunting, punishing island in this stylized 2D action RPG. Salt and Sanctuary.|283640|90",
"Clustertruck|2016|Landfall|Action,Platformer,Strategy|PC,Mac,Linux|76|Clustertruck is a chaotic physics based truckformer. Jump your way through insane levels in a.|397950|94",
"Far Cry Primal|2016|Ubisoft|Open World,Survival,Action|PC|74|The award-winning Far Cry franchise returns with its innovative open world gameplay, bringing.|371660|86",
"20 Minutes Till Dawn|2023|flanne|Shoot 'em up,Survival,Roguelike|PC,Mac||20 Minutes Till Dawn is a survival roguelite where endless hordes of creatures lurk from the.|1966900|91",
"Red Faction Guerrilla Steam Edition|2009|Volition|Open World,Action,TPS|PC|82|Set 50 years after the climactic events of the original Red Faction, Red Faction: Guerrilla.|20500|90",
"Tricky Towers|2016|WeirdBeard|Party,Puzzle,Arcade|PC,Mac,Linux|80|With your brilliant robe and magic powers, it's time to build some Tricky Towers! Stack your.|437920|90",
"Stronghold Crusader HD (2012)|2013|Firefly Studios|City Builder,Colony Sim,Strategy|PC|78|The highly anticipated sequel to the best-selling Stronghold, Stronghold Crusader HD throws you.|40970|98",
"Dune: Spice Wars|2023|Shiro Games|Management,Strategy,RTS|PC||A 4X real-time strategy game from the developers of the critically acclaimed Northgard. Set in.|1605220|80",
"Scribblenauts Unlimited|2012|5th Cell Media|Puzzle,Adventure,Sandbox|PC|75|The best-selling, award-winning franchise is back - on your home PC in gorgeous HD for the.||94",
"Iron Harvest|2020|KING Art|RTS,Strategy,Co-op|PC|75|A classic real-time strategy game with an epic single player campaign, multiplayer & coop, set.|826630|73",
"eFootball PES 2020|2019|Konami Digital Entertainment|Sports,Simulation,Co-op|PC||Experience unparalleled realism and authenticity in this year's definitive football game: PES.|996470|71",
"NBA 2K23|2022|Visual Concepts|Immersive Sim,Sports,Simulation|PC||Rise to the occasion in NBA 2K23. Showcase your talent in MyCAREER. Pair All-Stars with.|1919590|62",
"Mount & Blade: With Fire & Sword|2011|TaleWorlds Entertainment|RPG,Open World,Action|PC|68|The standalone expansion for Mount & Blade! With Fire & Sword builds and expands upon the.|48720|88",
"WorldBox - God Simulator|2021|Maxim Karpenko|Sandbox,Simulation,Colony Sim|PC,Mac,Linux||WorldBox is the ULTIMATE god simulator and sandbox game. A petri dish for your fantasy.|1206560|95"
]);
