/* Postgame - game catalogue, part 16
   Harvested from Steam. Rows carry two extra fields: the Steam app id
   (for the 600x900 capsule) and the percentage of Steam reviews that
   are positive. */
window.GAME_ROWS = (window.GAME_ROWS || []).concat([
"Torchlight|2009|Runic Games|RPG,Action RPG,Hack and Slash|PC,Mac|83|Adventure awaits in the award-winning Action RPG debut from Runic Games! Explore the randomized.|41500|91",
"Tribes: Ascend|2012|Hi-Rez Studios|FPS,Action,Shooter|PC|86|This edition packages weapon DLC from ten previous expansions as well new featured content.||81",
"Orcs Must Die! 3|2021|Robot Entertainment|Tower Defence,Co-op,Strategy|PC||Slice, burn, toss, zap, grind and gib massive hordes of repugnant orcs in this long-awaited.|1522820|86",
"The Last Remnant|2009|Square Enix|JRPG,RPG,Turn-Based|PC|66|Mitra, yama, qsiti, sovani... These four races exist in one world. A world filled with Remnants.||81",
"Freebie|2016|Free Games Info|Arcade|PC||Freebie is a casual game where you launch a ball against a paddle and hit a green surface. Be.||74",
"Aliens vs. Predator|2010|Rebellion|Action,FPS,Horror|PC|68|Survive, hunt and prey in the deadly jungles and swamps in distinctly new and thrilling first.|10680|91",
"MapleStory|2012|NEXON Korea Corporation|MMO,Platformer,Co-op|PC,Mac||Join over 260 million players worldwide in MapleStory, the world's biggest 2D MMORPG adventure!.|216150|63",
"Armored Warfare|2017|Obsidian Entertainment|Shooter,Co-op,Strategy|PC||Wage war against players from around the world with an unstoppable arsenal of 300+ powerful.|443110|65",
"The Surge|2017|Deck13|Souls-like,Action,RPG|PC|72|Welcome to CREO, the megacorporation saving the world! A catastrophic event has knocked you out.|378540|75",
"Warhammer 40,000: Inquisitor - Martyr|2018|NeocoreGames|Action RPG,RPG,Hack and Slash|PC|67|Enter the Chaos-infested Caligari Sector and purge the unclean with the most powerful agents of.|527430|76",
"Artifact|2018|Valve|Card Game,Strategy,Tactical|PC,Mac,Linux|76|Artifact now features two games: Artifact Classic, the original Dota 2 trading card game, and.|583950|47",
"Dungeons & Dragons Online|2012|Standing Stone Games|RPG,MMO,Adventure|PC||Enter a world of danger and adventure with Dungeons & Dragons Online based on the beloved RPG.|206480|71",
"Fortified|2016|Siege Camp|Action,Tower Defence,Co-op|PC||Fortified is an explosive strategy shooter where players will defend the Earth against a.||75",
"INVAXION|2018|Nanjing AQUATRAX|Rhythm,Racing|PC||Classic music gameplay with a whole new game experience! Players will play as a member of the.||53",
"WAKFU|2014|Ankama Studio|MMO,Strategy,RPG|PC,Mac,Linux|76|Immerse yourself in the WAKFU universe with this free to play MMORPG. Select your class, travel.|215080|76",
"Arma: Cold War Assault Remastered|2011|Bohemia Interactive|Simulation,Action,Strategy|PC,Linux||The genre-defining military sim that began as Operation Flashpoint (2001), now a modernized.|65790|80",
"School of Dragons|2014|JumpStart Games, Inc.|Adventure,MMO,RPG|PC||Fly fast, train hard, and learn well to become the Ultimate Dragon Trainer! Join Chief Hiccup.|332070|62",
"METAL GEAR SOLID V: GROUND ZEROES|2014|KONAMI|Stealth,Action,Tactical|PC|80|World-renowned Kojima Productions brings the Metal Gear Solid franchise to Steam with METAL.||84",
"Outlast 2|2017|Red Barrels|Horror,Survival,Action|PC|75|Outlast 2 introduces you to Sullivan Knoth and his followers, who left our wicked world behind.|414700|91",
"RUNNING WITH RIFLES|2015|Osumia Games|Action,Tactical,Open World|PC,Mac,Linux|78|RUNNING WITH RIFLES is a top-down tactical shooter with open world RPG elements. In RWR, you.|270150|88",
"Deponia: The Complete Journey|2014|Daedalic Entertainment|Adventure,Point and Click,Puzzle|PC,Mac,Linux||Junk, junk and even more junk. Life on the trash-planet Deponia is anything but a walk in the.|292910|86",
"Farming Simulator 17|2016|GIANTS Software|Farming,Simulation,Open World|PC,Mac|69|Take on the role of a modern farmer in Farming Simulator 17! Explore farming possibilities in a.|447020|93",
"Lord of the Rings: War in the North|2011|Snowblind Studios|RPG,Action,Co-op|PC|66|Work together or die alone in this epic quest to turn the tides in the War of the Ring.||81",
"GOD EATER 3|2019|BANDAI NAMCO Studios Inc.|Action,Hack and Slash,Co-op|PC|71|Set in a post-apocalyptic setting, it's up to your special team of God Eaters to take down.|899440|80",
"Shadow Tactics: Blades of the Shogun|2016|Mimimi Games|Stealth,Strategy,Tactical|PC,Mac,Linux|85|Shadow Tactics is a hardcore tactical stealth game set in Japan around the Edo period. A new.|418240|96",
"ArcheBlade|2014|CodeBrush Games|Action,Fighting,MMO|PC||ArcheBlade is a free to play 3D multiplayer fighting game that captures the essence of.||73",
"Warhammer 40,000: Dawn of War II Chaos Rising|2010|Relic Entertainment|Strategy,RTS,Tactical|PC,Mac,Linux|84|In Dawn of War II: Chaos Rising you will take command of the Blood Ravens and defend the sector.|20570|91",
"Dead Island Definitive Edition|2016|Techland|Open World,Co-op,Survival|PC,Linux||Welcome to the zombie apocalypse experience of a lifetime - and now more beautiful than ever..|383150|82",
"Bright Memory: Infinite|2021|FYQD-Studio|Action,FPS,Shooter|PC||Bright Memory: Infinite is an all-new lightning-fast fusion of the FPS and action genres.|1178830|92",
"Stormgate|2025|Frost Giant Studios|RTS,Strategy,Action|PC||Stormgate is a free-to-play real-time strategy game with a full single-player campaign.|2012510|50",
"Evolvation|2017|Eric Ruts|MMO,Action,Simulation|PC,Linux||Evolvation is a casual multiplayer and fast-paced and class based space flying shooter.||68",
"Heroes of Might & Magic III - HD Edition|2015|Dotemu|Strategy,RPG,Turn-Based|PC|65|The most popular Heroes title of all time is back in HD! Fifteen years later, rediscover the.|297000|79",
"Town of Salem|2014|BlankMediaGames|Strategy,Mystery,Social Deduction|PC,Mac||Inspired by the party games Werewolf and Mafia, Town of Salem is a game of murder, mystery and.|334230|88",
"Turbo Pug|2015|Space Cat Studios|Platformer|PC||It's time to unleash your inner pug! Turbo Pug is a casual runner with difficult, random.||91",
"The Elder Scrolls: Legends|2017|Sparkypants Studios, LLC|Card Game,Strategy,Tactical|PC,Mac||The Elder Scrolls: Legends is an award- winning free-to-play strategy card game based on the.|364470|75",
"The Evil Within 2|2017|Tango Gameworks|Horror,Adventure,Open World|PC|80|Detective Sebastian Castellanos has lost everything, including his daughter, Lily. To save her.|601430|92",
"Car Mechanic Simulator 2021|2021|Red Dot Games|Simulation,Sandbox,Racing|PC||Work your way to a service empire. Get your hands dirty in a highly realistic simulation game.|1190000|96",
"Dragons and Titans|2014|Wyrmbyte|MOBA,RPG,Action|PC,Mac,Linux|43|Dragons and Titans is a fast paced MOBA with classic RPG elements. Select from over 30 unique.||79",
"MudRunner|2017|Saber Interactive|Simulation,Racing,Open World|PC||MudRunner is the ultimate off-road experience putting the players in the driver seat and dares.|675010|91",
"DmC: Devil May Cry|2013|Ninja Theory|Action,Hack and Slash,Adventure|PC|85|In this retelling of Dante's origin story which is set against a contemporary backdrop, DmC.|220440|93",
"Panzar|2013|Panzar Studio|Action,MMO,RPG|PC||PANZAR is a fantasy multiplayer third-person shooter. You get to choose from eight unique.|240320|66",
"Catan Universe|2017|Client/Frontend: Endava / Backend: SuperNimbus|Strategy,Card Game|PC,Mac||Trade - build - settle: Become Lord of Catan! Get to know Catan and play the starter scenario.|544730|49",
"Paint the Town Red|2021|South East Games|Action,Fighting,Roguelike|PC,Mac,Linux||Paint the Town Red is a chaotic first person melee combat game set in different locations and.|337320|96",
"Sherlock Holmes: The Devil's Daughter|2016|Frogwares|Adventure,Detective,Mystery|PC|65|Experience a fantastic adventure with unique gameplay that blends investigation, action and.|350640|80",
"Brick Rigs|2023|Fluppisoft GmbH|Sandbox,Open World,Racing|PC,Linux||Do whatever you want in a physics sandbox full of chaotic destruction, endless player-made.|552100|95",
"Ghostwire: Tokyo|2022|Tango Gameworks|Open World,Horror,Action Adventure|PC|77|Tokyo's population has vanished, and deadly supernatural forces prowl the streets. Use an.|1475810|82",
"Orcs Must Die! Unchained|2017|Robot Entertainment|Tower Defence,Co-op,Action|PC|87|Orcs Must Die! Unchained takes the award-winning Orcs Must Die! action tower defense game to a.||69",
"X4: Foundations|2018|Egosoft|Simulation,Sandbox,Management|PC,Linux||Your journey to building a vast space empire begins behind the controls of a single ship..|392160|79",
"BrainBread 2|2022|Reperio Studios|FPS,Survival,Action|PC,Mac,Linux||Grab a weapon, demolish your enemies, level up, become more powerful, let the gore flow, let.|346330|73",
"Sid Meier's Civilization III Complete|2006|Firaxis Games|Strategy,Turn-Based,Simulation|PC|90|Sid Meier's Civilization III: Complete, the latest offering in the Sid Meier's Civilization III.|3910|90",
"Saving Grace|2021|Thomas JC Ironmonger|Horror,FPS,Hack and Slash|PC||A first-person horror game revolving around the abduction of your daughter Grace. Cultists.|1380400|",
"Assetto Corsa Competizione|2019|Kunos Simulazioni|Racing,Simulation,VR|PC|77|Assetto Corsa Competizione, the official GT World Challenge videogame. Thanks to the.|805550|93",
"Serious Sam HD: The First Encounter|2009|Croteam|FPS,Action,Shooter|PC|68|Serious Sam HD: The First Encounter is a visually upgraded and fully Steam supported remake.|41000|93",
"The Planet Crafter|2024|Miju Games|Survival,Co-op,Open World|PC||A space survival open world terraforming crafting game, designed for 1 to 10 players. Alter the.|1284190|96",
"Tower of Fantasy|2022|Hotta Studio|MMO,Open World,RPG|PC||Embark together on your fantasy adventure! Set hundreds of years in the future on the distant.|2064650|69",
"Trailmakers|2019|Flashbulb|Action,Co-op,Adventure|PC||Build the ultimate vehicle and explore a vast open world filled with challenges and adventure..|585420|92",
"DREDGE|2023|Black Salt Games|Exploration,Adventure,Open World|PC,Mac||DREDGE is a single-player fishing adventure with a sinister undercurrent. Sell your catch.|1562430|96",
"Inside the Backrooms|2022|MrFatcat|Horror,Puzzle,Co-op|PC||Inside the Backrooms is a horror multiplayer game mixed with different mechanics that will make.|1987080|82",
"CS2D|2017|Unreal Software|Shooter,Action,FPS|PC,Linux||CS2D is a free fast-paced top-down multiplayer shooter. Featuring many different game modes, a.|666220|90",
"Tropico 5|2014|Haemimont Games|Strategy,City Builder,Simulation|PC,Linux|75|Return to the remote island nation of Tropico and expand your Dynasty's reign from the early.|245620|79",
"Hand Simulator|2017|HFM Games|Simulation,VR,Horror|PC||There are many different levels where you can play with spinners, plunge into the subtleties of.|657200|84",
"Hitman 2: Silent Assassin|2007|Io-Interactive A/S|Stealth,Action,Shooter|PC|87|Enter the realm of a retired assassin, forced back into action by treason. You may be a hired.|6850|83",
"Call of Duty: Ghosts|2014|Infinity Ward|FPS,Action,Shooter|PC|68|Outnumbered and outgunned, but not outmatched.Call of Duty: Ghosts is an extraordinary step.|209160|64",
"Cruelty Squad|2021|Consumer Softproducts|Immersive Sim,FPS,Horror|PC||An immersive power fantasy simulator with tactical stealth elements set in a sewage infused.|1388770|97",
"Age of History II|2018|Łukasz Jakowski|Strategy,Turn-Based,Simulation|PC||Age of History II is a grand strategy wargame that is simple to learn yet hard to master.Your.|603850|90",
"Star Wars - The Force Unleashed Ultimate Sith Edition|2009|LucasArts|Action,Hack and Slash,Adventure|PC,Mac|65|A game that will show gamers the deepest, darkest side of the Force in a story that puts them.||76",
"Knights and Merchants|2013|Topware Interactive|Strategy,Colony Sim,City Builder|PC,Mac,Linux||KNIGHTS and MERCHANTS recreates the era of the Middle Ages. Apart from the purely fictitious.|253900|85",
"Unrailed!|2020|Indoor Astronaut|Co-op,Action,Survival|PC,Mac,Linux|77|Unrailed! is a co-op multiplayer game where you have to work together with your friends to.|1016920|93",
"Bright Memory|2020|FYQD-Studio|FPS,Hack and Slash,Shooter|PC||Bright Memory is a lightning-fast fusion of the FPS and action genres, created by one-man.|955050|90",
"Demonologist|2023|Clock Wizard Games|Horror,Co-op,Mystery|PC||Demonologist is a Co-Op horror game that can be played with at least 1 and up to 4 players..|1929610|86",
"Crysis 3 Remastered|2022|Crytek|Action,FPS,Shooter|PC||Experience the single-player experience from the iconic first-person shooter, Crysis 3.|2096610|88",
"Transport Fever|2016|Urban Games|City Builder,Sandbox,Racing|PC,Mac,Linux|71|Transport Fever is a railroad-focused tycoon game. Players start in 1850 and build up a.|446800|83",
"How to Survive|2014|Eko Software|Survival,Action,Co-op|PC|60|'A real Gem' - Destructoid at E3 'Offers a different experience for zombie game veterans' -.|250400|83",
"Warm Snow|2022|BadMudStudio|Roguelike,Action Adventure,RPG|PC||'Warm Snow' is a Rogue-like action game with a background set in a dark fantasy world, where.|1296830|93",
"Wobbly Life|2025|RubberBandGames|Adventure,Open World,Simulation|PC||Wobbly Life is a vibrant open-world physics sandbox. Play with your friends online or in local.|1211020|97",
"EARTH DEFENSE FORCE 4.1 The Shadow of New Despair|2016|SANDLOT|Action,TPS,Co-op|PC|79|It's a fight for the future of the planet between the Ravagers, a merciless swarm of alien.|410320|95",
"Killer is Dead - Nightmare Edition|2014|KADOKAWA GAMES / GRASSHOPPER MANUFACTURE|Action,Hack and Slash,Adventure|PC||Get ready for some seriously stylish action from renowned designer SUDA51. In this exclusive.|261110|75",
"Star Wars Knights of the Old Republic II - The Sith Lords|2012|Obsidian Entertainment|RPG,Adventure,Action|PC,Mac,Linux||5 years after the events of the award winning original, the Sith are on the verge of crushing.|208580|94",
"SCARLET NEXUS|2021|BANDAI NAMCO Studios Inc.|Action,RPG,JRPG|PC|78|Choose between Yuito and Kasane, elite psionics each armed with a talent in psychokinesis and.|775500|81",
"Day of Infamy|2017|New World Interactive|FPS,Shooter,Action|PC,Mac,Linux|77|Experience close-quarters battles in iconic WWII settings. Defend the line, storm the beach.|447820|82",
"PlateUp!|2022|It's happening|Co-op,Management,Roguelike|PC||Cook and serve your dishes, design and decorate your restaurants, and expand your culinary.|1599600|95",
"Beholder|2016|Alawar Stargaze (Warm Lamp Games)|Strategy,Simulation,Adventure|PC,Mac,Linux|75|You're a state-installed landlord in a totalitarian country. Place listening devices, steal and.|475550|92",
"Bloons TD Battles|2016|Ninja Kiwi|Tower Defence,Strategy,Action|PC,Mac||Go head to head with other players in a Bloon-popping battle for victory. From the creators of.|444640|91",
"Super Animal Royale|2021|Pixile|Battle Royale,Co-op,Shooter|PC,Mac||Welcome to the coziest way to kill your friends. Super Animal Royale is a 64-player, top-down.|843380|94",
"Rome: Total War - Collection|2007|CREATIVE ASSEMBLY|Strategy,RTS,Tactical|PC|92|Control and conquer the greatest empire ever known to man.|4760|95",
"Lobotomy Corporation / Monster Management Simulation|2018|ProjectMoon|Management,Horror,Adventure|PC||A roguelite monster-management simulation inspired by the likes of the SCP Foundation, Cabin in.|568220|94",
"Baldur's Gate II: Enhanced Edition|2013|Beamdog|RPG,Adventure,Open World|PC,Mac,Linux|78|Return to a timeless RPG masterpiece. Baldur's Gate II: Enhanced Edition brings the classic.|257350|92",
"Alan Wake's American Nightmare|2012|Remedy Entertainment|Action,Adventure,Horror|PC|73|A thrilling new storyline, hordes of creepy enemies, serious firepower and beautiful Arizona.|202750|73",
"Sniper: Ghost Warrior 2|2013|City Interactive|Action,FPS,Shooter|PC|52|Sniper: Ghost Warrior 2 takes the bulls-eye precision of its predecessor to new and exciting.|34870|76",
"Deadlink|2023|Gruby Entertainment|FPS,Roguelike,Shooter|PC|80|Get ready to put a sizable dent in the profits of megacorporations in Deadlink, a guns-blazing.|1676130|90",
"World War Z|2021|Saber Interactive Inc|Co-op,Action,Shooter|PC||World War Z is a heart-pounding coop third-person shooter for up to 4 players featuring massive.|699130|83",
"JUMP FORCE|2019|Spike Chunsoft Co., Ltd.|Fighting,Action,RPG|PC|60|Create your own avatar to fight alongside the most powerful Manga heroes in an original Story.|816020|73",
"Darksiders Warmastered Edition|2016|KAIKO|Action,Hack and Slash,Adventure|PC||Deceived by the forces of evil into prematurely bringing about the end of the world, War - the.|462780|88",
"Bless Online|2018|NEOWIZ BLESS STUDIO|MMO,RPG,Adventure|PC||Live your own adventure in the breathtaking world of Bless Online! Fight for your faction in.|681660|37",
"Civilization IV: Beyond the Sword|2007|Firaxis Games|Strategy,Turn-Based|PC,Mac|86|Sid Meier's Civilization IV: Beyond the Sword is the second expansion pack for Civilization IV.||95",
"Overcooked|2016|Ghost Town Games Ltd.|Co-op,Simulation,Action|PC|81|Overcooked is a chaotic couch co-op cooking game for one to four players. Working as a team.|448510|90",
"Craftopia|2020|Pocketpair|Open World,Survival,Sandbox|PC||Craftopia is the brand new multiplayer survival action game made in Japan. We combined many.|1307550|76",
"Medieval Dynasty|2021|Render Cube|Co-op,Survival,Open World|PC|73|Hunt, survive, build and lead in the harsh Middle Ages: Create your own Medieval Dynasty and.|1129580|91",
"Steep|2016|Ubisoft Annecy|Sports,Open World,Action|PC|72|Ride a massive open world across the Alps, where the powder is always fresh and the run never.|460920|82",
"Red Faction: Armageddon|2011|Volition|Action,TPS,Shooter|PC|74|Red Faction: Armageddon Path to War includes 4 new missions, 2 unlockable items and 10 new.|55110|73"
]);
