/* Postgame - game catalogue, part 12
   Harvested from Steam. Rows carry two extra fields: the Steam app id
   (for the 600x900 capsule) and the percentage of Steam reviews that
   are positive. */
window.GAME_ROWS = (window.GAME_ROWS || []).concat([
"Halo: The Master Chief Collection|2019|343 Industries|FPS,Adventure,Co-op|PC||The Master Chief's iconic journey includes six games, built for PC and collected in a single.|976730|92",
"Z1 Battle Royale: Test Server|2016|Daybreak Game Company|MMO,Survival,Shooter|PC||Z1 Battle Royale is a Free to Play, fast-paced, action arcade, competitive Battle Royale..||52",
"People Playground|2019|mestiez|Sandbox,Simulation,Horror|PC||Shoot, stab, burn, poison, tear, vaporise, or crush ragdolls in a large open space.|1118200|99",
"Eternal Return|2023|Nimble Neuron|MOBA,Survival,Action|PC||Eternal Return is a free-to-play, 2.5D perspective Battle Royale game. Search, Craft, Hunt, and.|1049590|79",
"Half-Life 2: Episode One|2006|Valve|FPS,Action,Adventure|PC,Linux|87|Half-Life 2 has sold over 4 million copies worldwide, and earned over 35 Game of the Year.|380|96",
"Half-Life Deathmatch: Source|2006|Valve|Action,FPS,Shooter|PC,Linux||Half-Life Deathmatch: Source is a recreation of the first multiplayer game set in the Half-Life.|360|75",
"Cry of Fear|2013|Team Psykskallar|Horror,Co-op,Action|PC||Cry of Fear is a psychological single-player and co-op horror game set in a deserted town.||89",
"SCUM|2025|Gamepires|Survival,Open World,MMO|PC||Welcome to SCUM, a ruthless open-world survival game where deep character customization defines.|513710|75",
"Splitgate|2019|1047 Games|FPS,Shooter,Action|PC,Linux||Splitgate is a free-to-play, fast-paced multiplayer shooter that features player-controlled.|677620|92",
"Stumble Guys|2021|Scopely|Battle Royale,Racing,Co-op|PC||Ready for the chaos? Stumble Guys is a 32-player, fast-paced multiplayer party royale where.|1677740|85",
"Neverwinter|2013|Cryptic Studios|MMO,RPG,Adventure|PC|74|Neverwinter is a free, action MMORPG based on the acclaimed Dungeons & Dragons fantasy.|109600|78",
"Half-Life 2: Episode Two|2007|Valve|FPS,Action,Shooter|PC,Linux|90|Half-Life 2: Episode Two is the second in a trilogy of new games created by Valve that extends.|420|97",
"Business Tour Board Game with Online Multiplayer|2017|8Floor|Strategy,MMO,Co-op|PC,Mac||Business Tour is a free-to-play multiplayer tabletop game. Build your own monopoly, play with.|397900|61",
"Divinity: Original Sin 2 - Definitive Edition|2017|Larian Studios|Tactics,RPG,Strategy|PC,Mac|93|The critically acclaimed RPG that raised the bar, from the creators of Baldur's Gate 3. Gather.|435150|96",
"Football Manager 2020|2019|Sports Interactive|Simulation,Sports,Management|PC,Mac|84|Run your football club, your way. Every decision counts in Football Manager 2020 with new.|1100600|89",
"Dying Light 2 Stay Human: Reloaded Edition|2022|Techland|Open World,Co-op,Horror|PC||Humanity is fighting a losing battle against the virus. Experience a post-apocalyptic open.|534380|79",
"Russian Fishing 4|2021|FishSoft LLC|Simulation,Immersive Sim,Sports|PC||Russian Fishing 4 is a fishing simulator with RPG elements. There is no story line and the.|766570|54",
"Counter-Strike Nexon|2014|Valve|FPS,Sandbox,Shooter|PC||Counter-Strike Nexon is a Free to Play MMOFPS offering competitive PvP and PvE action including.|273110|66",
"The Cycle: Frontier|2022|YAGER|Survival,Shooter,Tactical|PC||The Cycle: Frontier is a free-to-play PvPvE Extraction Shooter driven by suspense and danger..|868270|64",
"Infestation: The New Z|2016|Fredaikis AB|Survival,Open World,MMO|PC||The New Z is a FREE TO PLAY multi-game mode experience. SURVIVE with friends and gather loot.|555570|54",
"theHunter: Call of the Wild|2017|Expansive Worlds|Open World,Stealth,FPS|PC||Discover an atmospheric hunting game like no other in this realistic, stunning open world -.|518790|89",
"Tom Clancy's The Division|2016|Massive Entertainment|Open World,Shooter,TPS|PC||A tactical open world third-person shooter set in New York after a deadly pandemic. Team up or.|365590|70",
"POSTAL 2|2012|Running With Scissors|Open World,Sandbox,FPS|PC,Linux|59|Live a week in the life of The POSTAL Dude; a hapless everyman just trying to check off some.|223470|97",
"AdVenture Capitalist|2015|Hyper Hippo Games|Simulation,Management,Point and Click|PC,Mac,Linux||Welcome, eager young investor, to AdVenture Capitalist! Arguably the world's greatest.|346900|88",
"DAVE THE DIVER|2023|MINTROCKET|Management,Adventure,Exploration|PC,Mac|90|DAVE THE DIVER is a casual, singleplayer adventure RPG featuring deep-sea exploration and.|1868140|97",
"For Honor|2017|Ubisoft Montreal|Action,Fighting,Co-op|PC|76|Fight alone or with friends in For Honor, a third-person hero-based melee fighting game. Enter.|304390|70",
"Loadout|2014|Edge of Reality|TPS,Action,Shooter|PC|72|Loadout is an outrageous new multi-player shooter that's all about the guns, baby! Build a.||87",
"APB Reloaded|2011|Little Orbit|Open World,Action,MMO|PC||The world's first and premier Action MMO Third Person Shooter allows you to choose between two.|113400|64",
"Saints Row IV: Re-Elected|2013|Deep Silver Volition|Open World,Action,Co-op|PC,Linux|86|Experience the insane antics of Saints Row IV. The Saints have gone from the Penthouse to the.|206420|88",
"Fishing Planet|2017|Fishing Planet LLC|Simulation,Sports,MMO|PC,Mac,Linux||Fishing Planet is a highly realistic first-person online multiplayer fishing simulator..|380600|87",
"Braveland|2014|Tortuga Team|Strategy,Turn-Based,Tactics|PC,Mac,Linux||Braveland is a turn-based game inspired by old-school strategies with hexagonal battlefield..|285800|82",
"DCS World Steam Edition|2013|Eagle Dynamics SA|Simulation,VR,Open World|PC||Feel the excitement of flying the Su-25T Frogfoot attack jet and the TF-51D Mustang in the.|223750|85",
"Crossout|2017|Targem Games|Action,Sandbox,Shooter|PC||Crossout - the postapocalyptic MMO action game where you can create a unique design for an.|386180|75",
"Poppy Playtime|2021|Mob Entertainment|Horror,Puzzle,Mystery|PC||You must stay alive in this horror/puzzle adventure. Try to survive the vengeful toys waiting.|1721470|85",
"Albion Online|2018|Sandbox Interactive GmbH|MMO,Open World,Sandbox|PC,Mac,Linux||Albion Online is a fantasy sandbox MMORPG featuring a player-driven economy, classless combat.|761890|79",
"Divide By Sheep|2015|Victor Solodilov|Puzzle,Adventure,Shooter|PC,Mac|83|Divide By Sheep is a mind-bending math puzzler about friendship and slicing sheep in half with.|252130|91",
"Starbound|2016|Chucklefish|Survival,Sandbox,Adventure|PC,Mac,Linux|81|You've fled your home, only to find yourself lost in space with a damaged ship. Your only.|211820|92",
"Totally Accurate Battle Simulator|2021|Landfall|Sandbox,Simulation,Strategy|PC,Mac||Be the leader of wobblers from ancient lands, spooky places, and fantasy worlds. Watch them.|508440|98",
"Magicka|2011|Arrowhead Game Studios|Co-op,Action,RPG|PC|74|Magicka is a satirical action-adventure game set in a rich fantasy world based on Norse.|42910|86",
"Need for Speed Heat|2020|Ghost Games|Racing,Open World,Action|PC|72|Hustle by day and risk it all at night in Need for Speed Heat Deluxe Edition, a white-knuckle.|1222680|84",
"The Descendant|2016|Gaming Corps AB|Adventure,Point and Click,Horror|PC,Mac|59|In THE DESCENDANT, the end of the world is only the start. With what remains of humanity.|351940|89",
"Killing Floor|2009|Tripwire Interactive|FPS,Co-op,Survival|PC,Mac,Linux|72|6-player co-op survival horror at its finest! Free updates, free special events and a.|1250|95",
"Alien Swarm|2010|Valve|Co-op,Action,Shooter|PC|77|Co-operative multiplayer game and complete code base available for free.|630|95",
"DISTRAINT: Deluxe Edition|2015|Jesse Makkonen|Horror,Adventure,Puzzle|PC|76|DISTRAINT is a 2D psychological horror adventure game for PC. In order to secure a partnership.|395170|93",
"Crosshair X|2020|CenterPoint Gaming|Action,Adventure,Shooter|PC||Improve your aim and accuracy in every shooter you play. Crosshair X overlays a custom.|1366800|93",
"House Flipper|2018|Empyrean|Simulation,Sandbox,Immersive Sim|PC,Mac|67|House Flipper is a unique chance to become a one-man renovation crew. Buy, repair and remodel.|613100|94",
"Party Animals|2023|Recreate Games|Party,Co-op,Fighting|PC||Fight your friends as puppies, kittens and other fuzzy creatures in PARTY ANIMALS! Paw it out.|1260320|78",
"Arma 2: Operation Arrowhead|2010|Bohemia Interactive|Simulation,Action,Tactical|PC|73|Three years after the conflict in Chernarus, portrayed in the original Arma 2, a new flashpoint.|33930|92",
"The Lord of the Rings Online|2012|Standing Stone Games|MMO,Open World,RPG|PC||Join the world's greatest fellowship of players in the award-winning online re-creation of J..|212500|81",
"PAYDAY The Heist|2011|OVERKILL - a Starbreeze Studio.|FPS,Action,Co-op|PC|76|Take on the role of a hardened career criminal executing intense, dynamic heists in constant.|24240|93",
"FIFA 22|2021|EA Canada & EA Romania|Sports,Simulation,Co-op|PC||Powered by Football, EA SPORTS FIFA 22 brings the game even closer to the real thing with.|1506830|80",
"Ultimate Custom Night|2018|Scott Cawthon|Horror,Strategy,Survival|PC||Welcome to the ultimate FNAF mashup, featuring 50 selectable characters and custom difficulties!|871720|95",
"Broforce|2015|Free Lives|Action,Co-op,Platformer|PC,Mac,Linux|83|Broforce is an action-packed side-scrolling run 'n' gun ode to freedom, putting you in control.|274190|97",
"Vampire: The Masquerade - Bloodhunt|2022|Sharkmob AB|Battle Royale,TPS,Survival|PC||Bloodhunt is a thrilling free-to-play battle royale game set in Prague consumed by a ruthless.|760160|76",
"American Truck Simulator|2016|SCS Software|Racing,Open World,Simulation|PC,Mac,Linux|76|Experience legendary American trucks and deliver various cargoes across sunny California, sandy.|270880|97",
"Yu-Gi-Oh! Duel Links|2017|KONAMI|Card Game,Strategy,Turn-Based|PC||Take on Duelists around the world with Yu-Gi-Oh! Duel Links! Step into a world that crosses.|601510|83",
"Stick Fight: The Game|2017|Landfall West|Fighting,Action,Co-op|PC,Mac||Stick Fight is a physics-based couch/online fighting game where you battle it out as the iconic.|674940|94",
"CRSED: Cuisine Royale|2018|Darkflow Software|Battle Royale,Open World,Survival|PC||CRSED: Cuisine Royale - is a brutal MMO last-man-standing shooter with realistic weaponry.|884660|79",
"Kingdom Two Crowns|2018|Stumpy🐙Squid|Tower Defence,City Builder,Strategy|PC,Mac,Linux||Gather coins, build defenses and reclaim your fallen Kingdom. Explore and uncover secrets.|701160|88",
"Mirror 2: Project X|2022|KAGAMI Ⅱ WORKs|Visual Novel,Adventure,FPS|PC||Enter the parallel worlds enriched by the stories and match-3 games developed using cel-shading.|1832640|25",
"Torchlight II|2012|Runic Games|RPG,Action RPG,Hack and Slash|PC,Mac,Linux|88|The adventure continues in Torchlight II! An Action RPG filled with epic battles, bountiful.|200710|93",
"Supermarket Together|2024|DeadDevsTellNoLies|Simulation,Co-op,Management|PC||The multiplayer supermarket has arrived to your neighbourhood for free! Stock your shop space.|2709570|95",
"Borderlands: The Pre-Sequel|2014|2K Australia|Shooter,Co-op,FPS|PC,Mac,Linux|75|Launch into the Borderlands universe and shoot 'n' loot your way through a brand new adventure.|261640|79",
"Fistful of Frags|2014|Fistful of Frags Team|FPS,Survival,Shooter|PC,Mac,Linux||Multiplayer based, first person enabled, action packed and skill demanding shooter set in the.|265630|91",
"Hotline Miami|2012|Dennaton Games|Action,Shooter,Rhythm|PC,Mac,Linux|85|Hotline Miami is a high-octane action game overflowing with raw brutality, hard-boiled gunplay.|219150|97",
"The Expendabros|2014|Free Lives|Action,Co-op,Shooter|PC,Mac||The Expendabros have assembled and set their sights on the forces of ruthless arms dealer.||97",
"Rising Storm 2: Vietnam|2017|Antimatter Games|FPS,MMO,Immersive Sim|PC|81|Red Orchestra Series' take on Vietnam: 64-player MP matches; 20+ maps; US Army & Marines.|418460|87",
"RaceRoom Racing Experience|2013|KW Studios|Racing,Simulation,Sports|PC||RaceRoom is free to download and built on true-to-life physics and Force Feedback. Drive DTM.|211500|75",
"Last Man Standing|2017|Free Reign Entertainment|Survival,Open World,Shooter|PC||The Ultimate BATTLE ROYALE! Sharpen your skills and kill everyone in your way as you hunt for.||61",
"Total War: ROME II - Emperor Edition|2013|CREATIVE ASSEMBLY|Strategy,Tactical,RTS|PC,Mac|76|Emperor Edition is the definitive edition of ROME II, featuring an improved politics system.|214950|83",
"Skullgirls 2nd Encore|2013|Hidden Variable Studios|Fighting,Action,Arcade|PC,Mac,Linux|83|--Main Stage Game at Evo 2022!-- The ultimate Skullgirls experience: Featuring 14 hand-animated.|245170|73",
"Red Orchestra 2: Heroes of Stalingrad with Rising Storm|2011|Tripwire Interactive|FPS,Immersive Sim,Action|PC|76|Contains full Rising Storm content as well!|35450|92",
"Gang Beasts|2017|Boneloaf|Party,Fighting,Co-op|PC,Mac,Linux||Gang Beasts is a silly multiplayer party game with surly gelatinous characters, brutal.|285900|85",
"Killing Floor 2|2016|Tripwire Interactive|Co-op,FPS,Hack and Slash|PC|75|In KILLING FLOOR 2, players descend into continental Europe after it has been overrun by.|232090|88",
"Century: Age of Ashes|2021|Playwing LTD|Action,Hero Shooter,Shooter|PC||Century: Age of Ashes is a free-to-play multiplayer dragon shooter. Master a growing roster of.|918570|75",
"Guns of Icarus Online|2012|Muse Games|Co-op,Action,Tactical|PC,Mac,Linux|64|Assemble your crew, take to the skies in the premier PvP airship combat game. Guns of Icarus.|209080|90",
"Mortal Kombat X|2015|NetherRealm Studios|Fighting,Action,Arcade|PC|84|Experience the Next Generation of the #1 Fighting Franchise. Mortal Kombat X combines.|307780|85",
"Transformice|2015|Atelier 801|MMO,Platformer,Racing|PC,Mac,Linux||Transformice is an MMO platformer about dozens of mice running to bring back the cheese! Will.|335240|88",
"Spiral Knights|2011|Grey Havens|MMO,RPG,Adventure|PC,Mac|64|Join the ranks of the Spiral Knights. Stranded on an alien world, you must explore the.|99900|84",
"Helltaker|2020|vanripper|Puzzle,Adventure,Rhythm|PC,Mac,Linux||Helltaker is a short game about sharply dressed demon girls.|1289310|98",
"The Tiny Bang Story|2011|Colibri Games|Point and Click,Puzzle,Adventure|PC,Mac,Linux|63|Life on Tiny Planet was calm and carefree until a great disaster occurred - Tiny Planet was hit.|96000|87",
"Trine 2: Complete Story|2013|Frozenbyte|Platformer,Adventure,Action|PC,Mac,Linux|84|Three Heroes make their way through dangers untold in a fairytale world, featuring.|35720|95",
"Pummel Party|2018|Rebuilt Games|Co-op,Party,Action|PC||Pummel Party is a 4-8 player online and local-multiplayer party game. Pummel friends or AI.|880940|89",
"Scrap Mechanic|2026|Axolot Games|Sandbox,Survival,Open World|PC||Enter the creative paradise of Scrap Mechanic! Build fantastic machines, go on adventures with.|387990|92",
"Cookie Clicker|2021|Orteil|Simulation,Management,Horror|PC,Mac||An idle game about making cookies! Originally released in 2013 on the web, and actively.|1454400|97",
"Hotline Miami 2: Wrong Number|2015|Dennaton Games|Action,Shooter,Arcade|PC,Mac,Linux||Hotline Miami 2: Wrong Number is the brutal conclusion to the Hotline Miami saga, set against a.|274170|94",
"POSTAL|1997|Running With Scissors|Horror,Shooter,Action|PC,Mac,Linux|56|Take control of The POSTAL Dude in his infamous first outing as he battles to survive in a.|232770|91",
"Minimalism|2017|PixelMouse|Action,Platformer,Adventure|PC||Minimalism - platformer with a lot of levels, made in minimalist style - which is a cube.||73",
"Company of Heroes - Legacy Edition|2007|Relic Entertainment|Strategy,RTS,Action|PC|93|Delivering a visceral WWII gaming experience, Company of Heroes redefines RTS by bringing the.|4560|93",
"Gray Zone Warfare|2024|MADFINGER Games, a.s.|Co-op,Tactical,FPS|PC||Enter a high-stakes PvE-first open-world tactical shooter set on a quarantined Southeast Asian.|2479810|68",
"Shadow Warrior|2013|Flying Wild Hog|Action,FPS,Hack and Slash|PC,Mac,Linux|74|Shadow Warrior is a bold reimagining of the classic 3D Realms' shooter from independent.|233130|92",
"Wolfenstein: Youngblood|2019|MachineGames|Action,Co-op,FPS|PC|69|Wolfenstein: Youngblood is the first modern co-op Wolfenstein adventure. Team up with a friend.|1056960|44",
"Codename CURE|2017|Raptor Byte|Shooter,Horror,Co-op|PC,Linux||Codename CURE is a first person, co-operative zombie game with support for up to five players.|355180|85",
"Block N Load|2015|Toadman Interactive|Action,FPS,Shooter|PC|72|Five of you. Five of them. Face off in a battle where everything you build, destroy, construct.||79",
"South Park: The Stick of Truth|2014|Obsidian Entertainment|RPG,Adventure,Turn-Based|PC||From the perilous battlefields of the fourth-grade playground, a young hero will rise, destined.|213670|98",
"World of Guns: Gun Disassembly|2014|Noble Empire Corp.|Simulation,Puzzle,Exploration|PC,Mac,Linux||World of Guns: Gun Disassembly lets you delve into the inner workings of guns from the largest.|262410|84",
"Defiance|2014|Trion Worlds|Shooter,Open World,Action|PC|64|Join the futuristic online open-world shooter where thousands of players scour a transformed.|224600|77",
"Kingdom: Classic|2015|Noio|Strategy,Simulation,Management|PC,Mac,Linux|74|Kingdom is a 2D sidescrolling strategy/resource management hybrid with a minimalist feel.|368230|91",
"Liar's Bar|2024|Curve Animation|Co-op,FPS,Puzzle|PC||Dive into this multiplayer online experience set in a sketchy bar where the games are as.|3097560|91",
"Kenshi|2018|Lo-Fi Games|Open World,Sandbox,RPG|PC|75|A free-roaming squad based RPG. Focusing on open-ended sandbox gameplay features rather than a.|233860|95"
]);
