/* Postgame — game catalogue, part 3 of 5 */
window.GAME_ROWS = (window.GAME_ROWS || []).concat([
"Baldur's Gate II: Shadows of Amn|2000|BioWare|RPG|PC,Mac|95|The high-water mark for isometric party RPGs.",
"Pillars of Eternity|2015|Obsidian Entertainment|RPG|PC,PS4,Xbox One|89|A loving revival of the Infinity Engine era.",
"The Outer Worlds|2019|Obsidian Entertainment|Action RPG|PC,PS4,Switch,Xbox One|85|Corporate satire in a colourful frontier colony.",
"Pentiment|2022|Obsidian Entertainment|Adventure,RPG|PC,Xbox Series,Switch|86|A murder mystery drawn as an illuminated manuscript.",
"Kingdom Come: Deliverance|2018|Warhorse Studios|Action RPG,Open World|PC,PS4,Xbox One|76|Realistic medieval Bohemia with brutal swordplay.",
"Kingdom Come: Deliverance II|2025|Warhorse Studios|Action RPG,Open World|PC,PS5,Xbox Series|88|Henry's story continues with far more polish.",
"Monster Hunter: World|2018|Capcom|Action RPG|PC,PS4,Xbox One|90|The hunt finally made welcoming to everyone.",
"Monster Hunter Rise|2021|Capcom|Action RPG|Switch,PC,PS5,Xbox Series|87|Wirebug mobility makes hunting acrobatic.",
"Monster Hunter Wilds|2025|Capcom|Action RPG,Open World|PC,PS5,Xbox Series|88|Seamless, weather-driven hunting grounds.",
"Monster Hunter 4 Ultimate|2014|Capcom|Action RPG|3DS|86|Verticality and the handheld hunt at its peak.",
"Resident Evil 4|2005|Capcom|Horror,TPS|GameCube,PS2,Wii,PC|96|The over-the-shoulder camera that reshaped action games.",
"Resident Evil 4 Remake|2023|Capcom|Horror,TPS|PC,PS5,Xbox Series|93|A remake that honours and improves a classic.",
"Resident Evil 2 Remake|2019|Capcom|Horror,TPS|PC,PS4,Xbox One|91|Raccoon City rebuilt with an unkillable stalker.",
"Resident Evil 7: Biohazard|2017|Capcom|Horror,FPS|PC,PS4,Xbox One|86|First-person terror in a Louisiana farmhouse.",
"Resident Evil Village|2021|Capcom|Horror,FPS|PC,PS5,Xbox Series|84|Gothic villages, tall vampires, generous action.",
"Resident Evil 2|1998|Capcom|Horror|PS1,PC,GameCube|89|Two scenarios, one doomed police station.",
"Devil May Cry 5|2019|Capcom|Action,Hack and Slash|PC,PS4,Xbox One|88|Style ranks and three ludicrous protagonists.",
"Devil May Cry 3: Dante's Awakening|2005|Capcom|Action,Hack and Slash|PS2,PC,Switch|84|Punishing, brilliant, the series' backbone.",
"Street Fighter II|1991|Capcom|Fighting|Arcade,SNES,Genesis|93|The arcade cabinet that invented the fighting scene.",
"Street Fighter IV|2009|Capcom|Fighting|Arcade,PS3,Xbox 360,PC|93|The revival that brought fighters back.",
"Street Fighter 6|2023|Capcom|Fighting|PC,PS5,Xbox Series|92|Drive system, World Tour, best onboarding ever.",
"Marvel vs. Capcom 2|2000|Capcom|Fighting|Arcade,Dreamcast,PS2|90|Four-button chaos and an immortal soundtrack.",
"Mega Man 2|1988|Capcom|Platformer,Action|NES,Switch|91|Boss order as a puzzle, music as a legend.",
"Mega Man X|1993|Capcom|Platformer,Action|SNES,PC,Switch|89|Dashing, wall-jumping, armour hunting perfection.",
"Okami|2006|Clover Studio|Action Adventure|PS2,Wii,PC,Switch|93|Paint the world back to life as a wolf god.",
"Dragon's Dogma: Dark Arisen|2013|Capcom|Action RPG,Open World|PS3,Xbox 360,PC,Switch|82|Climb the griffin. Trust your pawns.",
"Dragon's Dogma 2|2024|Capcom|Action RPG,Open World|PC,PS5,Xbox Series|87|A stubborn, systemic world that resists convenience.",
"Phoenix Wright: Ace Attorney|2001|Capcom|Visual Novel,Adventure|GBA,DS,Switch,PC|81|Objection. Courtroom drama as pure comedy.",
"Metal Gear Solid|1998|Konami|Stealth,Action|PS1,PC,GameCube|94|Cinematic stealth and a fourth wall in pieces.",
"Metal Gear Solid 2: Sons of Liberty|2001|Konami|Stealth,Action|PS2,Xbox,PC|96|A prophetic essay disguised as a spy thriller.",
"Metal Gear Solid 3: Snake Eater|2004|Konami|Stealth,Action|PS2,PS3,3DS|91|Jungle survival and the greatest boss duel.",
"Metal Gear Solid V: The Phantom Pain|2015|Kojima Productions|Stealth,Open World|PC,PS4,Xbox One|93|The finest stealth sandbox ever built.",
"Death Stranding|2019|Kojima Productions|Action Adventure|PS4,PC,PS5|82|Delivering cargo across a haunted, gorgeous America.",
"Death Stranding 2: On the Beach|2025|Kojima Productions|Action Adventure|PS5,PC|87|Stranger roads, bigger ideas, same strange heart.",
"Silent Hill 2|2001|Konami|Horror|PS2,Xbox,PC|89|Grief rendered as fog and rusted metal.",
"Silent Hill 2 Remake|2024|Bloober Team|Horror|PC,PS5|86|A remake that finally justified itself.",
"Castlevania: Symphony of the Night|1997|Konami|Metroidvania,Action|PS1,Xbox 360,Mobile|93|The castle that named half a genre.",
"Contra|1987|Konami|Run and Gun,Action|Arcade,NES|87|Two players, thirty lives, endless spread gun.",
"Dance Dance Revolution|1998|Konami|Rhythm|Arcade,PS1|88|Arrows, arcades, and sweat.",
"Pro Evolution Soccer 6|2006|Konami|Sports|PS2,Xbox 360,PC|89|Football feel that FIFA chased for years.",
"Yakuza 0|2015|Ryu Ga Gotoku Studio|Action Adventure|PS4,PC,Xbox One|85|Bubble-era Japan, real estate, cabaret clubs, fists.",
"Yakuza: Like a Dragon|2020|Ryu Ga Gotoku Studio|JRPG,Turn-Based|PC,PS5,Xbox Series|84|The series becomes a turn-based comedy epic.",
"Like a Dragon: Infinite Wealth|2024|Ryu Ga Gotoku Studio|JRPG,Turn-Based|PC,PS5,Xbox Series|89|Hawaii, two heroes, and a huge warm heart.",
"Sonic the Hedgehog 2|1992|Sonic Team|Platformer|Genesis,Switch,PC|89|Momentum platforming with Tails in tow.",
"Sonic Adventure 2|2001|Sonic Team|Platformer,Action|Dreamcast,GameCube,PC|89|Hero and dark campaigns, immortal City Escape.",
"Sonic Mania|2017|Christian Whitehead|Platformer|PC,Switch,PS4,Xbox One|86|Classic Sonic made by the people who loved it.",
"Sonic Frontiers|2022|Sonic Team|Platformer,Open World|PC,PS5,Switch,Xbox Series|71|Open-zone Sonic with real potential.",
"Shenmue|1999|Sega AM2|Adventure,Simulation|Dreamcast,PC,PS4|89|A slow, sincere life simulation years ahead of itself.",
"Jet Set Radio|2000|Smilebit|Action,Rhythm|Dreamcast,PC,Xbox 360|94|Cel-shaded graffiti skating with a killer soundtrack.",
"Shin Megami Tensei V|2021|Atlus|JRPG,Turn-Based|Switch,PC,PS5|84|Demon negotiation in a ruined Tokyo desert.",
"Catherine|2011|Atlus|Puzzle,Adventure|PS3,Xbox 360,PC,Switch|82|Block puzzles about commitment and guilt.",
"Dragon Quest XI|2017|Square Enix|JRPG,Turn-Based|PS4,Switch,PC|87|Comfort-food JRPG storytelling done immaculately.",
"Dragon Quest VIII|2004|Level-5|JRPG,Turn-Based|PS2,3DS,Mobile|89|Cel-shaded charm and a huge overworld.",
"Ni no Kuni: Wrath of the White Witch|2011|Level-5|JRPG|PS3,PC,Switch,PS4|85|Studio Ghibli animation inside an RPG.",
"Kingdom Hearts II|2005|Square Enix|Action RPG|PS2,PS4,PS3|87|Disney worlds and preposterous, wonderful plot.",
"Kingdom Hearts III|2019|Square Enix|Action RPG|PS4,Xbox One,PC,Switch|83|A long-awaited finale with spectacular set pieces.",
"Octopath Traveler|2018|Square Enix|JRPG,Turn-Based|Switch,PC,PS4|83|Eight stories in stunning HD-2D.",
"Bravely Default|2012|Silicon Studio|JRPG,Turn-Based|3DS|85|Brave and default turn economy, brilliantly twisted.",
"Tales of Arise|2021|Bandai Namco Studios|JRPG,Action RPG|PC,PS5,Xbox Series|87|Real-time party combat and gorgeous art.",
"Clair Obscur: Expedition 33|2025|Sandfall Interactive|JRPG,Turn-Based|PC,PS5,Xbox Series|92|Turn-based combat with parries, and a stunning world.",
"Fire Emblem: Three Houses|2019|Intelligent Systems|Tactics,JRPG|Switch|89|Teach students, then send them to war.",
"Fire Emblem Awakening|2012|Intelligent Systems|Tactics,JRPG|3DS|92|The game that saved the whole franchise.",
"Xenoblade Chronicles|2010|Monolith Soft|JRPG,Open World|Wii,Switch,3DS|92|Two titans, one enormous adventure.",
"Xenoblade Chronicles 3|2022|Monolith Soft|JRPG,Open World|Switch|89|Ten soldiers reject a war built on lifespans.",
"Pokemon Red and Blue|1996|Game Freak|JRPG|GB|85|Gotta catch em all, from the start.",
"Pokemon Gold and Silver|1999|Game Freak|JRPG|GB,GBC|89|Two regions, day and night, breeding.",
"Pokemon Ruby and Sapphire|2002|Game Freak|JRPG|GBA|82|Hoenn, doubles battles, endless water routes.",
"Pokemon Diamond and Pearl|2006|Game Freak|JRPG|DS|85|Sinnoh, online trading, physical-special split.",
"Pokemon Black and White|2010|Game Freak|JRPG|DS|87|An all-new roster and a real story.",
"Pokemon X and Y|2013|Game Freak|JRPG|3DS|87|The series steps into full 3D with Mega Evolution.",
"Pokemon Sun and Moon|2016|Game Freak|JRPG|3DS|87|Alola trials replace the gym formula.",
"Pokemon Sword and Shield|2019|Game Freak|JRPG|Switch|80|Wild Area, Dynamax, and the first home-console generation.",
"Pokemon Scarlet and Violet|2022|Game Freak|JRPG,Open World|Switch|72|A genuinely open Pokemon world, rough at the seams.",
"Pokemon Legends: Arceus|2022|Game Freak|Action RPG|Switch|83|Catching reinvented as real-time stealth.",
"Pokemon Legends: Z-A|2025|Game Freak|Action RPG|Switch,Switch 2|82|One city, real-time battles, Mega Evolution back.",
"Pokemon GO|2016|Niantic|Mobile,AR|Mobile|69|The summer the whole world went outside.",
"Super Mario RPG|1996|Square|JRPG,Turn-Based|SNES,Switch|90|Mario's first RPG, and still one of the funniest.",
"Paper Mario: The Thousand-Year Door|2004|Intelligent Systems|JRPG,Turn-Based|GameCube,Switch|87|Stage-play presentation and razor-sharp writing.",
"Mario & Luigi: Superstar Saga|2003|AlphaDream|JRPG,Turn-Based|GBA,3DS|89|Two brothers, one button each, perfect timing.",
"Mario Party Superstars|2021|NDcube|Party|Switch|79|Classic boards and minigames, friendships optional.",
"Luigi's Mansion 3|2019|Next Level Games|Action Adventure|Switch|86|A haunted hotel of superb comic animation.",
"Kirby and the Forgotten Land|2022|HAL Laboratory|Platformer|Switch|85|Kirby's first full 3D adventure, and a car.",
"Kirby Super Star|1996|HAL Laboratory|Platformer,Action|SNES,Switch|89|Many small games, all of them generous.",
"Donkey Kong Country|1994|Rare|Platformer|SNES,Switch|89|Pre-rendered visuals that stunned a generation.",
"Donkey Kong Bananza|2025|Nintendo EPD|Platformer,Action|Switch 2|92|Smash through everything in a fully destructible world.",
"Banjo-Kazooie|1998|Rare|Platformer|N64,Xbox 360,Switch|92|Collect-a-thon platforming at its wittiest.",
"GoldenEye 007|1997|Rare|FPS|N64,Switch,Xbox 360|96|Split-screen deathmatch history, made in Twycross.",
"Perfect Dark|2000|Rare|FPS|N64,Xbox 360|97|Sci-fi espionage shooting far beyond its hardware.",
"Conker's Bad Fur Day|2001|Rare|Platformer,Action|N64,Xbox|92|A foul-mouthed squirrel parodying everything.",
"Star Fox 64|1997|Nintendo EAD|Shooter,Rail Shooter|N64,3DS,Switch|88|Do a barrel roll, forever.",
"F-Zero GX|2003|Amusement Vision|Racing|GameCube|89|Brutally fast, brutally hard futuristic racing.",
"Pikmin 4|2023|Nintendo EPD|Strategy,Adventure|Switch|87|Tiny squad management with enormous charm.",
"Wii Sports|2006|Nintendo EAD|Sports,Party|Wii|76|The pack-in that put motion controls in every living room.",
"Wii Sports Resort|2009|Nintendo EAD|Sports,Party|Wii|80|Twelve games and a swordfight everyone remembers.",
"Nintendogs|2005|Nintendo EAD|Life Sim|DS|84|Puppies, a touch screen, and a microphone.",
"Brain Age|2005|Nintendo SPD|Puzzle|DS|77|Daily arithmetic that sold to everyone's parents.",
"Tetris|1984|Alexey Pajitnov|Puzzle|Multi|94|Seven shapes. Infinite games.",
"Tetris Effect|2018|Monstars|Puzzle,Rhythm|PC,PS4,Switch,Xbox Series|89|Tetris as a synaesthetic light show.",
"Astro Bot|2024|Team Asobi|Platformer|PS5|94|Joyful invention in every single level.",
"Astro's Playroom|2020|Team Asobi|Platformer|PS5|82|A free pack-in that shows off a controller beautifully."
]);
