/* Postgame — game catalogue, part 6 of 10
   Row format: Title | Year | Developer | Genres | Platforms | Critic score | Blurb */
window.GAME_ROWS = (window.GAME_ROWS || []).concat([
"The Legend of Zelda|1986|Nintendo R&D4|Action Adventure|NES,Switch|84|The original open world, with no map and no mercy.",
"Zelda II: The Adventure of Link|1987|Nintendo R&D4|Action RPG,Platformer|NES,Switch|72|The odd one out: side-on combat and towns.",
"The Legend of Zelda: The Minish Cap|2004|Capcom|Action Adventure|GBA,3DS|89|Shrink to insect size and see Hyrule differently.",
"The Legend of Zelda: Oracle of Ages|2001|Capcom|Action Adventure|GBC,3DS|89|Time travel puzzling, one half of a linked pair.",
"The Legend of Zelda: Skyward Sword|2011|Nintendo EAD|Action Adventure|Wii,Switch|93|Motion swordplay and the origin of the whole legend.",
"The Legend of Zelda: A Link Between Worlds|2013|Nintendo EPD|Action Adventure|3DS|91|Become a drawing on the wall to solve dungeons.",
"The Legend of Zelda: Echoes of Wisdom|2024|Grezzo|Action Adventure|Switch|86|Zelda finally leads, copying objects instead of swinging swords.",
"Super Mario Bros. 2|1988|Nintendo EAD|Platformer|NES,Switch|80|Pull vegetables out of the ground. Genuinely strange.",
"Super Mario Sunshine|2002|Nintendo EAD|Platformer|GameCube,Switch|92|A water cannon, a tropical island, and real bite.",
"Super Mario Galaxy 2|2010|Nintendo EAD|Platformer|Wii,Switch|97|More ideas per level than most series manage in a decade.",
"Super Mario 3D World|2013|Nintendo EAD|Platformer|Wii U,Switch|93|The cat suit, and four-player 3D Mario that works.",
"Super Mario 3D Land|2011|Nintendo EAD|Platformer|3DS|90|The bridge between 2D and 3D Mario, built perfectly.",
"New Super Mario Bros.|2006|Nintendo EAD|Platformer|DS|89|The revival that sold to absolutely everyone.",
"New Super Mario Bros. Wii|2009|Nintendo EAD|Platformer|Wii|87|Four players, one screen, immediate betrayal.",
"Super Mario Maker 2|2019|Nintendo EPD|Platformer,Sandbox|Switch|88|Build the level, then watch strangers suffer through it.",
"Super Mario World 2: Yoshi's Island|1995|Nintendo EAD|Platformer|SNES,GBA|91|Crayon art and egg throwing, still unmatched.",
"Yoshi's Crafted World|2019|Good-Feel|Platformer|Switch|79|Cardboard and felt dioramas you can walk through.",
"Mario Kart 64|1996|Nintendo EAD|Racing|N64,Switch|83|Rainbow Road, four controllers, permanent grudges.",
"Mario Kart: Double Dash|2003|Nintendo EAD|Racing|GameCube|87|Two drivers per kart, and the best item juggling.",
"Mario Kart DS|2005|Nintendo EAD|Racing|DS|91|Snaking, mission mode, and the first great online kart racer.",
"Mario Tennis Aces|2018|Camelot Software Planning|Sports|Switch|75|Tennis with a shot clock and a rage meter.",
"Super Mario Party Jamboree|2024|NDcube|Party|Switch,Switch 2|81|Seven boards and a hundred ways to lose a friend.",
"Mario Party|1998|Hudson Soft|Party|N64|79|The original, and the one that gave everyone blisters.",
"Paper Mario|2000|Intelligent Systems|JRPG,Turn-Based|N64,Switch|93|Flat heroes, deep battles, immaculate comic timing.",
"Super Paper Mario|2007|Intelligent Systems|Platformer,JRPG|Wii|85|Flip between 2D and 3D to get past walls.",
"Paper Mario: The Origami King|2020|Intelligent Systems|Adventure,JRPG|Switch|80|Gorgeous set pieces and a surprisingly sad paper boat.",
"Mario & Luigi: Bowser's Inside Story|2009|AlphaDream|JRPG,Turn-Based|DS,3DS|90|Play as Bowser while the brothers wreck his insides.",
"Mario & Luigi: Brothership|2024|Acquire|JRPG,Turn-Based|Switch|75|Island hopping with the brothers' timing intact.",
"Luigi's Mansion|2001|Nintendo EAD|Action Adventure|GameCube,3DS|78|Vacuum ghosts in the dark, terrified the whole time.",
"Captain Toad: Treasure Tracker|2014|Nintendo EPD|Puzzle,Platformer|Wii U,Switch|81|Tiny diorama puzzles for a man who cannot jump.",
"Donkey Kong Country 2: Diddy's Kong Quest|1995|Rare|Platformer|SNES,Switch|92|Harder, darker, and the finest soundtrack on the SNES.",
"Donkey Kong Country: Tropical Freeze|2014|Retro Studios|Platformer|Wii U,Switch|83|Brutal, beautiful 2D platforming from the Metroid Prime team.",
"Donkey Kong 64|1999|Rare|Platformer|N64|88|Five characters, a golden banana for everything.",
"Diddy Kong Racing|1997|Rare|Racing|N64,DS|88|Karts, hovercraft and planes with an adventure mode.",
"Banjo-Tooie|2000|Rare|Platformer|N64,Xbox 360|90|Bigger, denser, and far more ambitious than the first.",
"Kirby's Adventure|1993|HAL Laboratory|Platformer|NES,Switch|85|Copy abilities arrive and change Kirby forever.",
"Kirby's Dream Land|1992|HAL Laboratory|Platformer|GB,Switch|80|Short, sweet, and pink. Where it all started.",
"Kirby's Return to Dream Land|2011|HAL Laboratory|Platformer|Wii,Switch|77|Four-player Kirby with super abilities.",
"Kirby Air Riders|2025|Bandai Namco Studios|Racing,Action|Switch 2|85|Sakurai's racing oddity, finally revived.",
"Metroid|1986|Nintendo R&D1|Metroidvania|NES,Switch|86|The lonely planet that named a genre.",
"Metroid Fusion|2002|Nintendo R&D1|Metroidvania|GBA,Switch|92|Tighter and tenser, with something hunting you.",
"Metroid Prime 2: Echoes|2004|Retro Studios|FPS,Metroidvania|GameCube,Switch|92|Light and dark worlds, and a punishing ammo economy.",
"Metroid Prime 3: Corruption|2007|Retro Studios|FPS,Metroidvania|Wii|90|Pointer controls that made the series feel new.",
"Metroid Prime 4: Beyond|2025|Retro Studios|FPS,Metroidvania|Switch,Switch 2|89|Eight years of waiting, and it lands.",
"Splatoon|2015|Nintendo EAD|Shooter|Wii U|81|Ink, squids, and a shooter unlike any other.",
"Splatoon 2|2017|Nintendo EPD|Shooter|Switch|83|Salmon Run and the Splatfests that ate weekends.",
"Animal Crossing|2001|Nintendo EAD|Life Sim|GameCube|87|A village that carries on whether you visit or not.",
"Animal Crossing: New Leaf|2012|Nintendo EAD|Life Sim|3DS|88|You are the mayor now. Good luck with the paperwork.",
"Pikmin|2001|Nintendo EAD|Strategy,Adventure|GameCube,Switch|89|Thirty days to rebuild a ship with tiny help.",
"Pikmin 2|2004|Nintendo EAD|Strategy,Adventure|GameCube,Switch|90|No time limit, much deeper caves, far crueller.",
"Pikmin 3|2013|Nintendo EAD|Strategy,Adventure|Wii U,Switch|85|Three captains, fruit juice logistics, gorgeous close-ups.",
"Fire Emblem: Path of Radiance|2005|Intelligent Systems|Tactics,JRPG|GameCube|85|Ike, mercenaries, and a war worth caring about.",
"Fire Emblem Fates|2015|Intelligent Systems|Tactics,JRPG|3DS|87|Pick a family and betray the other one.",
"Fire Emblem Engage|2023|Intelligent Systems|Tactics,JRPG|Switch|80|Thin story, some of the best maps in the series.",
"Advance Wars|2001|Intelligent Systems|Tactics,Strategy|GBA|92|Cheerful cartoon officers running a merciless war.",
"Xenoblade Chronicles 2|2017|Monolith Soft|JRPG,Open World|Switch|83|Blades, titans, and a hundred hours of systems.",
"Xenoblade Chronicles X|2015|Monolith Soft|JRPG,Open World|Wii U,Switch|84|An alien planet you eventually get a mech to explore.",
"Star Fox|1993|Nintendo EAD|Shooter,Rail Shooter|SNES|85|Polygons in 1993, courtesy of a chip in the cartridge.",
"F-Zero|1990|Nintendo EAD|Racing|SNES,Switch|84|Mode 7 speed that still feels dangerous.",
"Punch-Out!!|1987|Nintendo R&D3|Sports,Fighting|NES,Switch|84|Pattern recognition disguised as boxing.",
"EarthBound|1994|Ape|JRPG,Turn-Based|SNES,Switch|89|Suburban America as an RPG, funny until it is not.",
"Golden Sun|2001|Camelot Software Planning|JRPG,Turn-Based|GBA|91|Psynergy puzzles and djinn on a handheld.",
"WarioWare, Inc.: Mega Microgames|2003|Nintendo R&D1|Party,Puzzle|GBA|89|Hundreds of games lasting five seconds each.",
"Rhythm Heaven|2008|Nintendo SPD|Rhythm|DS|83|Perfect timing taught by absolute nonsense.",
"Super Smash Bros.|1999|HAL Laboratory|Fighting,Party|N64|79|Twelve fighters and an idea nobody expected to work.",
"Super Smash Bros. Brawl|2008|Sora|Fighting,Party|Wii|93|Subspace Emissary and a roster that felt enormous.",
"Ring Fit Adventure|2019|Nintendo EPD|Fitness,RPG|Switch|83|Squats as an RPG combat system. It works.",
"Nintendo Switch Sports|2022|Nintendo EPD|Sports,Party|Switch|71|Wii Sports again, with volleyball and better legs.",
"Tomodachi Life|2013|Nintendo SPD|Life Sim|3DS|71|Your friends as Miis, behaving very badly.",
"Excitebike|1984|Nintendo R&D1|Racing|NES,Switch|76|Overheating engines and a level editor in 1984.",
"Pokemon HeartGold and SoulSilver|2009|Game Freak|JRPG|DS|87|Johto rebuilt, with your favourite walking beside you.",
"Pokemon Snap|1999|HAL Laboratory|Photography,Rail Shooter|N64|77|A rail shooter where the gun is a camera.",
"Pokemon Mystery Dungeon: Explorers of Sky|2009|Chunsoft|Roguelike,JRPG|DS|81|A roguelike that will genuinely make you cry.",
"Pokemon Unite|2021|TiMi Studio Group|MOBA|Switch,Mobile|70|Pokemon as a five-a-side MOBA, and it fits.",
"Bayonetta 2|2014|PlatinumGames|Action,Hack and Slash|Wii U,Switch|92|Umbran Climax, and combat close to perfect.",
"Bayonetta 3|2022|PlatinumGames|Action,Hack and Slash|Switch|87|Kaiju summons and multiverse nonsense at full volume.",
"Astral Chain|2019|PlatinumGames|Action|Switch|87|Fight alongside a chained partner. Nothing else plays like it.",
"The Wonderful 101|2013|PlatinumGames|Action|Wii U,Switch,PS4|78|Draw shapes to command a hundred tiny heroes.",
"God of War (2005)|2005|Santa Monica Studio|Action,Hack and Slash|PS2,PS3|94|Kratos at his angriest, in the Greece that made him.",
"God of War II|2007|Santa Monica Studio|Action,Hack and Slash|PS2,PS3|93|The PS2 pushed past what it should have managed.",
"God of War III|2010|Santa Monica Studio|Action,Hack and Slash|PS3,PS4|92|Olympus torn down at spectacular scale.",
"Uncharted: Drake's Fortune|2007|Naughty Dog|Action Adventure,TPS|PS3,PS4|88|The rough first draft of a great series.",
"Uncharted 3: Drake's Deception|2011|Naughty Dog|Action Adventure,TPS|PS3,PS4|92|The plane sequence, the desert, the spectacle.",
"The Last Guardian|2016|Team Ico|Adventure,Puzzle|PS4|82|A giant animal that obeys you only when it feels like it.",
"Gravity Rush|2012|Japan Studio|Action Adventure|Vita,PS4|83|Fall in whatever direction you like.",
"Killzone 2|2009|Guerrilla Games|FPS|PS3|91|Weighty, grey, and technically staggering for its time.",
"Resistance: Fall of Man|2006|Insomniac Games|FPS|PS3|86|Alternate-history Britain overrun, with excellent guns.",
"inFamous|2009|Sucker Punch Productions|Action,Open World|PS3|85|Electricity, grinding on rails, and a moral slider.",
"inFamous Second Son|2014|Sucker Punch Productions|Action,Open World|PS4|80|Neon Seattle and the prettiest smoke on the PS4.",
"LittleBigPlanet 2|2011|Media Molecule|Platformer,Sandbox|PS3|91|A toolkit disguised as a platformer.",
"Ratchet & Clank|2002|Insomniac Games|Action Platformer|PS2,PS3|88|Absurd weapons and a lombax with a wrench.",
"Ratchet & Clank: Up Your Arsenal|2004|Insomniac Games|Action Platformer|PS2|91|The series at its funniest and best armed.",
"Jak II|2003|Naughty Dog|Platformer,Action|PS2|87|The cheerful platformer turns grim and difficult.",
"Sly 2: Band of Thieves|2004|Sucker Punch Productions|Platformer,Stealth|PS2|88|Three thieves, one heist per chapter, superb writing.",
"Ape Escape|1997|Japan Studio|Platformer|PS1|86|The first game built around two analogue sticks.",
"PaRappa the Rapper|1996|NanaOn-Sha|Rhythm|PS1|92|I gotta believe. The first rhythm game that mattered.",
"WipEout|1995|Psygnosis|Racing|PS1,PC|89|Anti-gravity racing with a nightclub soundtrack.",
"Gran Turismo|1997|Polyphony Digital|Racing,Simulation|PS1|96|The racing simulator that changed the genre.",
"Gran Turismo 4|2004|Polyphony Digital|Racing,Simulation|PS2|89|Seven hundred cars and a photo mode people framed.",
"Days Gone|2019|Bend Studio|Action,Open World,Survival|PS4,PC|71|A biker, a bike, and hordes of hundreds."
]);
